# Splitting Config

"""
exception collected over the time so that I can re-build it from scratch
"""

splitters = " VS | vs | & | , |, | featuring\. | Featuring\. | featuring | Featuring | feat\. | feat\.|feat\. |feat\.| ft\. | ft\.|ft\. |ft\.| x | × | with |＆| / |/"
secondary_splitters = "・|& | &|&| ,|,| ×|× |×"

splitting_exception_list = [
    (
        "Tenshou Gakuen Seito・Kyoushi Ichidou",
        ("Tenshou Gakuen Seito Ichidou", "Tenshou Gakuen Kyoushi Ichidou",),
    ),
    ("HoneyWorks meets YURiCa/Hanatan", ("HoneyWorks", "YURiCa/Hanatan",)),
    ("OxT", ("OxT",)),
    ("Hironobu Kageyama & BROADWAY", ("Hironobu Kageyama & BROADWAY",)),
    ("Fear, and Loathing in Las Vegas", ("Fear, and Loathing in Las Vegas",)),
    ("Kishida Kyōdan &THE Akeboshi Rockets", ("Kishida Kyōdan &THE Akeboshi Rockets",)),
    ("angela Presents/Shoko Nakagawa", ("angela", "Shoko Nkagawa",),),
    ("G・GRIP", ("G・GRIP",)),
    ("Aozu + Cap to Bin", ("Aozu", "Cap to Bin",)),
    ("Hello, Happy World!", ("Hello, Happy World!",)),
    ("Happy Around! feat. KYOKO & SAKI", ("Happy Around!",)),
    (" G・GRIP", ("G・GRIP",)),
    ("HIKAKIN & SEIKIN", ("HIKAKIN & SEIKIN",)),
    ("PSY・S", ("PSY・S",)),
    ("Swing・Cats", ("Swing・Cats",)),
    ("F・MAP", ("F・MAP",)),
    ("a・chi-a・chi", ("a・chi-a・chi",)),
    ("hide with Spread Beaver", ("hide with Spread Beaver",)),
    ("A・Times", ("A・Times",)),
    ("SAY・S & Nintama Family", ("SAY・S", "Nintama Family",),),
    ("SAY・S and Nintama Family", ("SAY・S", "Nintama Family",),),
    ("R・O・N", ("R・O・N",)),
    ("Ja・Ja", ("Ja・Ja",)),
    ("B・B Girls", ("B・B Girls",)),
    ("G・P・S", ("G・P・S",)),
    ("M・A・O", ("M・A・O",)),
    ("Clover×Clover", ("Clover×Clover",)),
    ("LIP×LIP", ("LIP×LIP",)),
    ("Gothic×Luck", ("Gothic×Luck",)),
    ("High×Joker", ("High×Joker",)),
    ("RhymeTube×Odori Foot Works", ("RhymeTube×Odori Foot Works",)),
    ("salyu × salyu", ("salyu × salyu",)),
    ("Daisy×Daisy", ("Daisy×Daisy",)),
    ("SKET×Sketch", ("SKET×Sketch",)),
    ("kanon×kanon", ("kanon×kanon",)),
    ("U×Mishi", ("U×Mishi",)),
    ("DIVA×DIVA", ("DIVA×DIVA",)),
    ("sister×sisters", ("sister×sisters",)),
    ("Teikoku Kageki-dan・Hana-gumi", ("Teikoku Kageki-dan・Hana-gumi",)),
    ("nana×nana", ("nana×nana",)),
    ("U×Mishi", ("U×Mishi",)),
    ("r.o.r/s", ("r.o.r/s",)),
    ("can/goo", ("can/goo",)),
    ("Petit Rabbit's with beans", ("Petit Rabbit's with beans",)),
    ("NAMI with Shige×2＆S/N", ("NAMI", "Shige×2", "S/N",),),
    ("DISH//", ("DISH//",)),
    ("ON/OFF", ("ON/OFF",)),
    ("S/mileage", ("S/mileage",)),
    ("Konnichiwa\(^o^)/Kirarinbo☆Harry!!!", ("Konnichiwa\(^o^)/Kirarinbo☆Harry!!!",)),
    ("Sol/Lull BOB", ("Sol/Lull BOB",)),
    ("Kisu Koide (PANDA 1/2)", ("Kisu Koide (PANDA 1/2)",)),
    ("HoneyWorks meets YURiCa/Hanatan", ("HoneyWorks", "YURiCa", "Hanatan",),),
    ("+α/Alfakyun.", ("+α/Alfakyun.",)),
    ("H-el-ical//", ("H-el-ical//",)),
    ("22/7", ("22/7",)),
    ("Becky (& PokePark KIDS Gasshou-dan)", ("Becky", "PokePark KIDS Gasshou-dan",),),
    ("Masayoshi Ōishi (feat.Riria.)", ("Masayoshi Ōishi", "Riria.",),),
    ("Basement Jaxx (feat. Lisa Kekaula)", ("Basement Jaxx", "Lisa Kekaula",),),
    ("Moe Shop (feat.TORIENA)", ("Moe Shop", "TORIENA",),),
    (
        "TO-MAS feat. M・A・O and Minami Takahashi",
        ("TO-MAS", "M・A・O", "Minami Takahashi",),
    ),
    ("Unsho Ishizuka to Pokemon Kids", ("Unsho Ishizuka", "Pokemon Kids",),),
    (
        "Mori no Ki Jidou Gasshō-dan to Sono Otomodachi",
        ("Mori no Ki Jidou Gasshō-dan", "Sono Otomodachi",),
    ),
    (
        "Sogeking to Shounen Shoujo Gasshou-dan",
        ("Sogeking", "Shounen Shoujo Gasshou-dan",),
    ),
    (
        "Pupa Mucha to Muchachiita to Etsuko Kozakura to Mayuko Omimura to Akiko Suzuki to Rie Kugimiya",
        (
            "Pupa Mucha",
            "Muchachiita",
            "Etsuko Kozakura",
            "Mayuko Omimura",
            "Akiko Suzuki",
            "Rie Kugimiya",
        ),
    ),
    ("Kenji Ōtsuki to Emmanuel 5", ("Kenji Ōtsuki", "Emmanuel 5",),),
    (
        "Eri Itō to Mori no Ki Jidō Gasshō-dan",
        ("Eri Itō", "Mori no Ki Jidō Gasshō-dan",),
    ),
    ("CHEMISTRY meets m-flo", ("CHEMISTRY", "m-flo",),),
    ("m-flo\u2665DOPING PANDA", ("m-flo", "DOPING PANDA",),),
    ("Milan Himemiya to Chocolate Rockers", ("Milan Himemiya to Chocolate Rockers",)),
    (
        "Naomi Tamura to Himawari Gasshou-dan",
        ("Naomi Tamura", "Himawari Gasshou-dan",),
    ),
    ("Ushio to Ichiro", ("Ushio", "Ichiro",),),
    ("Osamu Yamada to Hello Nights", ("Osamu Yamada", "Hello Nights",),),
    (
        "LaSalle Ishii to Kochikame Win Gashō-dan",
        ("LaSalle Ishii", "Kochikame Win Gashō-dan"),
    ),
    ("Mitsuko Horie to Angel '03", ("Mitsuko Horie", "Angel '03",),),
    ("Haruna Ikezawa to Kōki Miyata", ("Haruna Ikezawa", "Kōki Miyata",),),
    (
        "Osamu Minagawa to Hibari Jidou Gasshou-dan",
        ("Osamu Minagawa", "Hibari Jidou Gasshou-dan"),
    ),
    ("Seiichi Yamamoto to Fushigi Robot", ("Seiichi Yamamoto", "Fushigi Robot",),),
    ("Akiko Kanazawa to Soichi Terada", ("Akiko Kanazawa", "Soichi Terada",),),
    ("Masaaki Endoh to Three G's 2005", ("Masaaki Endoh", "Three G's 2005",),),
    (
        "My Melodies to Maryland no Nakama-tachi",
        ("My Melodies", "Maryland no Nakama-tachi",),
    ),
    ("Yasushi Nakanishi and Chikako Sawada", ("Yasushi Nakanishi", "Chikako Sawada",),),
    ("Kenji Ōtsuki to Fumihiko Kitsutaka", ("Kenji Ōtsuki", "Fumihiko Kitsutaka",),),
    ("Kana Ueda to Yukai na Nakama-tachi", ("Kana Ueda", "Yukai na Nakama-tachi",),),
    ("Kenji Ōtsuki to Zetsubō Shōjo-tachi", ("Kenji Ōtsuki", "Zetsubō Shōjo-tachi",),),
    ("ROLLY to Zetsubō Shōjo-tachi", ("ROLLY", "Zetsubō Shōjo-tachi",),),
    ("Ayano Tsuji to BEAT CRUSADERS", ("Ayano Tsuji", "BEAT CRUSADERS",),),
    ("Ayumi Tsunematsu to Kodomo-tachi", ("Ayumi Tsunematsu", "Kodomo-tachi",),),
    (
        "Kenji Ōtsuki to Zetsubō Shōjo-tachi feat. Rap-bit",
        ("Kenji Ōtsuki", "Zetsubō Shōjo-tachi", "Rap-bit",),
    ),
    ("Athena & Robikerottsu", ("Athena & Robikerottsu",)),
    ("Saori Hayami to SeiVi-tai", ("Saori Hayami", "SeiVi-tai",),),
    ("Mikako Komatsu to Kana Hanazawa", ("Mikako Komatsu", "Kana Hanazawa",),),
    ("Masaaki Endoh to Moon Riders", ("Masaaki Endoh", "Moon Riders",),),
    ("Hajime Hana to Crazy Cats", ("Hajime Hana", "Crazy Cats",),),
    ("Ichirou Mizuki to Tokusatsu", ("Ichirou Mizuki", "Tokusatsu",),),
    ("FROGMAN to Red Chili Gasshou-dan", ("FROGMAN", "Red Chili Gasshou-dan",),),
    (
        "Yumiko Kobayashi to F-shigi na Nakama-tachi",
        ("Yumiko Kobayashi", "F-shigi na Nakama-tachi",),
    ),
    ("Kanako Miyamoto to Young Fresh", ("Kanako Miyamoto", "Young Fresh",),),
    ("Kana Asumi to Sakebu Jigoku-tai", ("Kana Asumi", "Sakebu Jigoku-tai",),),
    (
        "Asuka Nishi to Yukai na Nakama-tachi",
        ("Asuka Nishi", "Yukai na Nakama-tachi",),
    ),
    (
        "Misato Fukuen, Asami Tano, Hisako Kanemoto, Marina Inoue and Chinami Nishimura",
        (
            "Misato Fukuen",
            "Asami Tano",
            "Hisako Kanemoto",
            "Marina Inoue",
            "Chinami Nishimura",
        ),
    ),
    ("Velvet.kodhy to Velvet.kodhy to μ to μ", ("Velvet.kodhy", "μ",),),
    ("Melori to Cocotama Five", ("Melori", "Cocotama Five",),),
    ("Junji Majima to Youkai Taiji Sentai", ("Junji Majima", "Youkai Taiji Sentai",),),
    ("Hajime Akira to Tsukumo-chan", ("Hajime Akira", "Tsukumo-chan",),),
    ("Hyōtei Eternity to Rikkai Young Kan", ("Hyōtei Eternity", "Rikkai Young Kan",),),
    (
        "Hyoutei Setsunati to Rikkai Kai Shihan",
        ("Hyoutei Setsunati", "Rikkai Kai Shihan",),
    ),
    ("Junichi Suwabe to Sachiko Nagai", ("Junichi Suwabe", "Sachiko Nagai",),),
    ("15-sai to Seiko Oomori", ("15-sai", "Seiko Oomori",),),
    ("Kaede+Cheek Fairy", ("Kaede", "Cheek Fairy",),),
    ("Kiyoshirō Imawano+CHAR", ("Kiyoshirō Imawano", "CHAR",),),
    ('Hiroshi Kakizaki + "r" Project', ("Hiroshi Kakizaki", '"r" Project',),),
    (
        "Pokemon Kids & Unshō Ishizuka (+Ikue Ootani)",
        ("Pokemon Kids", "Unshō Ishizuka", "Ikue Ootani",),
    ),
    ("refio + Haruka Shimotsuki", ("refio", "Haruka Shimotsuki",),),
    ("Pokemon Kids (+Ikue Ootani)", ("Pokemon Kids", "Ikue Ootani",),),
    (
        "Pokemon Kids & Unshou Ishizuka (+Ikue Ootani)",
        ("Pokemon Kids", "Unshou Ishizuka", "Ikue Ootani",),
    ),
    (
        "Ichiro Mizuki & Apple Pie + The 4-B's",
        ("Ichiro Mizuki", "Apple Pie", "The 4-B's",),
    ),
    ("Gokujou Seitokai Yuugeki+Sharyoubu", ("Gokujou Seitokai Yuugeki", "Sharyoubu",),),
    (
        "Mahora Gakuen Chuutobu 3-A + Rina Satou",
        ("Mahora Gakuen Chuutobu 3-A", "Rina Satou",),
    ),
    ("SERENON with K", ("SERENON with K",)),
    (
        "Koji Yusa+Yuuichi Nakamura+Kishō Taniyama",
        ("Koji Yusa", "Yuuichi Nakamura", "Kishō Taniyama"),
    ),
    ("T-Pistonz+KMC", ("T-Pistonz", "KMC",),),
    (
        "Kanae Itō+Rie Kugimiya+Yuuko Gotō",
        ("Kanae Itō", "Rie Kugimiya", "Yuuko Gotō",),
    ),
    (
        "Rie Kugimiya+Yuuko Gotō+Kanae Itō",
        ("Rie Kugimiya", "Yuuko Gotō", "Kanae Itō",),
    ),
    (
        "Yuuko Gotō+Rie Kugimiya+Kanae Itō",
        ("Yuuko Gotō", "Rie Kugimiya", "Kanae Itō",),
    ),
    (
        "Junji Ishiwatari & Yoshinori Sunahara + Etsuko Yakushimaru",
        ("Junji Ishiwatari", "Yoshinori Sunahara", "Etsuko Yakushimaru",),
    ),
    (
        "Masayoshi Minoshima+REDALiCE feat.ayami",
        ("Masayoshi Minoshima", "REDALiCE", "ayami",),
    ),
    ("Melissa Hutchison and Alicyn Packard", ("Melissa Hutchison", "Alicyn Packard",),),
    ("DJ mash + Rinku with VJ Only", ("DJ mash", "Rinku", "VJ Only"),),
    ("Dream5+Burii Taichou", ("Dream5", "Burii Taichou",),),
    ("T-Pistonz+KMZ with Little Blue boX", ("T-Pistonz", "KMZ", "Little Blue boX",),),
    ("m-flo+daoko", ("m-flo", "daoko",),),
    ("SoLaMiDressing+Falulu", ("SoLaMiDressing", "Falulu",),),
    ("SAINTS+SoLaMiDressing", ("SAINTS", "SoLaMiDressing",),),
    (
        "Kaede Hondo with Cocotama9 + Ayaka Nanase",
        ("Kaede Hondo", "Cocotama9", "Ayaka Nanase",),
    ),
    (
        "HoneyWorks meets Sayuringo Gundan + Manatsu-san Respect Gundan from Nogizaka46",
        ("HoneyWorks", "Sayuringo Gundan", "Manatsu-san Respect Gundan", "Nogizaka46",),
    ),
    (
        "Etsuko Yakushimaru + Yoshinori Sunahara",
        ("Etsuko Yakushimaru", "Yoshinori Sunahara",),
    ),
    ("QUANGO & SPARKY", ("QUANGO & SPARKY",)),
    ("TAKAO & THE VIEW", ("TAKAO & THE VIEW",)),
    ("MAHO-dou + Kodomo-tachi", ("MAHO-dou", "Kodomo-tachi",),),
    ("Takanori Nishikawa+ASCA", ("Takanori Nishikawa", "ASCA",),),
    ("Cotori with Stitchbird", ("Cotori with Stitchbird",)),
    (
        "Dai 501 Tougou Sentou Koukuu-dan + Aya Uchida",
        ("Dai 501 Tougou Sentou Koukuu-dan", "Aya Uchida",),
    ),
    ("kanon×kanon", ("kanon×kanon",)),
    (
        "livetune adding Fukase from SEKAI NO OWARI",
        ("livetune", "Fukase from SEKAI NO OWARI",),
    ),
    (
        "livetune adding Rin Oikawa (from Q;Indivi)",
        ("livetune", "Rin Oikawa (from Q;Indivi)",),
    ),
    ("livetune adding Anna Yano", ("livetune", "Anna Yano",),),
    (
        "livetune adding Takuro Sugawara from 9mm Parabellum Bullet",
        ("livetune", "Takuro Sugawara from 9mm Parabellum Bullet",),
    ),
    ("Schrödinger's Cat adding kotringo", ("Schrödinger's Cat", "kotringo",),),
    ("livetune adding Yun*chi", ("livetune", "Yun*chi",),),
    ("Dimitri From Paris Voice Chiwa Saito", ("Dimitri From Paris", "Chiwa Saito",),),
    ("Mix Speaker's,Inc.", ("Mix Speaker's,Inc.",)),
    ("Kamisama, Boku wa Kizuite Shimatta", ("Kamisama, Boku wa Kizuite Shimatta",)),
    ("SawanoHiroyuki[nZk]:Uru", ("SawanoHiroyuki[nZk]", "Uru",),),
    ("SawanoHiroyuki[nZk]:Anly", ("SawanoHiroyuki[nZk]", "Anly",),),
    ("SawanoHiroyuki[nZk]:LiSA", ("SawanoHiroyuki[nZk]", "LiSA",),),
    ("livetune adding Yuuki Ozaki", ("livetune", "Yuuki Ozaki",),),
    (
        "SawanoHiroyuki[nZk]:Jean-Ken Johnny",
        ("SawanoHiroyuki[nZk]", "Jean-Ken Johnny",),
    ),
    ("SawanoHiroyuki[nZk]:Laco", ("SawanoHiroyuki[nZk]", "Laco",),),
    ("SawanoHiroyuki[nZk]:ReoNa", ("SawanoHiroyuki[nZk]", "ReoNa",),),
    ("SawanoHiroyuki[nZk]:mizuki", ("SawanoHiroyuki[nZk]", "mizuki",),),
    ("SawanoHiroyuki[nZk]:Gemie", ("SawanoHiroyuki[nZk]", "Gemie",),),
    ("SawanoHiroyuki[nZk]:Yosh", ("SawanoHiroyuki[nZk]", "Yosh",),),
    ("SawanoHiroyuki[nZk]:Tielle", ("SawanoHiroyuki[nZk]", "Tielle",),),
    ("SawanoHiroyuki[nZk]:naNami", ("SawanoHiroyuki[nZk]", "naNami",),),
    ("SawanoHiroyuki[nZk]:Aimer", ("SawanoHiroyuki[nZk]", "Aimer",),),
    (
        "ave;new project feat Saori Sakura×Dorechu",
        ("ave;new project", "Saori Sakura", "Dorechu",),
    ),
    ("KING & QUEEN", ("KING & QUEEN",)),
    ("C&K", ("C&K",)),
    ("P&P", ("P&P",)),
    ("P4 with T", ("P4 with T",)),
    ("MAYA & Z", ("MAYA & Z",)),
    ("Icchi & Naru", ("Icchi & Naru",)),
    ("Licca & Nao", ("Licca", "Noa",),),
    ("Cotori with Stitchbird", ("Cotori with Stitchbird",)),
    (
        'SOIL&"PIMP"SESSIONS feat. Maaya Sakamoto',
        ('SOIL&"PIMP"SESSIONS', "Maaya Sakamoto",),
    ),
    ("Kaako & Papa", ("Kaako & Papa",)),
    (
        "You & Explosion Band feat. Lyn Inaizumi",
        ("You & Explosion Band", "Lyn Inaizumi",),
    ),
    (
        "Yuji Ohno & Lupintic Six with Friends feat. Miyuki Sawashiro",
        ("Yuji Ohno", "Lupintic Six with Friends", "Miyuki Sawashiro",),
    ),
    (
        "Yuji Ohno & Lupintic Six with Friends feat. Shigeru Matsuzaki",
        ("Yuji Ohno", "Lupintic Six with Friends", "Shigeru Matsuzaki",),
    ),
    (
        "Yuji Ohno&Lupintic Five with Friends feat. Yoshie Nakano (EGO-WRAPPIN')",
        ("Yuji Ohno", "Lupintic Five with Friends", "Yoshie Nakano (EGO-WRAPPIN')",),
    ),
    ("Yuji Ohno & Lupintic Six", ("Yuji Ohno", "Lupintic Six",),),
    (
        "Yuji Ohno & Lupintic Five with Friends Feat. DOUBLE",
        ("Yuji Ohno", "Lupintic Five with Friends", "DOUBLE",),
    ),
    ("New man Co.,Ltd.", ("New man Co.,Ltd.",)),
    ("Hamatora - Ryota Osaka & Wataru Hatano", ("Ryota Osaka", "Wataru Hatano",),),
    ("Adiamond -Amy & Bibian-", ("Adiamond -Amy & Bibian-",)),
    ("MAYUKO & Luminous", ("MAYUKO & Luminous",)),
    ("Bars & Melody", ("Bars & Melody",)),
    (
        "Rekka Katakiri meets Desen\u2606Rizotto",
        ("Rekka Katakiri", "Desen\u2606Rizotto",),
    ),
    ("MON & STER", ("MON & STER",)),
    ("MYTH & ROID", ("MYTH & ROID",)),
    ("DEJO & BON", ("DEJO & BON",)),
    ("Kakki & Ash Potato", ("Kakki & Ash Potato",)),
    ("Anamu & Maki", ("Anamu & Maki",)),
    ("SUEMITSU & THE SUEMITH", ("SUEMITSU & THE SUEMITH",)),
    ("TAKAKO&THE CRAZY BOYS", ("TAKAKO&THE CRAZY BOYS",)),
    ("TAKAKO & THE CRAZY BOYS", ("TAKAKO & THE CRAZY BOYS",)),
    ("Ōsugi & Hiiko", ("Ōsugi & Hiiko",)),
    ("Christy&Clinton", ("Christy&Clinton",)),
    ("Irene & Erika", ("Irene & Erika",)),
    (
        "Kazaki Morinaka meets \u25bd\u25b2TRiNITY\u25b2\u25bd",
        ("Kazaki Morinaka", "\u25bd\u25b2TRiNITY\u25b2\u25bd",),
    ),
    ("Dylan & Catherine", ("Dylan & Catherine",)),
    ("Junich & JJr", ("Junich & JJr",)),
    ("Bread & Butter", ("Bread & Butter",)),
    ("Betsy & Chris", ("Betsy & Chris",)),
    ("RUN&GUN", ("RUN&GUN",)),
    ("Macolin & Pythagoras", ("Macolin & Pythagoras",)),
    ("ZONE&Run Time All Stars", ("ZONE&Run Time All Stars",)),
    ("Rats & Star", ("Rats & Star",)),
    ("Aki & Isao", ("Aki & Isao",)),
    ("Let's Go BOYS & GIRLS", ("Let's Go BOYS & GIRLS",)),
    ("Shirai Takako &CRAZY BOYS", ("Shirai Takako &CRAZY BOYS",)),
    ("hitomi & Yukiji", ("hitomi & Yukiji",)),
    ("TOSS & TURN", ("TOSS & TURN",)),
    ("Chage & Aska", ("Chage & Aska",)),
    ("Earth, Wind & Fire", ("Earth, Wind & Fire",)),
    ("Oranges & Lemons", ("Oranges & Lemons",)),
    ("Rough & Ready", ("Rough & Ready",)),
    ("LOREN&MASH", ("LOREN&MASH",)),
    ("Jack & Betty", ("Jack & Betty",)),
    ("Aya & Chika", ("Aya & Chika",)),
    ("Sachi & Juri", ("Sachi & Juri",)),
    ("Tackey & Tsubasa", ("Tackey & Tsubasa",)),
    ("AKIMA & NEOS", ("AKIMA & NEOS",)),
    ("Okino, Shuntaro", ("Okino, Shuntaro",)),
    ("HoneyWorks meets Sphere", ("HoneyWorks", "Sphere",),),
    ("HoneyWorks meets CHiCO & sana", ("HoneyWorks", "CHiCO", "sana"),),
    ("HoneyWorks meets TrySail", ("HoneyWorks", "TrySail",),),
    ("HoneyWorks meets Mafumafu", ("HoneyWorks", "Mafumafu",),),
    ("HoneyWorks meets Amatsuki", ("HoneyWorks", "Amatsuki",),),
    ("Akebonoyama Chuugaku Band with T", ("Akebonoyama Chuugaku Band with T",)),
    ("Duel Hero Yuu & Atsuto", ("Duel Hero Yuu & Atsuto",)),
    ("Duel Hero Yuu & Atsuto", ("Duel Hero Yuu & Atsuto",)),
    ("Amane + Beat Mario (COOL&CREATE)", ("Amane", "Beat Mario (COOL&CREATE)",),),
    (
        "Naruyoshi Kikuchi y Pepe Tormento Azcarar feat. Ichiko Hashimoto",
        ("Naruyoshi Kikuchi", "Pepe Tormento Azcarar", "Ichiko Hashimoto",),
    ),
    ("GENERATIONS from EXILE TRIBE", ("GENERATIONS", "EXILE TRIBE",),),
    ("THE RAMPAGE from EXILE TRIBE", ("THE RAMPAGE", "EXILE TRIBE",),),
    ("FANTASTICS from EXILE TRIBE", ("FANTASTICS", "EXILE TRIBE",),),
    (
        "Sandaime J SOUL BROTHERS from EXILE TRIBE",
        ("Sandaime J SOUL BROTHERS", "EXILE TRIBE",),
    ),
    ("Sukima Switch produced by Tamio Okuda", ("Sukima Switch", "Tamio Okuda",),),
    (
        "Yui Makino Hikiiru Uchuu Shoujo Vanaren-tai",
        ("Yui Makino", "Uchuu Shoujo Vanaren-tai",),
    ),
    (
        "Momoko Saitou Hikiiru Uchuu Shoujo Vanaren-tai",
        ("Momoko Saitou", "Uchuu Shoujo Vanaren-tai",),
    ),
    (
        "Uchuu Shoujo Vanaren-tai wants Aya Hirano",
        ("Uchuu Shoujo Vanaren-tai", "Aya Hirano",),
    ),
    ("Run Girls, Run!", ("Run Girls, Run!",)),
    ("Wake Up, Girls!", ("Wake Up, Girls!",)),
    ("Wake Up, May'n!", ("Wake Up, May'n!",)),
    (
        "Waka・Fuuri・Sunao・Risuko from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao from STAR☆ANIS",
        ("Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS", "Sunao from STAR☆ANIS",),
    ),
    (
        "Waka・Fuuri・Sunao・Remi・Moe・Eri・Yuna・Risuko from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    ("Waka・Remi from STAR☆ANIS", ("Waka from STAR☆ANIS", "Remi from STAR☆ANIS",),),
    (
        "Waka・Fuuri・Sunao・Remi・Moe from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao・Remi・Moe・Eri・Risuko from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    ("Waka・Moe from STAR☆ANIS", ("Waka from STAR☆ANIS", "Moe from STAR☆ANIS",),),
    ("Waka from STAR☆ANIS", ("Waka from STAR☆ANIS",)),
    ("Remi from STAR☆ANIS", ("Remi from STAR☆ANIS",)),
    ("Risuko from STAR☆ANIS", ("Risuko from STAR☆ANIS",)),
    ("Risuko・Waka from STAR☆ANIS", ("Risuko from STAR☆ANIS", "Waka from STAR☆ANIS",),),
    ("Eri from STAR☆ANIS", ("Eri from STAR☆ANIS",)),
    ("Fuuri from STAR☆ANIS", ("Fuuri from STAR☆ANIS",)),
    (
        "Risuko・Moe・Yuna from STAR☆ANIS",
        ("Risuko from STAR☆ANIS", "Moe from STAR☆ANIS", "Yuna from STAR☆ANIS",),
    ),
    (
        "Sunao・Risuko from STAR☆ANIS",
        ("Sunao from STAR☆ANIS", "Risuko from STAR☆ANIS",),
    ),
    (
        "Sunao・Waka・Fuuri from STAR☆ANIS",
        ("Sunao from STAR☆ANIS", "Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS",),
    ),
    ("Waka・Fuuri from STAR☆ANIS", ("Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS",),),
    ("Sunao from STAR☆ANIS", ("Sunao from STAR☆ANIS",)),
    ("Waka・Risuko from STAR☆ANIS", ("Waka from STAR☆ANIS", "Risuko from STAR☆ANIS",),),
    (
        "Sunao・Yuniko from STAR☆ANIS",
        ("Sunao from STAR☆ANIS", "Yuniko from STAR☆ANIS",),
    ),
    (
        "Waka・Fuuri・Sunao・Remi・Moe・Eri from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
            "Eri from STAR☆ANIS",
        ),
    ),
    ("Sayuri meets Desen Risotto", ("Sayuri", "Desen Risotto",),),
    ("Moe from STAR☆ANIS", ("Moe from STAR☆ANIS",)),
    (
        "Waka・Fuuri・Sunao・Yuna from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
        ),
    ),
    (
        "Risuko・Sunao・Yuna from STAR☆ANIS",
        ("Risuko from STAR☆ANIS", "Sunao from STAR☆ANIS", "Yuna from STAR☆ANIS",),
    ),
    ("Waka・Sunao from STAR☆ANIS", ("Waka from STAR☆ANIS", "Sunao from STAR☆ANIS",),),
    (
        "Waka・Fuuri・Yuna from STAR☆ANIS",
        ("Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS", "Yuna from STAR☆ANIS",),
    ),
    (
        "Risuko・Waka・Fuuri・Mona from STAR☆ANIS",
        (
            "Risuko from STAR☆ANIS",
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Mona from STAR☆ANIS",
        ),
    ),
    ("Eri・Waka from STAR☆ANIS", ("Eri from STAR☆ANIS", "Waka from STAR☆ANIS",),),
    ("Yuna from STAR☆ANIS", ("Yuna from STAR☆ANIS",)),
    ("Risuko・Mona from STAR☆ANIS", ("Risuko from STAR☆ANIS", "Mona from STAR☆ANIS",),),
    (
        "Fuuri・Yuna・Sunao・Eri from STAR☆ANIS",
        (
            "Fuuri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Eri from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao・Remi from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
        ),
    ),
    ("Ruka from STAR☆ANIS", ("Ruka from STAR☆ANIS",)),
    ("Waka・Ruka from STAR☆ANIS", ("Waka from STAR☆ANIS", "Ruka from STAR☆ANIS",),),
    ("Mona from STAR☆ANIS", ("Mona from STAR☆ANIS",)),
    (
        "Waka・Fuuri・Yuna・Ruka from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Ruka from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Remi・Risuko・Mona・Fuuri・Eri from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
            "Mona from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Eri from STAR☆ANIS",
        ),
    ),
    ("Fuuri・Waka from STAR☆ANIS", ("Fuuri from STAR☆ANIS", "Waka from STAR☆ANIS",),),
    ("Yuna・Remi from STAR☆ANIS", ("Yuna from STAR☆ANIS", "Remi from STAR☆ANIS",),),
    ("Remi・Eri from STAR☆ANIS", ("Remi from STAR☆ANIS", "Eri from STAR☆ANIS",),),
    (
        "Waka・Fuuri・Remi・Eri・Ruka from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Ruka from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Risuko・Ruka from STAR☆ANIS",
        ("Waka from STAR☆ANIS", "Risuko from STAR☆ANIS", "Ruka from STAR☆ANIS",),
    ),
    (
        "Yuna・Remi・Eri from STAR☆ANIS",
        ("Yuna from STAR☆ANIS", "Remi from STAR☆ANIS", "Eri from STAR☆ANIS",),
    ),
    ("Eri・Remi from STAR☆ANIS", ("Eri from STAR☆ANIS", "Remi from STAR☆ANIS",),),
    (
        "Ruka・Mona・Miki from AIKATSU☆STARS!",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
        ),
    ),
    ("Ruka from AIKATSU☆STARS!", ("Ruka from AIKATSU☆STARS!",)),
    (
        "Miho・Miki from AIKATSU☆STARS!",
        ("Miho from AIKATSU☆STARS!", "Miki from AIKATSU☆STARS!",),
    ),
    (
        "Miho・Nanase・Kana from AIKATSU☆STARS!",
        (
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    ("Mona from AIKATSU☆STARS!", ("Mona from AIKATSU☆STARS!",)),
    ("Kana from AIKATSU☆STARS!", ("Kana from AIKATSU☆STARS!",)),
    (
        "Kana・Ruka from AIKATSU☆STARS!",
        ("Kana from AIKATSU☆STARS!", "Ruka from AIKATSU☆STARS!",),
    ),
    (
        "Miki・Ruka・Mona from AIKATSU☆STARS!",
        (
            "Miki from AIKATSU☆STARS!",
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
        ),
    ),
    (
        "Ruka・Mona from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Mona from AIKATSU☆STARS!",),
    ),
    (
        "Ruka・Miki from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Miki from AIKATSU☆STARS!",),
    ),
    ("Miho from AIKATSU☆STARS!", ("Miho from AIKATSU☆STARS!",)),
    (
        "Mona・Ruka from AIKATSU☆STARS!",
        ("Mona from AIKATSU☆STARS!", "Ruka from AIKATSU☆STARS!",),
    ),
    ("Nanase from AIKATSU☆STARS!", ("Nanase from AIKATSU☆STARS!",)),
    (
        "Miki・Miho from AIKATSU☆STARS!",
        ("Miki from AIKATSU☆STARS!", "Miho from AIKATSU☆STARS!",),
    ),
    ("Miki from AIKATSU☆STARS!", ("Miki from AIKATSU☆STARS!",)),
    (
        "Mona・Nanase from AIKATSU☆STARS!",
        ("Mona from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!",),
    ),
    (
        "Ruka・Mona・Miki・Miho・Nanase・Kana from AIKATSU☆STARS!",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Nanase・Kana from AIKATSU☆STARS!",
        ("Nanase from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!",),
    ),
    (
        "Ruka・Nanase from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!",),
    ),
    (
        "Ruka・Kana from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!",),
    ),
    (
        "Miho・Nanase from AIKATSU☆STARS!",
        ("Miho from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!",),
    ),
    (
        "Sena・Rie from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Rie from AIKATSU☆STARS!",),
    ),
    (
        "Sena・Rie・Miki・Kana from AIKATSU☆STARS!",
        (
            "Sena from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    ("SUN&LUNAR", ("SUN&LUNAR",)),
    (
        "Ruka・Nanase・Kana・Miho from AIKATSU☆STARS!",
        (
            "Ruka from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
        ),
    ),
    (
        "Ruka・Sena from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Sena from AIKATSU☆STARS!",),
    ),
    ("Risa/Miho from AIKATSU☆STARS!", ("Risa Aizawa", "Miho from AIKATSU☆STARS!",),),
    (
        "Sena・Ruka from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Ruka from AIKATSU☆STARS!",),
    ),
    ("Ayahi Takagaki meets Sphere", ("Ayahi Takagaki", "Sphere",)),
    ("Rie from AIKATSU☆STARS!", ("Rie from AIKATSU☆STARS!",)),
    ("Sena from AIKATSU☆STARS!", ("Sena from AIKATSU☆STARS!",)),
    (
        "Ruka・Miho from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Miho from AIKATSU☆STARS!",),
    ),
    (
        "Sena・Miki・Kana from AIKATSU☆STARS!",
        (
            "Sena from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Risa/Miho・Rie・Ruka from AIKATSU☆STARS!",
        (
            "Risa Aizawa",
            "Miho from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Ruka from AIKATSU☆STARS!",
        ),
    ),
    (
        "Sena・Rie・Miki・Kana・Nanase from AIKATSU☆STARS!",
        (
            "Sena from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
        ),
    ),
    (
        "Rie・Kana from AIKATSU☆STARS!",
        ("Rie from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!",),
    ),
    (
        "Miho・Kana from AIKATSU☆STARS!",
        ("Miho from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!",),
    ),
    (
        "Nanase・Miho・Kana from AIKATSU☆STARS!",
        (
            "Nanase from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Kana・Sena・Miki from AIKATSU☆STARS!",
        (
            "Kana from AIKATSU☆STARS!",
            "Sena from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
        ),
    ),
    ("Kuni Kawachi and Takako Ishiguro", ("Kuni Kawachi", "Takako Ishiguro",)),
    (
        "Kana・Nanase from AIKATSU☆STARS!",
        ("Kana from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!",),
    ),
    (
        "Nanase・Rie from AIKATSU☆STARS!",
        ("Nanase from AIKATSU☆STARS!", "Rie from AIKATSU☆STARS!",),
    ),
    (
        "Miki・Nanase from AIKATSU☆STARS!",
        ("Miki from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!",),
    ),
    (
        "Sena・Miki from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Miki from AIKATSU☆STARS!",),
    ),
    (
        "Sena・Nanase from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!",),
    ),
    (
        "Rie・Nanase from AIKATSU☆STARS!",
        ("Rie from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!",),
    ),
    (
        "Aine・Mio from BEST FRIENDS!",
        ("Aine from BEST FRIENDS!", "Mio from BEST FRIENDS!",),
    ),
    (
        "Karen・Mirai from BEST FRIENDS!",
        ("Karen from BEST FRIENDS!", "Mirai from BEST FRIENDS!",),
    ),
    ("Mio from BEST FRIENDS!", ("Mio from BEST FRIENDS!",)),
    ("Aine from BEST FRIENDS!", ("Aine from BEST FRIENDS!",)),
    ("Mirai from BEST FRIENDS!", ("Mirai from BEST FRIENDS!",)),
    ("Maika from BEST FRIENDS!", ("Maika from BEST FRIENDS!",)),
    ("Karen from BEST FRIENDS!", ("Karen from BEST FRIENDS!",)),
    (
        "Maika・Ema from BEST FRIENDS!",
        ("Maika from BEST FRIENDS!", "Ema from BEST FRIENDS!",),
    ),
    ("Sakuya from BEST FRIENDS!", ("Sakuya from BEST FRIENDS!",)),
    ("Ema from BEST FRIENDS!", ("Ema from BEST FRIENDS!",)),
    (
        "Sakuya・Kaguya from BEST FRIENDS!",
        ("Sakuya from BEST FRIENDS!", "Kaguya from BEST FRIENDS!",),
    ),
    (
        "Aine・Mirai from BEST FRIENDS!",
        ("Aine from BEST FRIENDS!", "Mirai from BEST FRIENDS!",),
    ),
    ("Kaguya from BEST FRIENDS!", ("Kaguya from BEST FRIENDS!",)),
    (
        "Aine・Mio・Maika・Ema from BEST FRIENDS!",
        (
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Maika from BEST FRIENDS!",
            "Ema from BEST FRIENDS!",
        ),
    ),
    (
        "Aine・Mio・Ema・Maika from BEST FRIENDS!",
        (
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Ema from BEST FRIENDS!",
            "Maika from BEST FRIENDS!",
        ),
    ),
    ("Hibiki from BEST FRIENDS!", ("Hibiki from BEST FRIENDS!",)),
    (
        "Mio・Wakaba from BEST FRIENDS!",
        ("Mio from BEST FRIENDS!", "Wakaba from BEST FRIENDS!",),
    ),
    ("Wakaba from BEST FRIENDS!", ("Wakaba from BEST FRIENDS!",)),
    (
        "Hibiki・Alicia from BEST FRIENDS!",
        ("Hibiki from BEST FRIENDS!", "Alicia from BEST FRIENDS!",),
    ),
    ("Ondo\u2606Girl meets Keroro Shoutai", ("Ondo\u2606Girl", "Keroro Shoutai",)),
    ("Nicole Price and Bynne Price", ("Nicole Price", "Bynne Price",)),
    (
        "Raki・Aine・Mio from BEST FRIENDS!",
        (
            "Raki from BEST FRIENDS!",
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
        ),
    ),
    (
        "Raki・Aine・Mio from BEST FRIENDS!/Waka・Ruka・Sena",
        (
            "Raki from BEST FRIENDS!",
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Waka from STAR☆ANIS",
            "Ruka from AIKATSU☆STARS!",
            "Sena from AIKATSU☆STARS!",
        ),
    ),
    (
        "Raki from BEST FRIENDS!",
        ("Raki from BEST FRIENDS!", "Sena from AIKATSU☆STARS",),
    ),
    ("Mio from BEST FRIENDS!/Sena", ("Mio from BEST FRIENDS!",)),
    (
        "Mirai from BEST FRIENDS!/Ruka",
        ("Mirai from BEST FRIENDS!", "Ruka from AIKATSU☆STARS!",),
    ),
    (
        "Raki from BEST FRIENDS!/Waka",
        ("Raki from BEST FRIENDS!", "Waka from STAR☆ANIS",),
    ),
    (
        "Hibiki from BEST FRIENDS!/Risuko/Risa",
        ("Hibiki from BEST FRIENDS!", "Risuko from STAR☆ANIS", "Risa Aizawa"),
    ),
    (
        "Sunao/Sena・Rie・Miki・Kana・Nanase/Aine・Mio・Maika・Ema from BEST FRIENDS!",
        (
            "Sunao from STAR☆ANIS",
            "Sena from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS",
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Maika from BEST FRIENDS!",
            "Ema from BEST FRIENDS!",
        ),
    ),
    (
        "Aine・Mio from BEST FRIENDS!/Sena",
        (
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Sena from AIKATSU☆STARS!",
        ),
    ),
    ("Alicia from BEST FRIENDS!", ("Alicia from BEST FRIENDS!",)),
    (
        "Aine・Mio from BEST FRIENDS!/Waka",
        ("Aine from BEST FRIENDS!", "Mio from BEST FRIENDS!", "Waka from STAR☆ANIS",),
    ),
    (
        "Ayane・Ruka・Rie/Karen from BEST FRIENDS!",
        (
            "Ayane Fujisaki",
            "Ruka from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Karen from BEST FRIENDS!",
        ),
    ),
    (
        "Mao・Ruli from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Ruli from STARRY PLANET☆",),
    ),
    (
        "Mao・Ayumi from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Ayumi from STARRY PLANET☆",),
    ),
    (
        "Mao・Kyouko from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Kyouko from STARRY PLANET☆",),
    ),
    (
        "Mao・Ruli・Kyouko・Shiori from STARRY PLANET☆",
        (
            "Mao from STARRY PLANET☆",
            "Ruli from STARRY PLANET☆",
            "Kyouko from STARRY PLANET☆",
            "Shiori from STARRY PLANET☆",
        ),
    ),
    ("Ayumi from STARRY PLANET☆", ("Ayumi from STARRY PLANET☆",)),
    (
        "Ayumi・Ruli from STARRY PLANET☆",
        ("Ayumi from STARRY PLANET☆", "Ruli from STARRY PLANET☆",),
    ),
    ("Meisa from STARRY PLANET☆", ("Meisa from STARRY PLANET☆",)),
    (
        "Shiori・Ruli from STARRY PLANET☆",
        ("Shiori from STARRY PLANET☆", "Ruli from STARRY PLANET☆",),
    ),
    ("Miyuki Ichijō and the Howmei Girls", ("Miyuki Ichijō", "the Howmei Girls",)),
    (
        "Dominic Nolfi, Heidi Weyhmueller and the Cast of Pokémon Live",
        ("Dominic Nolfi", "Heidi Weyhmueller", "the Cast of Pokémon Live",),
    ),
    ("Jeffrey Pescetto and the Jets", ("Jeffrey Pescetto", "the Jets",)),
    ("Tadashi Suzuki and CA Pops", ("Tadashi Suzuki", "CA Pops",)),
    ("Yōko Kuri and The Viking", ("Yōko Kuri", "The Viking",)),
    ("Jeremy Sweet and Ian Nickus", ("Jeremy Sweet", "Ian Nickus",)),
    ("Élan Rivera and PJ Lequerica", ("Élan Rivera", "PJ Lequerica",)),
    (
        "Aida Bunzou and Tokyo Shounen Shoujo Gasshoutai",
        ("Aida Bunzou", "Tokyo Shounen Shoujo Gasshoutai",),
    ),
    ("Mints and Rei Sekimori", ("Mints", "Rei Sekimori",)),
    ("Yoko Nakamura and Young Fresh", ("Yoko Nakamura", "Young Fresh",)),
    ("Yoshimi Nakajima and Young Fresh", ("Yoshimi Nakajima", "Young Fresh",)),
    (
        "Makiko Morita, Shiho Mannaka and Young Fresh",
        ("Makiko Morita", "Shiho Mannaka", "Young Fresh",),
    ),
    ("Masato Hidaka and Okama Club", ("Masato Hidaka", "Okama Club",)),
    ("Erin Bowman and Joe Philips", ("Erin Bowman", "Joe Philips",)),
    ("Alex Nackman and Kathryn Raio", ("Alex Nackman", "Kathryn Raio",)),
    ("Neal Coomer and Kathryn Raio", ("Neal Coomer", "Kathryn Raio",)),
    ("Ben Dixon and The Sad Truth", ("Ben Dixon", "The Sad Truth",)),
    (
        "Misaki Komatsu feat. Decktonic and Anthony Seeha",
        ("Misaki Komatsu", "Decktonic", "Anthony Seeha"),
    ),
    ("Jannel Candrice and The Sad Truth", ("Jannel Candrice", "The Sad Truth",)),
    ("Skrillex and Nik Roos", ("Skrillex", "Nik Roos",)),
    ("Elspeth Bawden and Amelia Jones", ("Elspeth Bawden", "Amelia Jones",)),
    (
        "DJ Milky and b-nCHANt-d featuring Rachel Pollack",
        ("DJ Milky", "b-nCHANt-d", "Rachel Pollack",),
    ),
    (
        "Mao・Shiori from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Shiori from STARRY PLANET☆",),
    ),
    (
        "Shiori・Ann from STARRY PLANET☆",
        ("Shiori from STARRY PLANET☆", "Ann from STARRY PLANET☆",),
    ),
    (
        "Mao・Ann from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Ann from STARRY PLANET☆",),
    ),
    (
        "Kyouko・Ayumi from STARRY PLANET☆",
        ("Kyouko from STARRY PLANET☆", "Ayumi from STARRY PLANET☆",),
    ),
    (
        "Ruli・Meisa from STARRY PLANET☆",
        ("Ruli from STARRY PLANET☆", "Meisa from STARRY PLANET☆",),
    ),
    (
        "Mao・Meisa from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Meisa from STARRY PLANET☆",),
    ),
    (
        "Ann・Sala from STARRY PLANET☆",
        ("Ann from STARRY PLANET☆", "Sala from STARRY PLANET☆",),
    ),
    (
        "Shiori・Sala from STARRY PLANET☆",
        ("Shiori from STARRY PLANET☆", "Sala from STARRY PLANET☆",),
    ),
    (
        "Ruli・Kyouko from STARRY PLANET☆",
        ("Ruli from STARRY PLANET☆", "Kyouko from STARRY PLANET☆",),
    ),
    (
        "Ayumi・Meisa from STARRY PLANET☆",
        ("Ayumi from STARRY PLANET☆", "Meisa from STARRY PLANET☆",),
    ),
    (
        "Ruka・Mona・Miki from AIKATSU☆STARS! & Waka from STAR☆ANIS",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Waka from STAR☆ANIS",
        ),
    ),
    (
        "Eri from STAR☆ANIS & Miho from AIKATSU☆STARS!",
        ("Eri from STAR☆ANIS", "Miho from AIKATSU☆STARS!",),
    ),
    (
        "Ruka・Mona・Miki・Miho from AIKATSU☆STARS! & Waka・Risuko from STAR☆ANIS",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Waka from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao from STAR☆ANIS & Ruka・Mona・Miki from AIKATSU☆STARS!",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
        ),
    ),
    (
        "Ruka・Mona・Miki・Miho・Nanase・Kana from AIKATSU☆STARS! & Waka from STAR☆ANIS",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Waka from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Yuna・Remi・Eri・Risuko・Mona・Ruka from STAR☆ANIS & Mona・Miki・Miho・Nanase・Kana from AIKATSU☆STARS!",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
            "Mona from STAR☆ANIS",
            "Ruka from STAR☆ANIS",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Waka・Fuuri・Sunao from STAR☆ANIS & Ruka・Mona・Miki from AIKATSU☆STARS!",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
        ),
    ),
    ("Waka・Eimi", ("Waka Kirishima", "Eimi Naruse",),),
    ("Risa・Eimi", ("Risa Aizawa", "Eimi Naruse")),
    ("Ayane・Eri", ("Ayane Fujisaki", "Eri Aino",),),
    ("You & Explosion Band", ("You & Explosion Band",)),
    (
        "You & Explosion Band feat. Lyn Inaizumi",
        ("You & Explosion Band", "Lyn Inaizumi",),
    ),
    ("You & Explosion Band featuring Lileth", ("You & Explosion Band", "Lileth",),),
    ("Akiko & Naoko Kobayashi", ("Akiko Kobayashi", "Naoko Kobayashi",)),
    ("(K)NoW_NAME:Ayaka Tachibana", ("(K)NoW_NAME", "Ayaka Tachibana",)),
    ("(K)NoW_NAME:Ayaka Tchibana", ("(K)NoW_NAME", "Ayaka Tchibana",)),
    ("(K)NoW_NAME:NIKIIE", ("(K)NoW_NAME", "NIKIIE",)),
    ("(K)NoW_NAME:AIJ", ("(K)NoW_NAME", "AIJ",)),
    ("(K)NoW_NAME:eNu", ("(K)NoW_NAME", "eNu",)),
    ("Kevin Penkin [feat. Emi Evans]", ("Kevin Penkin", "Emi Evans",)),
]
# 0000

splitting_exception = {}
for split_exception in splitting_exception_list:
    splitting_exception[split_exception[0]] = split_exception[1]
# Splitting Config

# Alternative Artists names
alternative_names = [
    # because database inconsistency
    ["Unshou Ishizuka", "Unshō Ishizuka", "Unsho Ishizuka"],
    ["Junjō no Afilia", "Junjou no Afilia", "Afilia Saga East", "Afilia Saga"],
    ["Yōko Hikasa", "Yoko Hikasa"],
    ["PSY･S", "PSY・S"],
    ["Nagi Yanagi", "nagi"],
    # ["Yuu Serizawa", "Yuu Serizawa"],
    ["Columbia Yurikago-kai", "Columbia Yurikago Kai", "Columubia Yurikago-kai"],
    ["Youki Kudoh", "Yuuki Kudo"],
    ["Yoko Kanno", "Gabriela Robin", "gabriela robin"],
    ["Steve Conte", "steve conte"],
    [
        "Tokyo Konsei Gasshou-dan",
        "Tokyo Konsei Gasshō-dan",
        "Shigeru Yamada (Tokyo Konsei Gasshou-dan)",
    ],
    ["Etsuko Kozakura", "Etsuko Kozukura"],
    [
        "Ichiro Mizuki",
        "Ichirou Mizuki",
        "Ichirō Mizuki",
        "Ichrio Mizuki",
        "Ichiro",
        "Mizuking",
    ],
    ["Masako Iwanaga", "Masako Iwanga"],
    ["Aki Kudo", "Aki Kudou"],
    ["Ami Ozaki", "Amii Ozaki"],
    ["Ryōtarō Okiayu", "Ryotaro Okiayu"],
    ["Chisa Yokoyama", "Chisa Yokohama"],
    ["Koh Ikeda", "Kou Ikeda"],
    ["Yuko Mizutani", "Yuuko Mizutani"],
    ["Shirō Sagisu", "Shiro Sagisu"],
    ["millio", "Millio"],
    ["Ayako Kawasumi", "Ayako Kawasumii"],
    ["Shinichirou Miki", "Shinichiro Miki"],
    ["Yuuko Kawai", "Yuko Kawai"],
    ["Sakurakko Club Sakura-gumi"],
    ["Maximum The Hormone", "Maximum the Hormone", "MAXIMUM THE HORMONE"],
    ["T's WORKSHOP", "T's WORK SHOP"],
    ["Koji Tsujitani", "Kouji Tsujitani"],
    ["Shoko Minami", "Shōko Minami"],
    ["Tarantula", "Tarantula (From Hi-Timez)"],
    ["Nakayoshi Mantan! Valac Ikka", "Valac Ikka"],
    ["Motohiro Hata", "Motohiro Hata meets Sakamichi no Apollon"],
    [
        "Suginami Jidou Gasshou-dan",
        "Suginami Jidō Gasshō-dan",
        "Suginami Jidou Gassho-dan",
    ],
    ["Maaya Sakamoto", "maaya sakamoto"],
    ["Yumi Touma", "Yumi Tōma"],
    ["Satomi Koorogi", "Satomi Kōrogi"],
    ["WIZ-KISS", "WIZ•KISS"],
    [
        "Yuuki Ozaki",
        "Yuuki Ozaki(from Galileo Galilei)",
        "Yuuki Ozaki (from Galileo Galilei)",
    ],
    ["Miwaku Okuda", "Miwako Okuda"],
    ["hitomi", "Hitomi", "Hitomi Kuroishi"],
    ["Yui Horie", "Miss Monochrome"],
    ["Tomoko Tokugai", "Tomoko Tokugaki"],
    ["Spica", "Team Spica"],
    ["Kaori Asō", "Kaori Asou"],
    # ["Yuu Asakawa", "Yuu Asakawa"],
    ["Reiko Takagi", "Reiko Tagaki"],
    ["Yuka Sato", "Yuka Satou", "Yuka Satō"],
    ["Yukiyo Satō", "Yukiyo Satou"],
    ["Pink Piggies", "Pink Piggys"],
    ["Minako Obata", 'Minako"mooki"Obata', 'Minako "mooki" Obata'],
    ["Akemi Satō", "Akemi Satou"],
    ["Mie Sonozaki", "Mie Sonokazi"],
    ["Kumiko Endou", "Kumiko Endo"],
    ["Knight Sabers", "the Knight Sabers"],
    ["Maiko Hashimoto", "Maiko Hashimoto "],
    ["Yumi Tōma", "Yumi Touma"],
    ["Riu Konaka", "Riyu Konaka"],
    [
        "Mori no Kijidou Gasshou-dan",
        "Mori no Ki Jidou Gasshou-dan",
        "Mori no Ki Jidou Gasshoudan",
        "Mori no Ki Gasshō-dan",
        "Mori no Ki Jidō Gasshō-dan",
        "Mori no Ki Jidou Gasshō-dan",
    ],
    ["Mayumi Sudō", "Mayumi Sudou", "Mayumi Sudo"],
    ["Tōru Furuya", "Tooru Furuya", "Tohru Furuya"],
    ["G・GRIP", " G・GRIP"],
    ["SHINES", "SHINE'S"],
    ["Russell Velázquez", "Russell Velazquez"],
    ["Yuko Kobayashi", "Yuuko Kobayashi"],
    ["Shizuru Ootaka", "Shizuru Ōtaka"],
    ["Eri Kawai", "Eri Kawaii"],
    ["Haruka Mimura", "VJ Only"],
    ["Kosei Asami", "Kōsei Asami"],
    ["Kazue Ikura", "Kazu Ikura"],
    ["Shō Hayami", "Sho Hayami"],
    ["※-mai-", "※-mai"],
    ["Mica Okudoi", "Mika Okudoi"],
    ["Raj Ramayya", "raj ramayya"],
    ["Michiko Kawai"],
    ["Sumi Shimamoto", "Sumi Shinamoto"],
    ["Hillbilly Bops", "HillBilly Bops"],
    ["Toshiyuki Ohsawa", "Yoshiyuki Ohsawa"],
    ["Mai Fukuda", "Mei Fukuda"],
    ["ZA-ZA", "ZAZA"],
    ["DR.LOVE", "DR. LOVE"],
    ["Kumiko Ōsugi", "Kumiko Osugi"],
    ["Platinum Peppers Family", "Platinum Pepper Family"],
    ["Kenji Kawai", "Kenji Kawami"],
    ["Ritsuko Ohwada", "Ritsuko Ōwada"],
    [
        "Kamitakada Shōnen Gasshō-dan",
        "Kamikataka Shōnen Gasshō-dan",
        "Kamitakada Shounen Gasshou-dan",
        "Kamitakada Shounen Gasshō-dan",
    ],
    ["Gackt", "GACKT"],
    ["Luna Goami", "LUNA GOAMI"],
    ["Scha Dara Parr", "SCHA DARA PARR"],
    # ["Yuumao", "Yuumao"],
    ["Fushigi Hakken no Uta Club", "FHK Fushigi Hakken no Uta Club"],
    ["Choro-gonzu", "Super Chorogons"],
    ["Soraru", "soraru"],
    # ["Kayoko Ishuu", "Kayoko Ishuu"],
    ["Kayoko Ishuu", "Kayo Ishu"],
    # ["Yuuki Hide", "Yuuki Hide"],
    ["Rumania Montevideo", "rumania montevideo"],
    ["Mariko Kouda", "Mariko Kōda"],
    ["Junichirou Oda", "Junichirō Oda"],
    ["Rosenburg Engel", "Rosenburg Alptraum"],
    ["White Ryuu", "Hakuryuu"],
    ["Hideki Saijou", "Hideki Saijo"],
    ["FENCE OF DEFENSE", "FENCE OF DEFENCE"],
    ["Reiko Omori", "Reiko Oomori"],
    ["Sh\u014djo-tai", "1999 Shoujo-tai"],
    ["Sweet Velvet", "sweet velvet"],
    ["Derek Jackson", "Darek Jackson"],
    ["Shouko Yamagiwa", "Shōko Yamagiwa"],
    # ["Yuuko Miyamura", "Yuko Miyamura", "Yuuko Miyamura"],
    ["Yuuko Miyamura", "Yuko Miyamura"],
    ["Miki Ito", "Miki Itō", "Miki Itou"],
    ["Tesshou Genda", "Tesshō Genda", "Tessho Kenda"],
    ["Becky♪#", "Becky"],
    ["Watarirouka Hashiritai 7", "Watarirouka Hashiritai"],
    ["Dance Man", "Dance☆Man"],
    ["mihimaru GT", "mihimaruGT"],
    # ["Yuu Takahashi", "Yuu Takahashi"],
    ["Yōko Nagayama", "Yoko Nagayama"],
    ["Koorogi '73", "Kōrogi '73"],
    ["Takeshi Ike", "Takashi Ike"],
    ["Shizuka Kudou", "Shizuka Kudō"],
    ["Yusuke Nakamura", "Yuusuke Nakamura"],
    ["Yuji Mitsuya", "Yuuji Mitsuya"],
    ["TSUNAMI", "TSUNAMi"],
    ["Chinami Nishimura", "Nishimura Chinami"],
    # ["Yuki Masuda", "Yuuki Masuda", "Yuuki Masuda"],
    ["Yuki Masuda", "Yuuki Masuda"],
    ["Yuukō Kusunoki", "Yukoh Kusunoki"],
    ["Kentar\u014d It\u014d", "Kentarou Itou"],
    ["Moyu Arishima", "Moyu Arashima"],
    ["Howmei Girls", "the Howmei Girls"],
    ["Miwako Saitou", "Miwako Saitō", "Miwako Saito"],
    ["Kōichi Yamadera", "Kouichi Yamadera", "Koichi Yamadera", "Kōchi Yamadera"],
    ["Shoko Suzuki", "Shōko Suzuki"],
    ["Sayuri Saitou", "Sayuri Saito"],
    ["Kyoko Hikami", "Kyōko Hikami", "Kyouko Hikami"],
    ["Mayumi Shou", "Mayumi Shō"],
    ["The Street Sliders", "Street Sliders"],
    ["7-nin no Mugiwara Kaizoku-dan", "Mugiwara Kaizoku-dan",],
    ["The ROOTLESS", "THE ROOTLESS"],
    ["Choo", "Cho", "Yuuichi Nagashima"],
    ["Kota Shinzato", "Kouta Shinzato"],
    ["Yōko Honna", "Yoko Honna", "Youko Honna"],
    ["Pull Tab to Can", "Pull Tab to Kan"],
    ["Kousuke Toriumi", "Kōsuke Toriumi"],
    ["Souichiro Hoshi", "Soichiro Hoshi", "Souichirou Hoshi"],
    ["Hitomi Tōyama", "Hitomi Toyama"],
    ["Yoko Ueno", "Youko Ueno"],
    ["Ayaka Saitou", "Ayaka Saito", "Ayaka Saitō"],
    ["Kouji Kikkawa", "Kōji Kikkawa"],
    ["FURIL", "FURIL'"],
    ["DAVE MC LOUD", "DAVE Mc LOUD"],
    ["Yuka Iwahashi", "Coco Panna"],
    ["MICKEY B.", "MICKEY B"],
    ["THE SPIDERS FROM MARS", "SPIDERS FROM MARS"],
    ["The Blessin' Four", "The Blessen Four"],
    ["Kyoko Koizumi", "Kyouko Koizumi"],
    ["Taeko Onuki", "Taeko Ohnuki"],
    ["Children's Chorus", "Children Chorus"],
    ["Peek-a-Boo", "Peek-A-Boo"],
    [
        "Hibari Jidou Gasshou-dan",
        "Hibari Jidō Gasshō-dan",
        "Hibari Jidou Gassho-dan",
        "Hibari Jidou Gasshoudan",
    ],
    ["Tokyo Arakawa Shounen Shoujo Gasshou-tai", "Arakawa Shounen Shoujo Gasshou-tai"],
    ["Tsunehiko Kamijou", "Tsunehiko Kamijo"],
    ["Takako Ohta", "Takako Oota", "Takako Ōta"],
    ["Meistersinger", "Tokyo Meistersinger"],
    ["Fumio Otsuka", "Fumio Ootsuka"],
    ["Nobuyo Oyama", "Nobuyo Ooyama"],
    ["Midori Kato", "Midori Katou"],
    ["Satomi Majima", "Satomi Mashima"],
    ["Kyoko Okada", "Kyouko Okada"],
    ["Salia", "SALIA"],
    ["Norman J. Grossfield", "Norman J. Grossfeld"],
    [
        "Nishirokugou Shōnen Gasshō-dan",
        "Nishirokugo Shōnen Gasshō-dan",
        "Nishirokugou Shounen Gasshougan",
    ],
    ["Koinu", "Riinu (Sutopuri)"],
    ["Kaguyahime", "Kaguya-hime"],
    ["Aurora Sannin Musume", "Aurora Gonin Musume"],
    ["Yougo Kouno", "Yogo Kono"],
    ["Youko Seri", "Yoko Seri"],
    ["Bonny Jacks", "Bonnie Jacks"],
    ["The Green Peas", "Green Peas"],
    ["Jōji Yanami", "Jouji Yanami"],
    # ["Yuusaku Yara", "Yuusaku Yara"],
    ["Kabuki Rocks", "Kabukibu Rocks"],
    ["Sayaka Ohara", "Sayaka Oohara"],
    ["Escargot", "Escargo"],
    ["Akio Ootsuka", "Akio Ohtsuka"],
    ["Ryouka Yuzuki", "Ryōka Yuzuki"],
    ["GagagaSP", "Gagaga SP"],
    ["Tarako", "TARAKO"],
    ["Yuko Tsuburaya", "Yuuko Tsuburaya"],
    ['Chris "Breeze" Barczynski', 'Chris "Breeze" Barczynsk'],
    ["Shabana", "Shabana "],
    ["Itai Toshi", "Itai Toshio"],
    ["Takurō Yoshida", "Takurou Yoshida"],
    ["Takurō Yoshida", "Takuro Yoshida"],
    ["Tokyo Shōnen Shōjo Gasshō-tai", "Tōkyō Shōnen Shōjo Gasshō-tai"],
    ["Kōhei Dōjima", "Kohei Dojima"],
    ["The Collectors", "the collectors", "THE COLLECTORS"],
    ["Ryoko Sano", "Ryōko Sano"],
    ["Gospellers", "The Gospellers"],
    ["Ryoko Shintani", "Ryōko Shintani"],
    ["Shining Stars", "Golden Stars"],
    ["Sadastic Mika Band", "Sadistic Mika Band"],
    ["Chikyuu Bouei-gumi Gasshou-tai", "Chikyuu Boueigumi Gasshotai"],
    ["Chikyuu Seifuku-bu"],
    ["Chikyuu Bōei-bu", "Chikyuu Bouei-bu"],
    ["MEGA NRG MAN", "NRG"],
    ["Coalamode.", "Coala mode."],
    ["Yuko Ishikawa", "Yuuko Ishikawa"],
    ["'Weird Al' Yankovic", '"WEIRD AL" YANKOVIC'],
    ["Kanako Itō", "Kanako Itou"],
    ["Akane Oomae", "Akane Omae"],
    ["Toshiyuki Omori", "Toshiyuki Oomori"],
    ["Bakufu Slump", "Bakufu-Slump"],
    ["Rin'", "Rin"],
    ["Ryou Horikawa", "Ryo Horikawa"],
    ["MR.M", "MR. M"],
    ["Tomoko Nakajima", "Toyoko Nakajima"],
    ["Ginzou Matsuo", "Ginzō Matsuo"],
    ["Yo Hitoto", "You Hitoto"],
    ["Kouji Yusa", "Kōji Yusa", "Koji Yusa"],
    # ["Yuu Mizushima", "Yuu Mizushima"],
    ["Eiichi Ōtaki", "Eiichi Ohtaki"],
    ["Kaoru Sasajima", "Kahoru Sasajima"],
    ["Yuu Nakamura", "Yu Nakamura"],
    ["Faylan", "faylan"],
    ["Ryō Hirohashi", "Ryou Hirohashi"],
    ["Chatmonchy", "chatmonchy"],
    ["ROOKiEZ is PUNK'D", "ROOKIEZ is PUNK'D"],
    ["Sunbrain", "sunbrain"],
    ["Shizuka Itou", "Shizuka Itō"],
    ["Yu Kobayashi", "Yuu Kobayashi", "Smith"],
    ["Aki Toyosaki", "Melori"],
    ["Current of Air", "COA"],
    ["Chiaki Osawa", "Chiaki Ōsawa"],
    ["ERIKA", "Erika Masaki"],
    ["Ryoko Shiraishi", "Ryōko Shiraishi"],
    ["Mahora Gakuen Chuutou-bu 2-A", "Mahora Gakuen Chuutoubu 2-A",],
    [
        "Mahora Gakuen Chuutou-bu 3-A",
        "Mahora Gakuen Chuutoubu 3-A",
        "Mahora Gakuen Chuutobu 3-A",
    ],
    ["Nemu Yumemi", "Nemu"],
    ["Tatsuhisa Suzuki", "Tatsuhisa Susuki"],
    ["Yuuko \u014cno", "Yuuko Oono"],
    ["Tomoe Oumi", "Tomoe Ohmi"],
    ["Momoko Saitō", "Momoko Saito", "Momoko Saitou"],
    ["Yuko Goto", "Yuuko Gotou"],
    ["Rina Satou", "Rina Satō"],
    ["Machico Kawana", "Machiko Kawana"],
    ["Chiwa Saito", "Chiwa Saitō"],
    ["Aya Endo", "Aya Endou", "Aya Endō"],
    ["Tamurapan", "Taurapan"],
    ["skankfunk", "shankfunk"],
    ["Rune Angel-tai", "Runrun Angel-tai"],
    ["Nomico", "nomico"],
    ["Momoko Saito", "Momoko Saitou"],
    ["Yuuna Inamura", "Yuna Inamura"],
    ["Izumi Katou", "Izumi Katō"],
    ["Nanae Katou", "Nanae Katō"],
    ["Kyōko Kishi", "Kyouko Kishi"],
    ["Kristen Price", "Kirsten Price"],
    ["Takashi Kondou", "Takashi Kondō"],
    ["Aimee Blackschleger", "Aimee B", "Aimee B."],
    ["STEEL ANGELS", "Angels"],
    ["Yurika Ooyama", "Yurika Ōyama"],
    ["The 5 TEARDROPS", "The5 TEARDROPS"],
    ["Addie Blaustein", "Maddie Blaustein"],
    ["Tortoise Matsumoto", "Tortoise Matsumoto (Ulfuls)"],
    # ["Naoto Fuuga", "Naoto Fuuga"],
    ["Yasutaka Nakata", "Yasutaka Nakata (CAPSULE)"],
    ["Aya Endou", "Aya Endō"],
    ["Aya Gōda", "Aya Gouda"],
    ["Dainiki LemonAngel", "Dai-II-Ki Lemon Angel", "Niki LemonAngel"],
    ["First Lemon Angels", "Ikki LemonAngel"],
    [
        "Anna Tsuchiya",
        "ANNA inspi' NANA(BLACK STONES)",
        "ANNA TSUCHIYA inspi' NANA(BLACK STONES)",
    ],
    ["Milky Way", "MilkyWay"],
    ["ko-saku", "Ko-saku"],
    ["Hyoutei Eternity", "Hyotei Eternity", "Hyōtei Eternity"],
    ["Kanae Itō", "Kanae Ito", "Kanae Itou"],
    ["Natsuko Aso", "Nyatsuko Asou"],
    ["May'n", "May'n!"],
    ["Fudanjuku", "Fuudanjuku"],
    ["Teriyuki Tsuchida", "Teruyuki Tsuchida"],
    ["pigstar", "Pigstar"],
    ["Shuuhei Kita", "Shuhei Kita"],
    ["Mai Gotō", "Mai Goto"],
    # ["Yuuko Sanpei", "Yuuko Sanpei"],
    ["Yuuki Kanno", "Yuki Kanno"],
    # ["Yuuichi Nakamura", "Yuuichi Nakamura", "Yuichi Nakamura"],
    ["Yuuichi Nakamura", "Yuichi Nakamura"],
    ["Satoru Kousaki", "Satoru Kosaki", "Satoru Kosaki (MONACA)"],
    ["PNGN 6", "PNGN 4", "PNGN 3"],
    ["Ame no Kisaki Shōjo Gasshō-dan", "Amanokisaki Shōjo Gasshō-dan"],
    ["Asuka Oogame", "Asuka Ōgame"],
    ["moumoon", "Moumoon"],
    ["School Food Punishment", "school food punishment"],
    ["Ho-Kago Tea Time - HTT", "Ho-Kago Tea Time"],
    ["Hekiyou Gakuen Seitokai", "Hekiyō Gakuen Seitokai", "Heikyō Gakuen Seitokai",],
    ["MM Gakuen Gasshou-bu", "MM Gakuen Gasshobu"],
    ["Yuki Kaji", "Yuuki Kaji"],
    ["Yuki Kajiura", "Fion"],
    ["Becky", "Becky♪#"],
    ["Yuuya Matsushita", "Yuya Matsushita"],
    ["Brenda Vaughn", "BRENDA VAUGHN"],
    # ["Yuu Sakai", "Yuu Sakai"],
    ["Yuuko Sanpei", "Yuuko Senpei"],
    ["Yuko Gibu", "Yuuko Gibu"],
    ["Atsushi Kōsaka", "Atsushi Kousaka"],
    ["Team.Nekokan [Neko]", "Team Nekokan [Neko]"],
    ["Karen GUY'S", "Karen GUY's"],
    ["Satomi Satou", "Satomi Sato"],
    ["Ayuru Ōhashi", "Ayuru Oohashi", "Ayuru Ohashi"],
    ["765PRO ALLSTARS", "765PRO ALL STARS", "765PRO"],
    ["Yuuko Kaida", "Yuko Kaida"],
    ["Mikako Komatsu", "Mikako komatsu"],
    ["kimaguren", "Kimaguren"],
    ["Nao Tōyama", "Nao Touyama"],
    ["Precure All-Stars 21", "Precure All Stars"],
    ["Micheal Brody", "Michael Brady"],
    ["FT ISLAND", "FTISLAND"],
    ["Hyadain", "Nyadain"],
    ["Kyuu Sakamoto", "Kyu Sakamoto"],
    ["Aiko Ōkubo", "Aiko Ookubo"],
    ["kasarinchu", "Kasarinchu"],
    ["singman", "Singman"],
    # ["Duel Hero Yuu & Atsuto", "Duel Hero Yuu & Atsuto"],
    ["Ryōhei Kimura", "Ryouhei Kimura"],
    ["Nothing's Carved In Stone", "Nothing's Carved in Stone"],
    ["Yuuki Wakai", "Yuki Wakai"],
    ["STYLE FIVE", "Iwatobi Machi no Yukai na Nakama-tachi"],
    ["Tomohisa Sakō", "Tomohisa Sako"],
    ["Yuuki Ono", "Yuki Ono", "Yuuki Ono"],
    ["Hoshi no Shōjo-tai", "Hoshi no Shoujo-tai☆"],
    ["Official HIGE DANdism", "Official HiGE DANdism"],
    ["Toru Ohkawa", "Tooru Ookawa"],
    ["Otome Shintō", "Otome Shinto"],
    ["Kenjiro Tsuda", "Kenjirou Tsuda"],
    ["Naomi Oozora", "Naomi Ōzora"],
    ["Shintarō Asanuma", "Shintaro Asanuma", "Shintarou Asanuma"],
    ["Yuki Hayashi", "Yuuki Hayashi"],
    ["Ryota Osaka", "Ryota Ohsaka"],
    ["Ayaka Ōhashi", "Ayaka Ohashi"],
    ["TAKUMI iwasky", "TAKUMI iwasaky"],
    ["KIRISAME UNDERTAKER", "Kirisame Undertaker"],
    ["Takuya Satō", "Takuya Satou"],
    ["Sae Aeuchi", "Sae Aiuchi"],
    ["Ayaka Senbongi", "Sayaka Senbongi"],
    ["Takayuki Hattori", "Takayuki Hattori Presents GUNDAM THE ORIGIN"],
    ["Flower", "FLOWER"],
    # ["Shuuta Morishima", "Shuuta Morishima"],
    ["Miho Arakawa", "Miho Arikawa"],
    ["smileY inc.", "SmileY inc."],
    ["Himika Akaneya", "Himeka Akaneya"],
    ["Dark Cherries", "Dark Cherry"],
    ["ZEN-LA ROCK", "ZEN-LA-ROCK"],
    ["Shintaro Asanuma", "Shintarou Asanuma"],
    ["Yuuto Suzuki", "Yuto Suzuki"],
    ["Yō Taichi", "You Taichi"],
    ["Azusa Satou", "Asuza Satou"],
    ["SPARK!! SOUND!! SHOW!!", "SPARK!!SOUND!!SHOW!!"],
    ["Yu Shimamura", "Yuu Shimamura"],
    ["Amina Satō", "Amina Satou"],
    ["Makoto Furukawa", "Makoto Furukara"],
    ["RINK (Mistera Feo)", "RINKU (Mistera Feo)"],
    ["Yuuka Nishio", "Rinku", "RINKU"],
    ["team Ōtori", "team Ootori"],
    ["team Hiiragi", "Team Hiiragi"],
    ["tofubeat", "tofubeats"],
    ["Merumo Hisaoka", "Meruo Hisaoka"],
    ["Osomatsu-san All Stars", "Osomatsu-san Allstars"],
    ["hitorie", "Hitorie"],
    ["Haruna Ōshima", "Haruna Oshima"],
    # ["Yuuma Uchida", "Yuuma Uchida"],
    ["Tommy heavenly\u2076", "Tommy february\u2076"],
    ["(K)NoW_NAME:Ayaka Tachibana", "(K)NoW_NAME:Ayaka Tchibana", "Ayaka Tachibana"],
    # ["Yuuki Takada", "Yuuki Takada"],
    ["Shuka Saito", "Shuka Saitou", "Shuka Saitō"],
    ["PriPara☆All Idol's", "Super PriPara☆All Idols"],
    ["AOZU", "Aozu"],
    ["Ryōko Maekawa", "Ryouko Maekawa"],
    # ["Yuuta Kasuya", "Yuuta Kasuya"],
    ["Souma Saito", "Souma Saitou", "Soma Saito"],
    ["Yuuichirō Umehara", "Yuuichirou Umehara"],
    ["BUD VIRGIN LOGIC", "BUDVIRGINLOGIC"],
    ["Shonan no Kaze", "Shōnan no Kaze"],
    ["Akira Ōse", "Akira Ouse"],
    ["Haruka Tojo", "Haruka Tōjō"],
    ["Dōbutsu Biscuit", "Dōbutsu Biscuits"],
    ["Shōgo Sakamoto", "Shougo Sakamoto"],
    ["Yuu Ayase", "Yu Ayase"],
    # ["Yuusuke Shirai", "Yuusuke Shirai", "Yusuke Shirai"],.
    ["Yuusuke Shirai", "Yusuke Shirai"],
    # ["Yuuki Hirose", "Yuuki Hirose"],
    ["Akari Kitō", "Akari Kitou", "Akari Kito"],
    ["Marika Kouno", "Marika Kōno"],
    ["Mina Katahira", "Mina Kitahara"],
    ["Seiko Oomori", "Seiko Ōmori"],
    ["Katzmic", "Kitzmic"],
    ["Yuka Aisaka", "Yuuka Aisaka"],
    ["Yuuki Kawahara", "Yuuki Kuwahara"],
    # ["Yuusuke Kobayashi", "Yuusuke Kobayashi"],
    ["Rina Honizumi", "Rina Honnizumi"],
    ["Yutaro Miura", "Yuutarō Miura"],
    ["Miracle☆StAr", "Miracle StAr"],
    ["Yui Kondou", "Yui Kondo"],
    ["Yuusuke Shirai", "Yusuke Shirai"],
    ["Gokudolls Niji-gumi", "Gokudolls Kan-gumi"],
    ["Minyou Girls", "Minyo Girls"],
    ["Ai Ichikawa", "I.C.I. a.k.a. Ai Ichikawa"],
    ["Starlight Kukugumi", "Starlight Kuku-gumi"],
    ["Ayasa Itou", "Ayasa Ito", "Ayasa Itō"],
    ["Hinata Satou", "Hinata Satō"],
    ["Seria Fukagawa", "Seria Fukugawa"],
    ["Yuuka Morishima", "Yuka Morishima"],
    ["Shou Nogami", "Sho Nogami"],
    ["Shouhei Komatsu", "Shōhei Komatsu"],
    ["Larissa Tago Takeda", "Rarisa Tago Takeda"],
    ["Reina Kondo", "Reina Kondou"],
    ["Yuki Ono", "Yuuki Ono"],
    ["Tokiko Katō", "Tokiko Kato"],
    ["Kyoko Tsuruno", "Kyouko Tsuruno"],
    ["Yuji Mitsuya", "Yuuji Mitsuya"],
    ["Yuko Imada", "Yuuko Imada"],
    ["Natsuki Kato", "Natsuki Katou"],
    ["Mimori Suzuko", "Suzuko Mimori"],
    ["Ushiro kara Haiyori-tai B", "Ushiro Kara Haiyori-tai B"],
    ["yosh", "Yosh", "yosh(Survive Said The Prophet)"],
    ["CHINO", "Chino"],
    ["THE ALFEE", "ALFEE"],
    ["Midori Karashima", "Midori Karashima "],
    # probably because database inconsistency
    # proper alternative names
    ["ASCA", "Asuka Ōkura"],
    ["GRAN RODEO", "GRANRODEO"],
    ["DAOKO", "daoko"],
    ["angela", "ANGELA"],
    ["Minami", "Minami Kuribayashi", "exige"],
    ["Yumi Matsutoya", "Yumi Arai"],
    ["Yuuka Nanri"],
    ["Aira Yuuki"],
    ["Wakana", "WAKANA"],
    ["Keiko Yoshinari"],
    ["Ushio Hashimoto", "Ushio"],
    ["Ai Kawashima", "♡"],
    ["(K)NoW_NAME:AIJ", "AIJ"],
    ["(K)NoW_NAME:NIKIIE", "NIKIIE"],
    ["Kaede", "Kaede☆"],
    ["TWO-MIX", "II MIX⊿DELTA"],
    ["T.M.Revolution", "Takanori Nishikawa"],
    ["Fire Bomber", "FIRE BOMBER"],
    ["AiRI", "d2b"],
    ["Mai Mizuhashi", "MARiA", "MARIA from GARNiDELiA"],
    ["Konomi Suzuki", "Koneko Yasagure"],
    ["Lia", "IA"],
    ["Aya Hirano", "Aya Hirano from Springs"],
    ["AKINO", "AKINO from bless4"],
    ["AIKI", "AIKI from bless4"],
    ["Yui Ishikawa", "Yui Ishikawa from attackers"],
    ["Hiroshi Kamiya", "Hiroshi Kamiya from No Name"],
    ["Hiroyuki Sawano", "SawanoHiroyuki[nZk]"],
    ["UraShimaSakataSen", "Fourpe"],
    ["Meltic StAr", "Meltic"],
    ["AiM", "Ai Maeda"],
    ["OKINO.SHUNTARO", "Okino, Shuntaro"],
    ["Miracle☆Kiratts", "Kiratts"],
    ["Fruit Tart", "Tart"],
    ["Takahiro Sakurai", "MC469MA"],
    ["Cream Anmitsu", "Anmitsu"],
    ["Lupintic Six", "Lupintic Six with Friends", "Lupintic Five with Friends"],
    ["TAKAKO & THE CRAZY BOYS", "TAKAKO&THE CRAZY BOYS", "Shirai Takako &CRAZY BOYS"],
    ["Momoiro Clover Z", "Momoiro Clover", "MomoClo-chan Z"],
    ["Yuuka Saegusa", "U-ka saegusa"],
    ["MIO", "MIQ"],
    ["Special Kids", "Special Kids as chorus"],
    ["DAIGO☆STARDUST", "DAIGO"],
    ["Honey Bee(YURIA)", "Honey Bee"],
    ["Mayumi Morinaga", "senya (Yuuhei Satellite)"],
    ["marina", "Girls Dead Monster (marina)"],
    ["LiSA", "Girls Dead Monster (LiSA)"],
    ["Lisa Komine", "lisa"],
    ["little by little", "Satou-san to Suzuki-kun"],
    ["yoshiki*lisa", "Risa Yoshiki"],
    ["Mariko Kouda", "Mariko Kōda", "miyuki"],
    ["TrySail", "TRINITYAiLE"],
    ["Sphere", "LizNoir"],
    [
        "Hironobu Kageyama",
        "Hironobu Kageyama (JAM Project)",
        "JAM Project (Hironobu Kageyama)",
    ],
    ["Hiroshi Kitadani", "Hiroshi Kitadani (JAM Project)"],
    ["Masami Okui", "Masami Okui (JAM Project)"],
    [
        "Yoshiki Fukuyama",
        "Yoshiki Fukuyama (JAM Project)",
        "JAM Project (Yoshiki Fukuyama)",
    ],
    ["SUEMITSU & THE SUEMITH", "Atsushi Suemitsu"],
    ["Masaaki Endoh", "Masaaki Endoh (JAM Project)", "JAM Project (Masaaki Endoh)"],
    ["Arika Takarano", "Arika Takarano (ALI PROJECT)"],
    ["Saori Hayami", "Saori Hayami (from Eclipse)"],
    ["Haruka Tomatsu", "Haruka Tomatsu (from Eclipse)"],
    ["Megumi Nakajima", "Megumi Nakajima (from Eclipse)"],
    ["Fumihiko Tachiki", "Tachiki Fumihiko"],
    ["Hibiku Yamamura", "hibiku"],
    ["Milky Holmes Feathers", "Feathers"],
    ["EMILY BINDIGER", "Emily Bindiger"],
    ["Hound Dog", "HOUND DOG"],
    ["Shoujobyo", "Shoujobyou"],
    ["Kent It\u014d", "Kento Itou"],
    ["UNDER GRAPH", "Under Graph"],
    ["Shirahamazaka High School Chorus Club", "Shirahamazaka Koukou Gasshou-bu"],
    ["LAZY", "ULTIMATE LAZY for MAZINGER"],
    ["ROOT FIVE", "\u221a5"],
    ["m.o.v.e", "move"],
    ["Kitagawa Chieko", "Chieko Kitagawa"],
    ["Shiena Nishizawa", "EXiNA"],
    ["Waka Kirishima", "Waka from STAR☆ANIS"],
    ["Fuuri Uebana", "Fuuri from STAR☆ANIS"],
    ["Yuna Ichikura", "Yuna from STAR☆ANIS"],
    ["Remi Mitani", "Remi from STAR☆ANIS"],
    ["Eri Aino", "Eri from STAR☆ANIS"],
    ["Risuko Sasakama", "Risuko from STAR☆ANIS"],
    ["Ruka Endou", "Ruka from STAR☆ANIS", "Ruka from AIKATSU\u2606STARS!"],
    ["Sunao Yoshikawa", "Sunao from STAR☆ANIS"],
    ["Moe Yamazaki", "Moe from STAR☆ANIS"],
    ["Mona Tomoyama", "Mona from STAR☆ANIS", "Mona from AIKATSU\u2606STARS!"],
    ["Yuniko Morishita", "Yuniko from STAR☆ANIS"],
    ["Miki Mirai", "Miki from AIKATSU☆STARS!"],
    ["Miho Amane", "Miho from AIKATSU☆STARS!"],
    ["Nanase Matsuoka", "Nanase from AIKATSU☆STARS!"],
    ["Kana Hoshizaki", "Kana from AIKATSU☆STARS!"],
    ["Sena Horigushi", "Sena from AIKATSU☆STARS!"],
    ["Rie Fujishiro", "Rie from AIKATSU☆STARS!"],
    ["Akane Matsunaga", "Aine from BEST FRIENDS!"],
    ["Ibuki Kido", "Mio from BEST FRIENDS!"],
    ["Karen Miyama", "Maika from BEST FRIENDS!"],
    ["Yui Ninomiya", "Ema from BEST FRIENDS!"],
    ["Azusa Tadokoro", "Karen from BEST FRIENDS!"],
    ["Ayaka Ōhashi", "Mirai from BEST FRIENDS!"],
    ["Emiri Suyama", "Sakuya from BEST FRIENDS!"],
    ["Yuuki Kuwahara", "Kaguya from BEST FRIENDS!"],
    ["Saori Oonishi", "Alicia from BEST FRIENDS!"],
    ["Yoko Hikasa", "Hibiki from BEST FRIENDS!"],
    ["Rin Aira", "Wakaba from BEST FRIENDS!", "Raki from BEST FRIENDS!"],
    ["Kensuke Ushio", "agraph"],
    ["Sh\u014dta Aoi", "Shouta Aoi"],
    ["Youji Ueda", "Y\u014dji Ueda"],
    ["STEREO DIVE FOUNDATION", "R・O・N"],
    ["ORIGA", "Origa"],
    ["dream", "Dream"],
    ["Yukana", "Yukana Nogami"],
    ["Hana*Hana", "HANA HANA"],
    ["Mi~ko", "MI-KO"],
    ["LOVE", "Ai Otsuka"],
    ["YU-KI", "Yuuki Kitamura"],
    ["Motsu", "MOTSU"],
]
# Alternative Artists names
# 0000


# Todo manually after everything is done:
""" SAME GROUP WITH DIFFERENT MEMBER CONFIGURATIONS
jam project
k-on

_________ DIFFERENT ARTIST WITH SAME NAME
karin takahashi
hinata satou

________________ MISSING ?:
Seizei Ganbare! Mahou Shoujo Kurumi 3rd Season

________________ BACK UP SINGERS
humming bird
move etc..
smith with MON
nanjo with prism mates
glitter green
roselia
bang dream
RONDO
Ourin Sisters
eclipse
most of sbr
friends (horimiya)
Uchuu Shoujo Vanaren-tai
"""
