# tokusatsu with ichirou mizuki is only composing?
# This is a POC, it will be manage through the Admin UI directly

to_remove_composer = [
    "TENMON",
    "Hiroyuki Sawano",
    "Another Infinity",
    "Rasmus Faber",
    "Satoru Kosaki",
    "TeddyLoid",
    "Skrillex",
    "Nik Roos",
    "HoneyWorks",
    "livetune",
    "Seatbelts",
    "Utsu-P",
    "Hachioji-P",
    "You & Explosion Band",
    "ROUND TABLE",
    "REDALiCE",
    "Akira Miyagawa",
    "(K)NoW_NAME",
    "Ryo Kunihiko",
    "Yasutaka Nakata",
    "Sound Team jdk",
    "Rio Kouyama",
    "Jun Maeda",
    "Maiko Iuchi",
    "Tom-H@ck",
]
# Multiple people with same name
# Yuuyu

composer_database = [
    {
        "artists_ids": ["fripSide", "ALTIMA"],
        "songs": ["Get goal!", "SHOOT!", 32008, 27252],
        "composers": ["Satoshi Yaginuma"],
        "arrangers": ["Satoshi Yaginuma"],
    },
    {
        "artists_ids": ["ANGELA"],
        "songs": [12696, 13363, 12568],
        "composers": ["Atsuko", "Katsu"],
        "arrangers": ["Katsu"],
    },
    {
        "artists_field_sub": ["SawanoHiroyuki[nZk]"],
        "artists_ids": [
            "Hiroyuki Sawano",
            "Gemie",
            "mpi",
            "CASG",
            "Benjamin Anderson",
            "Benjamin",
            "Laco",
            "Eliana",
            "Mika Kobayashi",
        ],
        "songs": [
            21655,
            7832,
            24733,
            10275,
            10276,
            11770,
            17913,
            17996,
            18009,
            17864,
            21256,
            34755,
            11771,
            17912,
            13332,
            31154,
            14567,
            14815,
            14816,
            18399,
            15816,
            15817,
            32262,
            17568,
            18727,
            20997,
            24448,
            34463,
            31719,
            35044,
        ],
        "composers": ["Hiroyuki Sawano"],
        "arrangers": ["Hiroyuki Sawano"],
    },
    # 140
    {
        "artists_ids": ["TENMON"],
        "songs": [
            2072,
            5102,
            8999,
            9001,
            "Kizamu Kisetsu",
            9703,
            9707,
            9709,
            9710,
            19241,
            23435,
            23436,
            "Tatta Ichido no Kiseki",
            10883,
            29802,
            6251,
            28201,
            28202,
            2764,
            33735,
        ],
        "composers": ["TENMON"],
        "arrangers": ["TENMON"],
    },
    {
        "songs": [25017],
        "composers": ["TENMON", "Eiichirou Yanagi"],
        "arrangers": ["TENMON", "Eiichirou Yanagi"],
    },
    {
        "songs": [9005],
        "composers": ["TENMON"],
        "arrangers": ["TENMON", "Eiichirou Yanagi"],
    },
    {
        "songs": [9002, 9711, 19253],
        "composers": ["TENMON"],
        "arrangers": ["Eiichirou Yanagi"],
    },
    {
        "songs": [2764, 33735],
        "composers": ["Sound Team jdk", "TENMON"],
        "arrangers": ["Hiroshi Shinkawa"],
    },
    {
        "songs": [20342],
        "composers": ["Sound Team jdk"],
        "arrangers": ["Yukihiro Jindou"],
    },
    {
        "songs": [13714],
        "composers": ["Sound Team jdk"],
        "arrangers": ["Sound Team jdk"],
    },
    {
        "songs": [
            14680,
            18334,
            7617,
            "Akai Namida",
            "PSI-missing",
            12163,
            6652,
            16736,
            31910,
            19140,
            22898,
            "Asu e no Namida",
            6838,
            9643,
            20545,
        ],
        "composers": ["Tomoyuki Nakazawa"],
        "arrangers": ["Tomoyuki Nakazawa"],
    },
    {
        "songs": [
            "Vidro Moyou",
            "Contrail~Kiseki~",
            "Miracle Colors",
            "Loop-the-Loop",
            "ebb and flow",
            "lull ~Soshite Bokura wa~",
            "Hishoku no Sora",
            12780,
            18335,
            10440,
            11983,
            11984,
            8651,
            8896,
            22898,
            10902,
            31661,
            21990,
            10899,
            11777,
            8900,
            23440,
            9642,
        ],
        "composers": ["Tomoyuki Nakazawa"],
        "arrangers": ["Tomoyuki Nakazawa", "Takeshi Ozaki"],
    },
    {
        "songs": [11780, 11781, 10439, 10438],
        "composers": ["Tomoyuki Nakazawa", "Takeshi Ozaki"],
        "arrangers": ["Tomoyuki Nakazawa", "Takeshi Ozaki"],
    },
    {
        "songs": [13217],
        "composers": ["Takeshi Ozaki"],
        "arrangers": ["Tomoyuki Nakazawa", "Takeshi Ozaki"],
    },
    {
        "songs": [7617],
        "composers": ["Tomoyuki Nakazawa"],
        "arrangers": ["Tomoyuki Nakazawa", "Maiko Iuchi"],
    },
    {
        "songs": [11991],
        "composers": ["Tomoyuki Nakazawa"],
        "arrangers": ["Kenji Arai"],
    },
    {
        "songs": ["Chasse"],
        "composers": ["Kazuya Takase"],
        "arrangers": ["Tomoyuki Nakazawa", "Maiko Iuchi"],
    },
    {
        "songs": ["Higurashi no Naku Koro ni"],
        "composers": ["Tomoyuki Nakazawa"],
        "arrangers": ["Tomoyuki Nakazawa", "Kazuya Takase"],
    },
    {
        "songs": ["Second Flight"],
        "composers": ["Kazuya Takase"],
        "arrangers": ["Tomoyuki Nakazawa", "Kazuya Takase"],
    },
    {
        "songs": [12163],
        "composers": ["Tomoyuki Nakazawa"],
        "arrangers": ["Tomoyuki Nakazawa", "Kazuya Takase", "Takeshi Ozaki"],
    },
    {
        "songs": [31910],
        "composers": ["Tomohiro Takeshita"],
        "arrangers": ["Tomoyuki Nakazawa", "Tomohiro Takeshita", "Takeshi Ozaki"],
    },
    {
        "songs": [26370],
        "composers": ["Jun Maeda"],
        "arrangers": ["Tomoyuki Nakazawa", "Takeshi Ozaki"],
    },
    {
        "songs": [13475],
        "composers": ["Jun Maeda"],
        "arrangers": ["Tomoyuki Nakazawa", "Takeshi Ozaki", "Kazuya Takase"],
    },
    {
        "songs": [7429],
        "composers": ["Marty Friedman"],
        "arrangers": ["Tomoyuki Nakazawa", "Maiko Iuchi"],
    },
    {
        "songs": [13822],
        "composers": ["Jin"],
        "arrangers": ["Tomoyuki Nakazawa", "Takeshi Ozaki"],
    },
    {
        "songs": [28643, 28644, 15493, 13701, 13468],
        "composers": ["Jun Maeda"],
        "arrangers": ["MANYO"],
    },
    {
        "songs": [
            18025,
            18021,
            18026,
            13702,
            9282,
            9702,
            9281,
            27709,
            9284,
            "Toki o Kizamu Uta",
            "Bravely You",
            "Yake Ochinai Tsubasa",
            14883,
            ["My Soul,Your Beats!", "Lia"],
            10318,
            "Brave Song",
        ],
        "composers": ["Jun Maeda"],
        "arrangers": ["anant-garde eyes", "Ai Kamachi", "Nagie"],
    },
    {
        "songs": [13471, 13700, 12463],
        "composers": ["Jun Maeda"],
        "arrangers": ["MintJam"],
    },
    {
        "songs": [
            14881,
            21510,
            14884,
            21512,
            21513,
            21514,
        ],
        "composers": ["Shuyo Hikari"],
        "arrangers": ["Shuyo Hikari"],
    },
    {
        "songs": [["My Soul,Your Beats!", "LiSA"], 10323, 10317, 10319, 10320, 10321],
        "composers": ["Jun Maeda"],
        "arrangers": ["Shuyo Hikari"],
    },
    {
        "songs": [14879, 14882, 21506, 21508],
        "composers": ["Jun Maeda"],
        "arrangers": ["Tomohiro Takeshita"],
    },
    {
        "songs": [9547],
        "composers": ["Jun Maeda"],
        "arrangers": ["Magome Togoshi"],
    },
    {
        "songs": [8845, 9548],
        "composers": ["Jun Maeda"],
        "arrangers": ["Takumaru"],
    },
    {
        "songs": [13474],
        "composers": ["Jun Maeda"],
        "arrangers": ["Manack"],
    },
    {
        "songs": [13473],
        "composers": ["Jun Maeda"],
        "arrangers": ["Yu Hagiwara"],
    },
    {
        "songs": [7733, 21398],
        "composers": ["Jun Maeda"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": [18892],
        "composers": ["Jun Maeda"],
        "arrangers": ["Ryo Okabe"],
    },
    {
        "songs": [7735],
        "composers": ["Jun Maeda"],
        "arrangers": ["Hajime Kikuchi"],
    },
    {
        "songs": [5211, 23914],
        "composers": ["Jun Maeda"],
        "arrangers": ["Shinji Orito"],
    },
    {
        "songs": [7734],
        "composers": ["Key"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": [
            893,
            7732,
            35254,
            5209,
            6276,
            7163,
            14679,
            "sign",
            "Shooting Star",
            "Sora no Mori de",
            31743,
        ],
        "composers": ["Shinji Orito"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": [8850, 15499],
        "composers": ["Shinji Orito"],
        "arrangers": ["MANYO"],
    },
    {
        "songs": ["TORCH"],
        "composers": ["Shinji Orito"],
        "arrangers": ["Kentarou Fukushi"],
    },
    {
        "songs": [31908],
        "composers": ["Shinji Orito"],
        "arrangers": ["Shouji Morifuji"],
    },
    {
        "songs": [25513, 12464, 13698, 15492, 21771],
        "composers": ["Shinji Orito"],
        "arrangers": ["MintJam"],
    },
    {
        "songs": [13470],
        "composers": ["Shinji Orito"],
        "arrangers": ["nishi-ken"],
    },
    {
        "songs": [16028],
        "composers": ["Shinji Orito"],
        "arrangers": ["Takayuki Negishi"],
    },
    {
        "songs": [15495],
        "composers": ["Shinji Orito"],
        "arrangers": ["Terra"],
    },
    {
        "songs": [18022],
        "composers": ["Shinji Orito"],
        "arrangers": ["Ryousuke Shigenaga"],
    },
    {
        "songs": [32807],
        "composers": ["Shinji Orito"],
        "arrangers": ["Shinpei Nasuno"],
    },
    {
        "songs": [11264],
        "composers": ["HAPPY SOUL MAN"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": [
            14792,
            11448,
            "Red Fraction",
            "Red fraction IO drive mix",
            11284,
            "Tenjou o Kakeru Mono-tachi",
            22203,
            "Hayate no Gotoku!",
            ["Proof", "MELL"],
            "Super scription of data",
            6651,
            6653,
            1122,
            8959,
            8897,
            8898,
            18897,
            14154,
            "Rakuen PROJECT",
            "Gardens",
            22643,
            5371,
            "X-encounter",
        ],
        "composers": ["Kazuya Takase"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": [7351],
        "composers": ["KOTOKO"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": [10903],
        "composers": ["Barbarian On The Groove"],
        "arrangers": ["Barbarian On The Groove"],
    },
    {
        "songs": ["Ko no Me Kaze", "Chikai Goto ~Sukoshi dake mou Ichido~"],
        "composers": ["IKU"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": ["Rimless ~Fuchinashi no Sekai~"],
        "composers": ["IKU", "Kazuya Takase"],
        "arrangers": ["Kazuya Takase"],
    },
    {
        "songs": [
            "Get my way!",
        ],
        "composers": ["Kazuya Takase"],
        "arrangers": ["Kazuya Takase", "Takeshi Ozaki"],
    },
    {
        "songs": ["Farewell song"],
        "composers": ["Magome Togoshi"],
        "arrangers": ["Magome Togoshi"],
    },
    {
        "songs": [
            11987,
            11988,
            12717,
            24061,
            11992,
            30502,
            21188,
            32646,
            32612,
            32613,
            32614,
            23679,
            27449,
            28356,
            16187,
            19838,
            8793,
            26465,
            "Kyoumei no True Force",
            30052,
            8871,
            15136,
            20393,
            18269,
            20619,
            25106,
            26274,
            30837,
            10900,
            10901,
            13216,
            7770,
            32301,
            32430,
            33105,
        ],
        "composers": ["Maiko Iuchi"],
        "arrangers": ["Maiko Iuchi"],
    },
    {
        "songs": [18024],
        "composers": ["Maiko Iuchi"],
        "arrangers": ["Ryo Mizutsuki"],
    },
    {
        "songs": [18023],
        "composers": ["Maiko Iuchi"],
        "arrangers": ["Hideki Higuchi"],
    },
    {
        "songs": [18028],
        "composers": ["Maiko Iuchi"],
        "arrangers": ["Donmaru"],
    },
    {
        "songs": [
            26266,
            15193,
            15194,
            15796,
            15192,
            21772,
            15574,
            21690,
            14321,
            "TRY UNITE!",
            30587,
            24135,
            12598,
            16800,
            30887,
        ],
        "composers": ["Rasmus Faber"],
        "arrangers": ["Rasmus Faber"],
    },
    {
        "songs": [22042, 22043],
        "composers": ["Rasmus Faber"],
        "arrangers": [
            "Rasmus Faber",
            "Anton Dromberg",
            "Daniel Rosenqvist",
            "Erasmus Talbot",
            "Martin Landström",
        ],
    },
    {
        "artists_field_sub": ["HoneyWorks"],
        "artists_ids": ["sana", "LIP×LIP"],
        "songs": [12785, 22148, 25113, 20795, 13049, 16137, 19326, 34222],
        "composers": ["HoneyWorks"],
        "arrangers": ["HoneyWorks"],
    },
    {
        "songs": ["~Outgrow~", 14755],
        "composers": ["HoneyWorks"],
        "arrangers": ["Katsuhiko Kurosu"],
    },
    {
        "songs": [
            "Trip -innocent of D-",
        ],
        "composers": ["c.g mix"],
        "arrangers": ["Takeshi Ozaki", "c.g mix"],
    },
    {
        "songs": [
            9006,
            24643,
            7616,
            12786,
            14756,
            7428,
            11286,
            8716,
            "daily-daily Dream",
            "Sociometry",
        ],
        "composers": ["c.g mix"],
        "arrangers": ["c.g mix"],
    },
    {
        "songs": [28283],
        "composers": ["c.g mix"],
        "arrangers": ["Atsuhiko Nakatsubo", "c.g mix"],
    },
    {
        "songs": [13201],
        "composers": ["c.g mix"],
        "arrangers": ["Takeshi Hoshino", "c.g mix"],
    },
    {
        "songs": [5112, 31578],
        "composers": ["KOTOKO", "Atsuhiko Nakatsubo"],
        "arrangers": ["Atsuhiko Nakatsubo"],
    },
    {
        "songs": [10409],
        "composers": ["Another Infinity", "Starving Trancer", "Ryu☆"],
        "arrangers": ["Starving Trancer"],
    },
    {
        "songs": [["Affection", "Mayumi Morinaga"], "Towa no Kizuna", 12480],
        "composers": ["Another Infinity", "Starving Trancer", "Ryu☆"],
        "arrangers": ["Another Infinity", "Starving Trancer", "Ryu☆"],
    },
    {
        "songs": [14771, 33833, 24592],
        "composers": ["Starving Trancer"],
        "arrangers": ["Starving Trancer"],
    },
    {
        "songs": [27022],
        "composers": ["Ryu☆"],
        "arrangers": ["Starving Trancer"],
    },
    {
        "songs": [16290],
        "composers": ["Ryu☆"],
        "arrangers": ["Yanagita Mitsuyasu"],
    },
    {
        "songs": [
            18393,
            16615,
            18394,
            22679,
            15580,
            18266,
            18006,
            20737,
            15779,
            25144,
            35068,
        ],
        "composers": ["TeddyLoid"],
        "arrangers": ["TeddyLoid"],
    },
    {
        "songs": [18005],
        "composers": ["TeddyLoid"],
        "arrangers": ["TeddyLoid", "Ikeda Mitsunori", "☆Taku Takahashi"],
    },
    {
        "songs": [18004],
        "composers": ["TeddyLoid", "Emyli", "Taku Takahashi"],
        "arrangers": ["TeddyLoid", "Ikeda Mitsunori"],
    },
    {
        "songs": [18395],
        "composers": ["Jin"],
        "arrangers": ["TeddyLoid"],
    },
    {
        "songs": [16617],
        "composers": ["TeddyLoid", "MaryJane"],
        "arrangers": ["TeddyLoid"],
    },
    {
        "songs": [32735],
        "composers": ["DECO*27"],
        "arrangers": ["Rockwell", "TeddyLoid"],
    },
    {
        "songs": [27029, 27030, 32905],
        "composers": ["Yuujin Kitagawa"],
        "arrangers": ["TeddyLoid"],
    },
    {
        "songs": [22678],
        "composers": ["TeddyLoid", "Giga"],
        "arrangers": ["TeddyLoid", "Giga"],
    },
    {
        "songs": [22233, 24136],
        "composers": ["Lozareena"],
        "arrangers": ["TeddyLoid"],
    },
    {
        "songs": [31737],
        "composers": ["Luis Ogata"],
        "arrangers": ["TeddyLoid"],
    },
    {
        "artists_field_sub": ["FictionJunction"],
        "artists_ids": [
            "Emily Bindiger",
            "Yuri Kasahara",
            "Yuriko Kaida",
            "Eri Itou",
            "Kalafina",
            "Yuki Kajiura",
            "See-Saw",
        ],
        "songs": [
            30408,
            30409,
            30410,
            30411,
            30407,
            5499,
            19047,
            19045,
            "Calling",
            2977,
            8733,
            20242,
            25927,
            27489,
            33342,
            30526,
            35484,
            21974,
            15901,
            15902,
            15903,
            6691,
            6694,
            6695,
            4126,
            34560,
            35615,
            2400,
            34134,
            5402,
            34139,
            5950,
            7627,
            5413,
            34140,
            7365,
            7629,
            34128,
            5416,
            7635,
            30625,
            34973,
            35484,
            34981,
            18817,
            25111,
            30482,
            30483,
            30484,
            30485,
            30486,
            30487,
            6350,
            27066,
            6351,
            27067,
            27068,
            27069,
            7756,
            4723,
            18483,
            18485,
            16601,
            16602,
            9045,
        ],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Yuki Kajiura"],
    },
    {
        "songs": [11199, 17922],
        "composers": ["Charles Gounod", "Johann Sebastian Bach"],
        "arrangers": ["Yuki Kajiura"],
    },
    {
        "songs": [7949],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["HΛL"],
    },
    {
        "songs": [2401, 34133, 5954],
        "composers": ["Toshihiko Sahashi"],
        "arrangers": ["Yuki Kajiura"],
    },
    {
        "songs": ["Sora wa Takaku Kaze wa Utau"],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Sorao Mori"],
    },
    {
        "songs": [30757],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Yuki Kajiura", "Kenichi Kimura"],
    },
    {
        "songs": [7757],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Hijiri Anze"],
    },
    {
        "songs": [9029, 6876],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Masayuki Sakamoto"],
    },
    {
        "songs": [6874],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Takeo Kajiwara", "Sousaku Sasaki"],
    },
    {
        "songs": [4027],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Akihisa Matsuura"],
    },
    {
        "songs": [5408, 34124],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Yuki Kajiura", "Susumu Nishikawa"],
    },
    {
        "songs": ["Sore wa Chiisana Hikari no You na"],
        "composers": ["Yuki Kajiura"],
        "arrangers": ["Ryou Eguchi"],
    },
    {
        "songs": [8726],
        "composers": ["Takumi"],
        "arrangers": ["Yuki Kajiura"],
    },
    {
        "artists_field_sub": ["TECHNOBOYS"],
        "songs": [
            9844,
            9845,
            9846,
            9847,
            9848,
            9849,
            9851,
            9852,
            9853,
            9854,
            9855,
            9856,
            21101,
            27120,
            29550,
            15319,
            15502,
            31561,
            21470,
            21469,
            23136,
            "BEAUTIFUL≒SENTENCE",
            23986,
            23984,
            23983,
            21730,
            23985,
            21730,
            16581,
            16489,
            16490,
            22801,
            25483,
            15765,
            15660,
            17567,
            21281,
            15331,
            21282,
            15332,
            32218,
            31291,
            20347,
            31778,
            "ReSTART 'THE WORLD'",
            "SHaVaDaVa in AMAZING♪",
            "TRINITY×SEVENTH+HEAVEN",
            25746,
            25747,
            25748,
            13675,
        ],
        "composers": [
            "TECHNOBOYS PULCRAFT GREEN-FUND",
            "Tomohisa Ishikawa",
            "Tooru Fujimura",
            "Youhei Matsui",
        ],
        "arrangers": [
            "TECHNOBOYS PULCRAFT GREEN-FUND",
            "Tomohisa Ishikawa",
            "Tooru Fujimura",
            "Youhei Matsui",
        ],
    },
    {
        "songs": [15325, 32645],
        "composers": ["Ichirou Araki"],
        "arrangers": [
            "TECHNOBOYS PULCRAFT GREEN-FUND",
            "Tomohisa Ishikawa",
            "Tooru Fujimura",
            "Youhei Matsui",
        ],
    },
    {
        "songs": [15791],
        "composers": ["Yousui Inoue"],
        "arrangers": [
            "TECHNOBOYS PULCRAFT GREEN-FUND",
            "Tomohisa Ishikawa",
            "Tooru Fujimura",
            "Youhei Matsui",
        ],
    },
    {
        "songs": [16614, 26379, 26380, 26381, 26382, 26383, 26384],
        "composers": ["Fumiya Fujii"],
        "arrangers": [
            "TECHNOBOYS PULCRAFT GREEN-FUND",
            "Tomohisa Ishikawa",
            "Tooru Fujimura",
            "Youhei Matsui",
        ],
    },
    {
        "songs": [13266, 20630, 27462, 30809, 23309],
        "composers": ["Tomohisa Ishikawa"],
        "arrangers": ["Tomohisa Ishikawa"],
    },
    {
        "songs": [20189],
        "composers": ["Tsukasa Yatoki"],
        "arrangers": ["Tomohisa Ishikawa"],
    },
    {
        "songs": [9019],
        "composers": ["shilo"],
        "arrangers": ["Tomohisa Ishikawa", "shilo"],
    },
    {
        "songs": [21463],
        "composers": ["Youhei Matsui"],
        "arrangers": ["Youhei Matsui"],
    },
    {
        "songs": [15954],
        "composers": ["Youhei Matsui"],
        "arrangers": ["TO-MAS"],
    },
    {
        "songs": [27187],
        "composers": ["Skrillex", "Nik Roos"],
        "arrangers": ["Skrillex", "Nik Roos"],
    },
    {
        "songs": [15975, 30886, 30412, 24987],
        "composers": ["SUGIZO"],
        "arrangers": ["SUGIZO"],
    },
    {
        "songs": [28457, 25757],
        "composers": ["SUGIZO", "Kenichi Yoshida"],
        "arrangers": ["SUGIZO"],
    },
    {
        "songs": [24328],
        "composers": ["Daisuke Inoue"],
        "arrangers": ["SUGIZO"],
    },
    {
        "songs": [24598],
        "composers": ["Sadaka Neil"],
        "arrangers": ["SUGIZO"],
    },
    {
        "songs": [33304],
        "composers": [
            "Miriya Katou",
            "Carlosk.",
            "Yoshida Brothers",
            "Kenichi Yoshida",
        ],
        "arrangers": [
            "Miriya Katou",
            "Carlosk.",
            "Yoshida Brothers",
            "Kenichi Yoshida",
        ],
    },
    {
        "songs": [
            12926,
            12924,
            "FLAT",
            13845,
            24564,
            24565,
            14185,
            16582,
            16583,
            20193,
            22092,
            16787,
            10787,
            11921,
            27258,
            28928,
            18230,
            18082,
            28942,
            "RESTART POiNTER",
            32532,
            33055,
            32531,
            25233,
            12883,
            "CLICK",
            13354,
            17899,
            10843,
            "reunion",
            13775,
            13048,
            15912,
            20546,
            34003,
        ],
        "composers": ["livetune"],
        "arrangers": ["livetune"],
    },
    {
        "songs": [16586],
        "composers": ["livetune"],
        "arrangers": ["Yuu Manabe"],
    },
    {
        "songs": [
            "Zannen-kei Rinjin-bu ★★☆",
            "Be My Friend",
            "Watashi no Ki-mo-chi",
            "Go EXCEED!!",
            "Perfect HERO",
            "Cagayake! GIRLS",
            "Cagayake! GIRLS (5-nin Ver.)",
            "GO! GO! MANIAC",
            "Utauyo!! MIRACLE",
            "Mainichi Koharu Biyori",
            "Natsu-iro Present",
            15084,
            11118,
            15548,
            23571,
            15450,
            30413,
            32126,
            16034,
            10296,
            11099,
        ],
        "composers": ["Tom-H@ck"],
        "arrangers": ["Tom-H@ck"],
    },
    {
        "songs": [30500, 12491, "Staccato Days"],
        "composers": ["Tom-H@ck"],
        "arrangers": ["Yamazo"],
    },
    {
        "songs": [17607],
        "composers": ["Tom-H@ck", "Kana Utatane"],
        "arrangers": ["Kana Utatane"],
    },
    {
        "songs": [21023],
        "composers": ["Tom-H@ck"],
        "arrangers": ["Kana Utatane"],
    },
    {
        "songs": [27670, 27936],
        "composers": ["Tokiya Sugishita"],
        "arrangers": ["Tom-H@ck", "Tokiya Sugishita"],
    },
    {
        "songs": [21024],
        "composers": ["Tokiya Sugishita"],
        "arrangers": ["KanadeYUK"],
    },
    {
        "songs": [16297],
        "composers": ["Tokiya Sugishita"],
        "arrangers": ["RINZO"],
    },
    {
        "songs": [14786],
        "composers": ["Tom-H@ck"],
        "arrangers": ["Keisuke Kurose"],
    },
    {
        "artists_ids": ["MYTH & ROID"],
        "composers": ["MYTH & ROID", "Tom-H@ck"],
        "arrangers": ["MYTH & ROID", "Tom-H@ck"],
    },
    {
        "songs": [10388, 8171],
        "composers": ["Yuji"],
        "arrangers": ["SuG", "Tom-H@ck"],
    },
    {
        "songs": [16653, 28735],
        "composers": ["Yuji"],
        "arrangers": ["KanadeYUK"],
    },
    {
        "songs": [28255],
        "composers": ["ZAQ"],
        "arrangers": ["KanadeYUK"],
    },
    {
        "songs": [28037],
        "composers": ["Kayoko Kusano"],
        "arrangers": ["KanadeYUK"],
    },
    {
        "songs": [16401],
        "composers": ["KanadeYUK", 'Masahiro "Godspeed" Aoki'],
        "arrangers": ["KanadeYUK"],
    },
    {
        "songs": [28145],
        "composers": ["KanadeYUK"],
        "arrangers": ["Sounosuke Takao"],
    },
    {
        "songs": ["Ichiban Ippai"],
        "composers": ["Tom-H@ck"],
        "arrangers": ["Hajime Hyakkoku"],
    },
    {
        "songs": [25121, 29892, 16326],
        "composers": ["Tom-H@ck"],
        "arrangers": ["Tom-H@ck", "KanadeYUK"],
    },
    {
        "songs": [24692, 21143, 34828, 29358],
        "composers": ["Tom-H@ck"],
        "arrangers": ["KanadeYUK"],
    },
    {
        "songs": [27728, 28736, 27963],
        "composers": ["KanadeYUK"],
        "arrangers": ["Tom-H@ck"],
    },
    {
        "songs": [34864, 29359],
        "composers": ["Tom-H@ck"],
        "arrangers": ["RINZO"],
    },
    {
        "songs": [27259],
        "composers": ["Tom-H@ck"],
        "arrangers": ["Tom-H@ck", "Yuuki Nara"],
    },
    {
        "songs": [23771],
        "composers": ["Masayoshi Ooishi"],
        "arrangers": ["Tom-H@ck", "KanadeYUK"],
    },
    {
        "songs": [19049, 16206],
        "composers": ["OxT", "Masayoshi Ooishi", "Tom-H@ck"],
        "arrangers": ["Tom-H@ck"],
    },
    {
        "songs": [15086, "Clattanoia", 17775, 21199],
        "composers": ["Masayoshi Ooishi"],
        "arrangers": ["Tom-H@ck"],
    },
    {
        "songs": [21348, 21346],
        "composers": ["Last Note."],
        "arrangers": ["Tom-H@ck"],
    },
    {
        "songs": [10224],
        "composers": ["Shunryuu"],
        "arrangers": ["Tom-H@ck"],
    },
]
[
    {
        "artists_field_sub": [],
        "artists_ids": [],
        "songs": [],
        "composers": [],
        "arrangers": [],
    },
]


fix_exception = [
    {
        "songs": [23263],
        "composers": ["Takahiro Obata"],
        "arrangers": ["Takahiro Obata"],
    },
    {
        "songs": ["Boku wa Boku de Atte"],
        "composers": ["Atsuko", "Satoshi Yaginuma"],
        "arrangers": ["Katsu", "Satoshi Yaginuma"],
    },
    {
        "songs": ["The end of escape"],
        "composers": ["Satoshi Yaginuma"],
        "arrangers": ["Katsu", "Satoshi Yaginuma"],
    },
    {
        "songs": [23903, 32008],
        "composers": ["Satoshi Yaginuma"],
        "arrangers": ["Shinya Saitou"],
    },
    {
        "songs": ["flower of bravery"],
        "composers": ["Chiyomaru Shikura"],
        "arrangers": ["Satoshi Yaginuma"],
    },
    {
        "songs": [4429],
        "composers": ["Atsuko", "Katsu"],
        "arrangers": ["Katsunori-H"],
    },
    {
        "songs": [9358, 9357, 9356, 22289, 22290, 22291, 22292],
        "composers": ["Rio Kouyama"],
        "arrangers": ["Rio Kouyama", "Katsu"],
    },
    {
        "songs": [7832],
        "composers": ["Hiroyuki Sawano"],
        "arrangers": ["Hiroyuki Sawano", "Takafumi Wada"],
    },
    {
        "songs": [18491],
        "composers": ["Keita Haga"],
        "arrangers": ["Yuki Kajiura"],
    },
    {
        "songs": [20278, 20279],
        "composers": ["Yoko Kanno"],
        "arrangers": ["Yoko Kanno"],
    },
    {
        "songs": [
            34927,
            34928,
            18003,
            33563,
            23661,
            33582,
            33583,
            33584,
            34925,
            34926,
            34924,
        ],
        "composers": ["Taku Iwasaki"],
        "arrangers": ["Taku Iwasaki"],
    },
    {
        "songs": [446, 28256],
        "composers": ["Tsukasa Nagoya"],
        "arrangers": ["Tsukasa Nagoya"],
    },
    {
        "songs": [5332],
        "composers": ["Yuriko Kaida"],
        "arrangers": ["Hiroshi Imaizumi"],
    },
    {
        "songs": [35497],
        "composers": ["Cheru Watanabe"],
        "arrangers": ["Cheru Watanabe"],
    },
    {
        "songs": [4003],
        "composers": ["Richard Rodgers"],
        "arrangers": ["Shinsuke Kazato"],
    },
    {
        "songs": [4004],
        "composers": ["Masayuki Kishi"],
        "arrangers": ["Shinsuke Kazato"],
    },
    {
        "songs": [4005],
        "composers": ["Shinsuke Kazato"],
        "arrangers": ["Shinsuke Kazato"],
    },
    {
        "songs": [22420, 22421],
        "composers": ["Tomohisa Ishikawa"],
        "arrangers": ["Tomohisa Ishikawa"],
    },
    {
        "songs": [18408],
        "composers": ["Youhei Matsui"],
        "arrangers": ["Tomohisa Ishikawa", "Youhei Matsui"],
    },
    {
        "songs": [27348],
        "composers": ["MYTH & ROID", "Tom-H@ck"],
        "arrangers": ["Tom-H@ck", "Kevin Penkin"],
    },
]

# coaltar of the deepers / Goro Watari

# marty friedman
#  Bach/Gounod
# kajiura sing and sometime don't

# groups
# sound team jdk, honeyworks, mintjam, anant-garde, i've, technoboys

# sometime sing sometime not
# sugizo

# alt names
# fish tone/atsuhiko nakatsubo
# livetune, kz
