# Splitting Config

splitters = r" VS | vs | & | , |, | featuring\. | Featuring\. | featuring | Featuring | feat\. | feat\.|feat\. |feat\.| FEAT. | ft\. | ft\.|ft\. |ft\.| x | × | with |＆| / |/| meets | adding | and "
secondary_splitters = r"・|& | &|&| ,|,| ×|× |×| \+ |\+"

splitting_exception_list = [
    ## To check
    (
        "ave;new project feat Saori Sakura×Dorechu",
        ("ave;new project", "Saori Sakura", "Dorechu"),
    ),
    ("Yuji Ohno & Lupintic Six", ("Yuji Ohno", "Lupintic Six")),
    (
        "You & Explosion Band feat. Lyn Inaizumi",
        ("You & Explosion Band", "Lyn Inaizumi"),
    ),
    ("You & Explosion Band featuring Lileth", ("You & Explosion Band", "Lileth")),
    ("ZONE&Run Time All Stars", ("ZONE", "Run Time All Stars")),
    ## Force splitting (splitters that are not automatically recognized)
    # to
    ("Skirt to ODD Foot Works", ("Skirt", "ODD Foot Works")),
    (
        "Yuka Uchiyae to Shizuku no Mori no Nakama-tachi",
        ("Yuka Uchiyae", "Shizuku no Mori no Nakama-tachi"),
    ),
    ("PUFFY to Tsuide ni TOOBOE", ("PUFFY", "TOOBOE")),
    ("chelmico to ryo takahashi", ("chelmico", "ryo takahashi")),
    ("Soraru to Rib", ("Soraru", "Rib")),
    ("Mari Yaguchi to Straw Hat", ("Mari Yaguchi", "Straw Hat")),
    ("Osamu Yamada to Hello Nights", ("Osamu Yamada to Hello Nights",)),
    ("Taku Izumi to Sono Family", ("Taku Izumi", "Sono Family")),
    (
        "Hiroka Nishizawa to Mori no Juunin-tachi",
        ("Hiroka Nishizawa", "Mori no Juunin-tachi"),
    ),
    ("Ei Morisako to Amigo Penguins", ("Ei Morisako", "Amigo Penguins")),
    ("Kishidan to Hiroshi Kitadani", ("Kishidan", "Hiroshi Kitadani")),
    ("Mio Saeki to Ryoko Shiraishi", ("Mio Saeki", "Ryoko Shiraishi")),
    (
        "Aqours to Uranohoshi no Nakama-tachi",
        (
            "Aqours",
            "Uranohoshi no Nakama-tachi",
        ),
    ),
    (
        "Tomoe Ohmi to Palette",
        (
            "Tomoe Ohmi",
            "Palette",
        ),
    ),
    (
        "Dreaming to Kyouryuu no Kuni no Nakama-tachi",
        (
            "Dreaming",
            "Kyouryuu no Kuni no Nakama-tachi",
        ),
    ),
    ("Me to Humbert Humbert", ("Me", "Humbert Humbert")),
    ("Unsho Ishizuka to Pokemon Kids", ("Unsho Ishizuka", "Pokemon Kids")),
    (
        "Sogeking to Shounen Shoujo Gasshou-dan",
        ("Sogeking", "Shounen Shoujo Gasshou-dan"),
    ),
    (
        "Pupa Mucho to Muchachiita to Etsuko Kozakura to Mayuko Omimura to Yukiji to Rie Kugimiya",
        (
            "Pupa Mucha",
            "Muchachiita",
            "Etsuko Kozakura",
            "Mayuko Omimura",
            "Yukiji",
            "Rie Kugimiya",
        ),
    ),
    ("Chiita to Mitsubachi Gasshou-dan", ("Chiita", "Mitsubachi Gasshou-dan")),
    ("Katsuko Morita to The Pretties", ("Katsuko Morita", "The Pretties")),
    (
        "Eri Itou to Mori no Ki Jidou Gasshou-dan",
        ("Eri Itou", "Mori no Ki Jidou Gasshou-dan"),
    ),
    ("Naomi Tamura to Himawari Gasshou-dan", ("Naomi Tamura", "Himawari Gasshou-dan")),
    (
        "LaSalle Ishii to Kochikame Win Gasshou-dan",
        ("LaSalle Ishii", "Kochikame Win Gasshou-dan"),
    ),
    ("Mitsuko Horie to Angel '03", ("Mitsuko Horie", "Angel '03")),
    ("Haruna Ikezawa to Kouki Miyata", ("Haruna Ikezawa", "Kouki Miyata")),
    (
        "Osamu Minagawa to Hibari Jidou Gasshou-dan",
        ("Osamu Minagawa", "Hibari Jidou Gasshou-dan"),
    ),
    ("Seiichi Yamamoto to Fushigi Robot", ("Seiichi Yamamoto", "Fushigi Robot")),
    ("Akiko Kanazawa to Soichi Terada", ("Akiko Kanazawa", "Soichi Terada")),
    ("Masaaki Endoh to Three G's 2005", ("Masaaki Endoh", "Three G's 2005")),
    ("Rina Satou to Asuka Oogame", ("Rina Satou", "Asuka Oogame")),
    (
        "My Melodies to Maryland no Nakama-tachi",
        ("My Melodies", "Maryland no Nakama-tachi"),
    ),
    ("Kenji Ohtsuki to Fumihiko Kitsutaka", ("Kenji Ohtsuki", "Fumihiko Kitsutaka")),
    ("Kana Ueda to Yukai na Nakama-tachi", ("Kana Ueda", "Yukai na Nakama-tachi")),
    (
        "Kenji Ohtsuki to Zetsubou Shoujo-tachi",
        ("Kenji Ohtsuki", "Zetsubou Shoujo-tachi"),
    ),
    ("ROLLY to Zetsubou Shoujo-tachi", ("ROLLY", "Zetsubou Shoujo-tachi")),
    ("Ayano Tsuji to BEAT CRUSADERS", ("Ayano Tsuji", "BEAT CRUSADERS")),
    ("Ayumi Tsunematsu to Kodomo-tachi", ("Ayumi Tsunematsu", "Kodomo-tachi")),
    (
        "Kenji Ohtsuki to Zetsubou Shoujo-tachi feat. Rap-bit",
        ("Kenji Ohtsuki", "Zetsubou Shoujo-tachi", "Rap-bit"),
    ),
    ("Mikako Komatsu to Kana Hanazawa", ("Mikako Komatsu", "Kana Hanazawa")),
    ("Masaaki Endoh to Moonriders", ("Masaaki Endoh", "Moonriders")),
    ("Ichiro Mizuki to Tokusatsu", ("Ichiro Mizuki", "Tokusatsu")),
    ("FROGMAN to Red Chili Gasshou-dan", ("FROGMAN", "Red Chili Gasshou-dan")),
    (
        "Yumiko Kobayashi to F-shigi na Nakama-tachi",
        ("Yumiko Kobayashi", "F-shigi na Nakama-tachi"),
    ),
    ("Kanako Miyamoto to Young Fresh", ("Kanako Miyamoto", "Young Fresh")),
    ("Kana Asumi to Sakebu Jigoku-tai", ("Kana Asumi", "Sakebu Jigoku-tai")),
    ("Asuka Nishi to Yukai na Nakama-tachi", ("Asuka Nishi", "Yukai na Nakama-tachi")),
    ("Velvet.kodhy to Velvet.kodhy to μ to μ", ("Velvet.kodhy", "μ")),
    ("Aki Toyosaki to Cocotama Five", ("Aki Toyosaki", "Cocotama Five")),
    ("Junji Majima to Youkai Taiji Sentai", ("Junji Majima", "Youkai Taiji Sentai")),
    ("Hajime Akira to Tsukumo-chan", ("Hajime Akira", "Tsukumo-chan")),
    ("Hyoutei Eternity to Rikkai Young Kan", ("Hyoutei Eternity", "Rikkai Young Kan")),
    (
        "Hyoutei Setsunati to Rikkai Kai Shihan",
        ("Hyoutei Setsunati", "Rikkai Kai Shihan"),
    ),
    ("Junichi Suwabe to Sachiko Nagai", ("Junichi Suwabe", "Sachiko Nagai")),
    ("15-sai to Seiko Oomori", ("15-sai", "Seiko Oomori")),
    ("Azusa Enoki to Yume Bouei Shoujo-tai", ("Azusa Enoki", "Yume Bouei Shoujo-tai")),
    ("Skirt to PUNPEE", ("Skirt", "PUNPEE")),
    # :
    ("SawanoHiroyuki[nZk]:Uru", ("SawanoHiroyuki[nZk]", "Uru")),
    (
        "SawanoHiroyuki[nZk]:Honoka Takahashi",
        ("SawanoHiroyuki[nZk]", "Honoka Takahashi"),
    ),
    ("SawanoHiroyuki[nZk]:Anly", ("SawanoHiroyuki[nZk]", "Anly")),
    ("SawanoHiroyuki[nZk]:LiSA", ("SawanoHiroyuki[nZk]", "LiSA")),
    ("SawanoHiroyuki[nZk]:Jean-Ken Johnny", ("SawanoHiroyuki[nZk]", "Jean-Ken Johnny")),
    ("SawanoHiroyuki[nZk]:Laco", ("SawanoHiroyuki[nZk]", "Laco")),
    ("SawanoHiroyuki[nZk]:ReoNa", ("SawanoHiroyuki[nZk]", "ReoNa")),
    ("SawanoHiroyuki[nZk]:mizuki", ("SawanoHiroyuki[nZk]", "mizuki")),
    ("SawanoHiroyuki[nZk]:Gemie", ("SawanoHiroyuki[nZk]", "Gemie")),
    ("SawanoHiroyuki[nZk]:Yosh", ("SawanoHiroyuki[nZk]", "Yosh")),
    ("SawanoHiroyuki[nZk]:Tielle", ("SawanoHiroyuki[nZk]", "Tielle")),
    ("SawanoHiroyuki[nZk]:naNami", ("SawanoHiroyuki[nZk]", "naNami")),
    ("SawanoHiroyuki[nZk]:Aimer", ("SawanoHiroyuki[nZk]", "Aimer")),
    ("(K)NoW_NAME:Ayaka Tachibana", ("(K)NoW_NAME", "Ayaka Tachibana")),
    (
        "(K)NoW_NAME:Ayaka Tachibana & NIKIIE",
        ("(K)NoW_NAME", "Ayaka Tachibana", "NIKIIE"),
    ),
    ("(K)NoW_NAME:NIKIIE", ("(K)NoW_NAME", "NIKIIE")),
    ("(K)NoW_NAME:AIJ", ("(K)NoW_NAME", "AIJ")),
    ("(K)NoW_NAME:eNu", ("(K)NoW_NAME", "eNu")),
    # other
    (
        "WAGDUG FUTURISTIC UNITY (featuring ULTRA BRAiN",
        ("WAGDUG FUTURISTIC UNITY", "ULTRA BRAiN"),
    ),
    ("Yoko Kanno (feat. Arnór Dan)", ("Yoko Kanno", "Arnór Dan")),
    ("Yoko Kanno (feat. Hanna Berglind)", ("Yoko Kanno", "Hanna Berglind")),
    ("Yoko Kanno (feat. POP ETC)", ("Yoko Kanno", "POP ETC")),
    ("Yoko Kanno (feat. Ryo Nagano)", ("Yoko Kanno", "Ryo Nagano")),
    ("Ogiyahagi produced by Yasushi Akimoto feat. toutou", ("Ogiyahagi", "toutou")),
    ("Nao Touyama & Nozomi Nishida (from Walküre)", ("Nao Touyama", "Nozomi Nishida")),
    ("TOWA TEI WITH UA", ("TOWA TEI", "UA")),
    ("TOWA TEI WITH TAPRIKK SWEEZEE", ("TOWA TEI", "TAPRIKK SWEEZEE")),
    (
        "REAL AKIBA BOYZ loves Kasumi Taguchi & AiRyA from REAL AKIBA BAND",
        ("REAL AKIBA BOYZ", "Kasumi Taguchi", "AiRyA from REAL AKIBA BAND"),
    ),
    ("REAL AKIBA BOYZ loves Shoko Nakagawa", ("REAL AKIBA BOYZ", "Shoko Nakagawa")),
    ("m-flo loves Alex (CLAZZIQUAI PROJECT)", ("m-flo", "Alex (CLAZZIQUAI PROJECT)")),
    ("m-flo loves Adee A.", ("m-flo", "Adee A.")),
    (
        "THE RZA Feat: The Reverend William Burk",
        ("THE RZA", "The Reverend William Burk"),
    ),
    ("Black Knights (feat. P. Dot)", ("Black Knights", "P. Dot")),
    ("DJ TIËSTO FEATURING KIRSTY HAWKSHAW", ("DJ TIËSTO", "KIRSTY HAWKSHAW")),
    (
        "Mica Caldito & mpi & Mika Kobayashi produced by Hiroyuki Sawano",
        ("Mica Caldito", "mpi", "Mika Kobayashi", "Hiroyuki Sawano"),
    ),
    ("mpi Produced by Hiroyuki Sawano", ("mpi", "Hiroyuki Sawano")),
    ("Team.Nekokan [Neko] featuring. atsuko", ("Team.Nekokan [Neko]", "atsuko")),
    ("Team.Nekokan [Neko] featuring. Lia", ("Team.Nekokan [Neko]", "Lia")),
    (
        "Team.Nekokan [Neko] featuring. Junca Amaoto",
        ("Team.Nekokan [Neko]", "Junca Amaoto"),
    ),
    (
        "Team.Nekokan [Neko] featuring. Rekka Katakiri",
        ("Team.Nekokan [Neko]", "Rekka Katakiri"),
    ),
    ("Rinko Maki (with Dynamite You)", ("Rinko Maki", "Dynamite You")),
    (
        "Mitsuko Horie, Mamoru Ichiba, Titine & Children Chorus, Mori no Ki Jidou Gasshou-dan",
        (
            "Mitsuko Horie",
            "Mamoru Ichiba",
            "Titine",
            "Children's Chorus",
            "Mori no Ki Jidou Gasshou-dan",
        ),
    ),
    (
        "Ichiro Mizuki (Columbia Yurikago-kai)",
        ("Ichiro Mizuki", "Columbia Yurikago-kai"),
    ),
    ("Naoya Ogawa☆Mayuko Iwasa", ("Naoya Ogawa", "Mayuko Iwasa")),
    (
        "Precure 5 plus Eri Sendai feat. Cure Quartet",
        ("Precure 5", "Eri Sendai", "Cure Quartet"),
    ),
    ("Yo Hitoto loves Mummy-D", ("Yo Hitoto", "Mummy-D")),
    ("Hiroshi Kitadani With 100 friends", ("Hiroshi Kitadani", "100 friends")),
    ("i-dep feat. Minami Fujioka (PANDA 1/2)", ("i-dep", "Minami Fujioka (PANDA 1/2)")),
    ("Kano to Uzaki-chan", ("Kano", "Uzaki-chan")),
    ("Aya Kamiki w TAKUYA", ("Aya Kamiki", "TAKUYA")),
    ("Toshiki Masuda v.s. Shunsuke Takeuchi", ("Toshiki Masuda", "Shunsuke Takeuchi")),
    (
        "Shunsuke Takeuchi v.s. Tasuku Hatanaka",
        ("Shunsuke Takeuchi", "Tasuku Hatanaka"),
    ),
    ("Konomi Suzuki n' Kiba of Akiba", ("Konomi Suzuki", "Kiba of Akiba")),
    ("FUZI × Neru (feat. Luschka & Panaman)", ("FUZI", "Neru", "Luschka", "Panaman")),
    ("FUZI × Neru (feat. Mas Kimura & MEG)", ("FUZI", "Neru", "Mas Kimura", "MEG")),
    ("Rinko Maki AND Ichiro Mizuki", ("Rinko Maki", "Ichiro Mizuki")),
    ("Big Gadgets ft. Aya Kamiki w TAKUYA", ("Big Gadgets", "Aya Kamiki", "TAKUYA")),
    ("angela Presents/Shoko Nakagawa", ("angela", "Shoko Nakagawa")),
    (
        "Yui Makino Hikiiru Uchuu Shoujo Vanaren-tai",
        ("Yui Makino", "Uchuu Shoujo Vanaren-tai"),
    ),
    (
        "Michiru Aizawa Hikiiru Uchuu Shoujo Vanaren-tai",
        ("Michiru Aizawa", "Uchuu Shoujo Vanaren-tai"),
    ),
    (
        "Momoko Saitou Hikiiru Uchuu Shoujo Vanaren-tai",
        ("Momoko Saitou", "Uchuu Shoujo Vanaren-tai"),
    ),
    (
        "Uchuu Shoujo Vanaren-tai wants Aya Hirano",
        ("Uchuu Shoujo Vanaren-tai", "Aya Hirano"),
    ),
    ("Sukima Switch produced by Tamio Okuda", ("Sukima Switch", "Tamio Okuda")),
    (
        "Hashiguchikanaderiya hugs The Super Ball",
        ("Hashiguchikanaderiya", "The Super Ball"),
    ),
    ("Hammer (Featuring. The Home Boy Chair)", ("Hammer", "The Home Boy Chair")),
    ## Force NOT splitting (exception on splitters)
    # ・
    ("Y・F ZOMBIE COMPANY", ("Y・F ZOMBIE COMPANY",)),
    (
        "B-CLUB\u30fbBAND feat. Hiromi Tsuru, Aya Hisakawa, Yumi Touma, Hinako Kanamaru, Junko Shimakata",
        (
            "B-CLUB・BAND",
            "Hiromi Tsuru",
            "Aya Hisakawa",
            "Yumi Touma",
            "Hinako Kanamaru",
            "Junko Shimakata",
        ),
    ),
    (
        "Mamiko Mizutani With Doku P.E.T.S",
        (
            "Mamiko Mizutani",
            "Doku P.E.T.S",
        ),
    ),
    (
        "Sakura Nogawa & Mamiko Mizutani With Doku P.E.T.S",
        (
            "Sakura Nogawa",
            "Mamiko Mizutani",
            "Doku P.E.T.S",
        ),
    ),
    ("Rieko・Slick", ("Rieko・Slick",)),
    ("m.c.A・T", ("m.c.A・T",)),
    ("Blend・A", ("Blend・A",)),
    ("G・GRIP", ("G・GRIP",)),
    (
        "Yuuko Gotou with S\u30fbA",
        ("Yuuko Gotou", "S・A"),
    ),
    ("Hara・Maki", ("Hara・Maki",)),
    ("R・O・N", ("R・O・N",)),
    ("(K)NoW_NAME:R\u30fbO\u30fbN", ("(K)NoW_NAME", "R・O・N")),
    ("P・H・A-T", ("P・H・A-T",)),
    ("KIX・S", ("KIX・S",)),
    ("PSY・S", ("PSY・S",)),
    ("A・ZU・NA", ("A・ZU・NA",)),
    ("Ham-chans・Himawari-gumi", ("Ham-chans・Himawari-gumi",)),
    ("Swing・Cats", ("Swing・Cats",)),
    ("F・MAP", ("F・MAP",)),
    ("a・chi-a・chi", ("a・chi-a・chi",)),
    ("hide with Spread Beaver", ("hide with Spread Beaver",)),
    ("A・Times", ("A・Times",)),
    ("SAY・S & Nintama Family", ("SAY・S", "Nintama Family")),
    ("SAY・S and Nintama Family", ("SAY・S", "Nintama Family")),
    ("R・O・N", ("R・O・N",)),
    ("(K)NoW_NAME|R・O・N", ("(K)NoW_NAME", "R・O・N")),
    ("B・B Girls", ("B・B Girls",)),
    ("G・P・S", ("G・P・S",)),
    ("M・A・O", ("M・A・O",)),
    ("The s・h・e", ("The s・h・e",)),
    ("The S・h・e", ("The S・h・e",)),
    ("Teikoku Kageki-dan・Hana-gumi", ("Teikoku Kageki-dan・Hana-gumi",)),
    # &
    (
        "80KIDZ & ☆Taku Takahashi with Sagiri Sól",
        ("80KIDZ & ☆Taku Takahashi", "Sagiri Sól"),
    ),
    ("80KIDZ & ☆Taku Takahashi", ("80KIDZ & ☆Taku Takahashi",)),
    (
        "Royal Swedish Opera Chorus and Orchestra",
        ("Royal Swedish Opera Chorus and Orchestra",),
    ),
    ("Gecko&Tokage Parade", ("Gecko&Tokage Parade",)),
    ("Vivi & Chii", ("Vivi & Chii",)),
    ("Song & Dance Kids", ("Song & Dance Kids",)),
    ("R & M PROJECT", ("R & M PROJECT",)),
    ("TAAR & ☆Taku Takahashi", ("TAAR", "☆Taku Takahashi")),
    ("SAK & TAO feat. Azusa Tachibana", ("SAK & TAO", "Azusa Tachibana")),
    ("TAO & SAK", ("TAO & SAK",)),
    ("meia&soya", ("meia&soya",)),
    ("Yoko Kon & Pinky to Killers", ("Yoko Kon & Pinky to Killers",)),
    ("KEEN (C&K)", ("KEEN (C&K)",)),
    ("Giga & TeddyLoid", ("Giga & TeddyLoid",)),
    (
        "Giga & TeddyLoid meets Rina Matsuda & Hikaru Morita (Sakurazaka46)",
        ("Giga & TeddyLoid", "Rina Matsuda", "Hikaru Morita (Sakurazaka46)"),
    ),
    ("IBERIs&", ("IBERIs&",)),
    ("&TEAM", ("&TEAM",)),
    (
        "JUDY GARLAND with Victor Young & his Orchestra",
        (
            "JUDY GARLAND",
            "Victor Young & his Orchestra",
        ),
    ),
    ("Noriyuki Asakura & GANG", ("Noriyuki Asakura & GANG",)),
    (
        "Toshiyuki Toyonaga, Yuka Kamebuchi & THE VOICE OF JAPAN",
        ("Toshiyuki Toyonaga", "Yuka Kamebuchi & THE VOICE OF JAPAN"),
    ),
    (
        "Mai Kuraki feat. Mika Arisaka & The Sunshowers",
        ("Mai Kuraki", "Mika Arisaka & The Sunshowers"),
    ),
    (
        "TBH / Chiaro & Scuro VS Division Leaders",
        ("TBH", "Chiaro & Scuro", "Division Leaders"),
    ),
    ("T/N", ("T/N",)),
    ("MAYUKO & Luminous", ("MAYUKO & Luminous",)),
    ("Benjamin & mpi", ("Benjamin & mpi",)),
    ("Benjamin & mpi, Laco", ("Benjamin & mpi", "Laco")),
    ("Hiroyuki Sawano feat. Benjamin & mpi", ("Hiroyuki Sawano", "Benjamin & mpi")),
    ("Laugh & Peace", ("Laugh & Peace",)),
    ("Beom&Nang", ("Beom&Nang",)),
    ("K&K Factory", ("K&K Factory",)),
    ("Shin&Kei", ("Shin&Kei",)),
    ("Coach & Sendo", ("Coach", "Sendo")),
    (
        "Coach & Sendo , Katerina Bramley , Kim Tesung",
        ("Coach & Sendo", "Katerina Bramley", "Kim Tesung"),
    ),
    (
        "Coach & Sendo , Kyler Niko , Obi Mhondera",
        ("Coach & Sendo", "Kyler Niko", "Obi Mhondera"),
    ),
    ("Teddy & Melvin", ("Teddy", "Melvin")),
    (
        "Wasei Geronimo & Love Guerrilla Experience",
        ("Wasei Geronimo & Love Guerrilla Experience",),
    ),
    (
        "Wasei Geronimo & Love Guerrilla Experience & Ryumi Moritoki",
        ("Wasei Geronimo & Love Guerrilla Experience", "Ryumi Moritoki"),
    ),
    ("LOVE+HATE", ("LOVE+HATE",)),
    ("WILD&DELICATES", ("WILD&DELICATES",)),
    ("Cut&Past", ("Cut&Past",)),
    ("Chie & Mar-kun", ("Chie & Mar-kun",)),
    (
        "Penalty Kick Oldies with Kenji♂Spark Kawai",
        ("Penalty Kick Oldies with Kenji♂Spark Kawai",),
    ),
    ("EYE&SHOKO", ("EYE&SHOKO",)),
    ("YVES&ADAMS", ("YVES&ADAMS",)),
    ("Schtein&Longer", ("Schtein&Longer",)),
    ("Beat Mario (COOL&CREATE)", ("Beat Mario (COOL&CREATE)",)),
    ("Macaroni&Cheese", ("Macaroni&Cheese",)),
    ("D&H", ("D&H",)),
    ("ALI&", ("ALI&",)),
    ("H & H", ("H & H",)),
    ("T&J COOL", ("T&J COOL",)),
    ("SHINSUKE & BUS GAS BAKUHATSU GAKUDAN", ("SHINSUKE & BUS GAS BAKUHATSU GAKUDAN",)),
    (
        "Yumemi Kujira feat. Mimizuku & Fukurou",
        (
            "Yumemi Kujira",
            "Mimizuku & Fukurou",
        ),
    ),
    (
        "Warsaw Philharmonic Orchestra & Choir",
        ("Warsaw Philharmonic Orchestra & Choir",),
    ),
    ("UCARY & THE VALENTINE", ("UCARY & THE VALENTINE",)),
    (
        "Mina Kubota feat. MIYUU & MASUMI (Mistera Feo)",
        ("Mina Kubota", "MIYUU (Mistera Feo)", "MASUMI (Mistera Feo)"),
    ),
    ("765PRO&876PRO ALLSTARS", ("765PRO ALLSTARS", "876PRO ALLSTARS")),
    (
        "Orie Kimoto & Atsuko Enomoto with Flappy & Choppy's",
        ("Orie Kimoto", "Atsuko Enomoto", "Flappy & Choppy's"),
    ),
    ("Mayumi Gojou with Flappy & Choppy's", ("Mayumi Gojou", "Flappy & Choppy's")),
    ("sisters M.K. & K.U.", ("sisters M.K. & K.U.",)),
    ("Hamatora -Nice & Murasaki-", ("Hamatora -Nice & Murasaki-",)),
    ("Shoukichi Kina & Champloose", ("Shoukichi Kina & Champloose",)),
    ("Flappy & Choppy's", ("Flappy & Choppy's",)),
    ("Sachi & Juri", ("Sachi & Juri",)),
    ("Amane + Beat Mario (COOL&CREATE)", ("Amane", "Beat Mario (COOL&CREATE)")),
    ("Zinee&issei", ("Zinee&issei",)),
    ("Hironobu Kageyama & BROADWAY", ("Hironobu Kageyama & BROADWAY",)),
    (
        "Kishida Kyoudan &THE Akeboshi Rockets",
        ("Kishida Kyoudan &THE Akeboshi Rockets",),
    ),
    ("HIKAKIN & SEIKIN", ("HIKAKIN & SEIKIN",)),
    ("HIKAKIN & SEIKIN with Mayumi Tanaka", ("HIKAKIN & SEIKIN", "Mayumi Tanaka")),
    ("Athena & Robikerottsu", ("Athena & Robikerottsu",)),
    ("QUANGO & SPARKY", ("QUANGO & SPARKY",)),
    ("TAKAO & THE VIEW", ("TAKAO & THE VIEW",)),
    ("KING & QUEEN", ("KING & QUEEN",)),
    ("C&K", ("C&K",)),
    ("P&P", ("P&P",)),
    ("P4 with T", ("P4 with T",)),
    ("MAYA & Z", ("MAYA & Z",)),
    ("Icchy & Naru", ("Icchy & Naru",)),
    ("Licca & Noa", ("Licca", "Noa")),
    (
        'SOIL&"PIMP"SESSIONS feat. Maaya Sakamoto',
        ('SOIL&"PIMP"SESSIONS', "Maaya Sakamoto"),
    ),
    ('SOIL&"PIMP"SESSIONS', ('SOIL&"PIMP"SESSIONS',)),
    ("Kaako & Papa", ("Kaako & Papa",)),
    ("Adiamond -Amy & Bibian-", ("Adiamond -Amy & Bibian-",)),
    ("Bars & Melody", ("Bars & Melody",)),
    ("Mon & Ster", ("Mon & Ster",)),
    ("MYTH & ROID", ("MYTH & ROID",)),
    (
        "MYTH & ROID feat. TK (Ling Tosite Sigure)",
        ("MYTH & ROID", "TK (Ling Tosite Sigure)"),
    ),
    ("Kakki & Ash Potato", ("Kakki & Ash Potato",)),
    ("Anamu & Maki", ("Anamu & Maki",)),
    ("SUEMITSU & THE SUEMITH", ("SUEMITSU & THE SUEMITH",)),
    ("SUEMITSU & THE NODAME ORCHESTRA", ("SUEMITSU & THE NODAME ORCHESTRA",)),
    ("TAKAKO&THE CRAZY BOYS", ("TAKAKO&THE CRAZY BOYS",)),
    ("Takako Shirai&CRAZY BOYS", ("Takako Shirai&CRAZY BOYS",)),
    ("Oosugi & Hiiko", ("Oosugi & Hiiko",)),
    ("Christy&Clinton", ("Christy&Clinton",)),
    ("Irene & Erika", ("Irene & Erika",)),
    ("Dylan & Catherine", ("Dylan & Catherine",)),
    ("Junichi&JJr", ("Junichi&JJr",)),
    ("Bread & Butter", ("Bread & Butter",)),
    ("Betsy & Chris", ("Betsy & Chris",)),
    ("RUN&GUN", ("RUN&GUN",)),
    ("Rats & Star", ("Rats & Star",)),
    ("Aki & Isao", ("Aki & Isao",)),
    ("Let's Go BOYS & GIRLS", ("Let's Go BOYS & GIRLS",)),
    ("TOSS & TURN", ("TOSS & TURN",)),
    ("CHAGE&ASKA", ("CHAGE&ASKA",)),
    ("Earth, Wind & Fire", ("Earth, Wind & Fire",)),
    ("Oranges & Lemons", ("Oranges & Lemons",)),
    ("Rough & Ready", ("Rough & Ready",)),
    ("Jack & Betty", ("Jack & Betty",)),
    ("Tackey & Tsubasa", ("Tackey & Tsubasa",)),
    ("AKIMA & NEOS", ("AKIMA & NEOS",)),
    ("Duel Hero Yuu & Atsuto", ("Duel Hero Yuu & Atsuto",)),
    ("You & Explosion Band", ("You & Explosion Band",)),
    ("2&", ("2&",)),
    ("Yumachi & Aina", ("Yumachi & Aina",)),
    (
        "Wasei Geronimo & Love Guerrilla Experience",
        ("Wasei Geronimo & Love Guerrilla Experience",),
    ),
    # and
    ("Pen and Pencil", ("Pen and Pencil",)),
    (
        "Jimmy Joyce and his Children's Chorus",
        ("Jimmy Joyce and his Children's Chorus",),
    ),
    ("Jimmy Jam and Terry Lewis", ("Jimmy Jam and Terry Lewis",)),
    ("Junko Hori and New Royal", ("Junko Hori and New Royal",)),
    ("Tetsu and Tomo", ("Tetsu and Tomo",)),
    ("HIGH and MIGHTY COLOR", ("HIGH and MIGHTY COLOR",)),
    ("Big Sofa and the Lazy Boys", ("Big Sofa and the Lazy Boys",)),
    ("devils and realist", ("devils and realist",)),
    ("Lillies and Remains", ("Lillies and Remains",)),
    ("Bird Bear Hare and Fish", ("Bird Bear Hare and Fish",)),
    (
        "Takanori Nishikawa × Fear, and Loathing in Las Vegas",
        (
            "Takanori Nishikawa",
            "Fear, and Loathing in Las Vegas",
        ),
    ),
    ("Tim Timebomb and the Interrupters", ("Tim Timebomb and the Interrupters",)),
    ("Yuusuke (ex. HIGH and MIGHTY COLOR)", ("Yuusuke (ex. HIGH and MIGHTY COLOR)",)),
    # x
    ("R×R", ("R×R",)),
    ("Shin Kawasaki (Kari)×beni-shouga", ("Shin Kawasaki (Kari)×beni-shouga",)),
    ("YABI\u00d7YABI", ("YABI\u00d7YABI",)),
    ("Chun×4", ("Chun×4",)),
    ("OxT", ("OxT",)),
    ("Clover×Clover", ("Clover×Clover",)),
    ("LIP×LIP", ("LIP×LIP",)),
    ("Gothic×Luck", ("Gothic×Luck",)),
    ("High×Joker", ("High×Joker",)),
    ("salyu×salyu", ("salyu×salyu",)),
    ("Daisy×Daisy", ("Daisy×Daisy",)),
    ("SKET×Sketch", ("SKET×Sketch",)),
    ("kanon×kanon", ("kanon×kanon",)),
    ("DIVA×DIVA", ("DIVA×DIVA",)),
    ("sister×sisters", ("sister×sisters",)),
    ("nana×nana", ("nana×nana",)),
    ("U×Mishi", ("U×Mishi",)),
    # with
    ("Seiko Shiga with Octopus 8", ("Seiko Shiga with Octopus 8",)),
    ("Babbit with Kodocha-tai", ("Babbit with Kodocha-tai",)),
    ("NyaaKB with Tsuchinoko Panda", ("NyaaKB with Tsuchinoko Panda",)),
    ('Takumi Nakayama with "R"', ('Takumi Nakayama with "R"',)),
    ("YOURI with the CASH", ("YOURI with the CASH",)),
    ("KYAN MARIE with MEDUSA", ("KYAN MARIE with MEDUSA",)),
    ("Aoi Yuuki with Starfield", ("Aoi Yuuki with Starfield",)),
    ("yuyu with eriri", ("yuyu with eriri",)),
    ("Petit Rabbit's with beans", ("Petit Rabbit's with beans",)),
    ("Serenon with K", ("Serenon with K",)),
    ("Cotori with Stitchbird", ("Cotori with Stitchbird",)),
    ("Akebonoyama Chuugaku Band with T", ("Akebonoyama Chuugaku Band with T",)),
    (
        "Yuji Ohno & Lupintic Six with Friends feat. Miyuki Sawashiro",
        ("Yuji Ohno & Lupintic Six with Friends", "Miyuki Sawashiro"),
    ),
    (
        "Yuji Ohno & Lupintic Six with Friends feat. Lyn Inaizumi",
        ("Yuji Ohno & Lupintic Six with Friends", "Lyn Inaizumi"),
    ),
    (
        "Yuji Ohno & Lupintic Six with Friends feat. Sakura Fujiwara",
        ("Yuji Ohno & Lupintic Six with Friends", "Sakura Fujiwara"),
    ),
    (
        "Yuji Ohno & Lupintic Six with Friends feat. Shigeru Matsuzaki",
        ("Yuji Ohno & Lupintic Six with Friends", "Shigeru Matsuzaki"),
    ),
    (
        "Yuji Ohno & Lupintic Six with Friends",
        ("Yuji Ohno & Lupintic Six with Friends"),
    ),
    (
        "Yuji Ohno & Lupintic Six with Friends feat. Akari Dritschler",
        ("Yuji Ohno & Lupintic Six with Friends", "Akari Dritschler"),
    ),
    (
        "Yuji Ohno & Lupintic Five with Friends Featuring Yoshie Nakano (EGO-WRAPPIN')",
        ("Yuji Ohno & Lupintic Five with Friends", "Yoshie Nakano (EGO-WRAPPIN')"),
    ),
    (
        "Yuji Ohno & Lupintic Five with Friends Feat. DOUBLE",
        ("Yuji Ohno & Lupintic Five with Friends", "DOUBLE"),
    ),
    # ,
    ("Cantores Oratorio Choir, Bruges", ("Cantores Oratorio Choir, Bruges",)),
    ("Maurice Samples, Jr.", ("Maurice Samples, Jr.",)),
    ("Sakurakou 3-2, Sakurakou 2-1", ("Sakurakou 3-2, Sakurakou 2-1",)),
    ("RAY PARKER,JR.", ("RAY PARKER,JR.",)),
    ("TA,COOL", ("TA,COOL",)),
    ("Pete Mac, Jr.", ("Pete Mac, Jr.",)),
    ("Nora from Konya, anomachikara", ("Nora from Konya, anomachikara",)),
    ("CHA, HO-SOK & MIKI", ("CHA, HO-SOK", "MIKI")),
    (
        "Kiyoshiro Imawano, Johnny, Louis & Char",
        ("Kiyoshiro Imawano", "Johnny, Louis & Char"),
    ),
    ("Fear, and Loathing in Las Vegas", ("Fear, and Loathing in Las Vegas",)),
    ("RAISE A SUILEN×Hello, Happy World!", ("RAISE A SUILEN", "Hello, Happy World!")),
    ("Hello, Happy World!", ("Hello, Happy World!",)),
    ("Mix Speaker's,Inc.", ("Mix Speaker's,Inc.",)),
    ("Kamisama, Boku wa Kizuite Shimatta", ("Kamisama, Boku wa Kizuite Shimatta",)),
    ("New man Co.,Ltd.", ("New man Co.,Ltd.",)),
    ("Okino, Shuntaro", ("Okino, Shuntaro",)),
    ("OKINO,SHUNTARO", ("OKINO,SHUNTARO",)),
    ("Run Girls, Run!", ("Run Girls, Run!",)),
    ("Wake Up, Girls!", ("Wake Up, Girls!",)),
    ("Wake Up, May'n!", ("Wake Up, May'n!",)),
    ("Kagrra,", ("Kagrra,",)),
    # +
    ("Aiobahn +81", ("Aiobahn +81",)),
    ("t+pazolite", ("t+pazolite",)),
    ('Hiroshi Kakizaki + "r" Project', ('Hiroshi Kakizaki + "r" Project',)),
    ("Helios+trope", ("Helios+trope",)),
    ("ma2k from roughsketch+", ("ma2k from roughsketch+",)),
    ("405+D", ("405+D",)),
    ("encounter+", ("encounter+",)),
    ("encounter+ & yamazo", ("encounter+", "yamazo")),
    ("+d", ("+d",)),
    ("GAK , Tatsuya Kida , +d", ("GAK", "Tatsuya Kida", "+d")),
    ("+d & Yumeto Tsurusawa", ("+d", "Yumeto Tsurusawa")),
    (
        "Gokujou Seitokai Yuugeki-bu+Sharyou-bu",
        ("Gokujou Seitokai Yuugeki-bu+Sharyou-bu",),
    ),
    ("Fuji Misaki+", ("Fuji Misaki+",)),
    ("EIKO+ERIKO", ("EIKO+ERIKO",)),
    ("Kaede+Cheek Fairy", ("Kaede+Cheek Fairy",)),
    ("Sister Princess +1", ("Sister Princess +1",)),
    ("nobodyknows+", ("nobodyknows+",)),
    ("Re+sa", ("Re+sa",)),
    ("+Plus", ("+Plus",)),
    ("T-Pistonz+KMC", ("T-Pistonz+KMC",)),
    ("Alchemy+", ("Alchemy+",)),
    ("stella quintet+", ("stella quintet+",)),
    ("YU+KI", ("YU+KI",)),
    ("Needless★Girls+", ("Needless★Girls+",)),
    ("Yonagahime 3+1", ("Yonagahime 3+1",)),
    ("ASAHINA Bros.+JULI", ("ASAHINA Bros.+JULI",)),
    ("Q;indivi+", ("Q;indivi+",)),
    ("+α/Alfakyun.", ("+α/Alfakyun.",)),
    ("sabio/Futa Takamura", ("sabio/Futa Takamura",)),
    ("MON/KU", ("MON/KU",)),
    ("F/ACE", ("F/ACE",)),
    ("+earth☆sky feat. ayaka morikawa", ("+earth☆sky", "ayaka morikawa")),
    ("SUMMONERS 2+", ("SUMMONERS 2+",)),
    ("DIALOGUE+", ("DIALOGUE+",)),
    ("sophie+", ("sophie+",)),
    ("Megami-ryousei+α", ("Megami-ryousei+α",)),
    # other
    ("SSGIRLS feat. Mikako Komatsu", ("SSGIRLS feat. Mikako Komatsu",)),
    ("DWB feat. NIRGILIS", ("DWB feat. NIRGILIS",)),
    ("DWB feat. fade", ("DWB feat. fade",)),
    ("AUO feat. MORISAKI WIN", ("AUO feat. MORISAKI WIN",)),
    ("THE CUPIDS by CHAR & ANN LEWIS", ("THE CUPIDS by CHAR & ANN LEWIS",)),
    ("KEY with Mohican Brothers", ("KEY with Mohican Brothers",)),
    ("Dale & Julie Ember with The Flames", ("Dale & Julie Ember with The Flames",)),
    ("Saima Nakano of e/g", ("Saima Nakano of e/g",)),
    ("Rock, Pebble & Stones", ("Rock, Pebble & Stones",)),
    ("Konya, anomachikara starring VALSHE", ("Konya, anomachikara", "VALSHE")),
    ("EE JUMP featuring Sonin", ("EE JUMP featuring Sonin",)),
    ("JAXX/JAXX", ("JAXX/JAXX",)),
    ("Shou/Ouji", ("Shou/Ouji",)),
    ("NAMI with Shige×2＆S/N", ("NAMI", "Shige×2", "S/N")),
    ("r.o.r/s", ("r.o.r/s",)),
    ("konoco from kyoukaimetro/Qlover", ("konoco from kyoukaimetro/Qlover",)),
    ("kyoukaimetro/Qlover", ("kyoukaimetro/Qlover",)),
    ("can/goo", ("can/goo",)),
    ("Koichirou Tokinori & can/goo", ("Koichirou Tokinori", "can/goo")),
    ("DISH//", ("DISH//",)),
    ("ON/OFF", ("ON/OFF",)),
    ("S/mileage", ("S/mileage",)),
    (r"Konnichiwa\(^o^)/Kirarinbo☆Harry!!!", (r"Konnichiwa\(^o^)/Kirarinbo☆Harry!!!",)),
    ("Sol/Lull BOB", ("Sol/Lull BOB",)),
    ("Kisu Koide (PANDA 1/2)", ("Kisu Koide (PANDA 1/2)",)),
    ("H-el-ical//", ("H-el-ical//",)),
    ("PIOTR MACIEJEWSKI / DRIVEALONE", ("PIOTR MACIEJEWSKI / DRIVEALONE")),
    (
        "David Wilson, Soma Genda, Kyle Reith, Elijah Noll, Tony Ferrari, Jamesy Minimal, BYDOR ARCHIVE, Jacob Critch, Ryan Shin(153/Joombas), Wyatt Sanders, Horace Dodd",
        (
            "David Wilson",
            "Soma Genda",
            "Kyle Reith",
            "Elijah Noll",
            "Tony Ferrari",
            "Jamesy Minimal",
            "BYDOR ARCHIVE",
            "Jacob Critch",
            "Ryan Shin(153/Joombas)",
            "Wyatt Sanders",
            "Horace Dodd",
        ),
    ),
    ("22/7", ("22/7",)),
    ("Yukichi Kasaku/men", ("Yukichi Kasaku/men",)),
    ("Prhythm/epx", ("Prhythm/epx",)),
    ("HoneyWorks meets YURiCa/Hanatan", ("YURiCa/Hanatan")),
    ("Bach/Gounod", ("Johann Sebastian Bach", "Charles Gounod")),
    ("m-flo\u2665DOPING PANDA", ("m-flo", "DOPING PANDA")),
    ## removing longer strings (removing longer string to avoid having dumb artists names)
    ("Karen GUY's Yuuichi Nakamura & Kishou Taniyama", ("Karen GUY's",)),
    ("Karen GUY's Kouji Yusa & Junichi Suwabe", ("Karen GUY's",)),
    ("Chihiro Yonekura (With Kaleido Stars)", ("Chihiro Yonekura", "Kaleido Stars")),
    ("Kevin Penkin (ft. Elspeth Bawden)", ("Kevin Penkin", "Elspeth Bawden")),
    ("livetune adding Fukase(from SEKAI NO OWARI)", ("livetune", "Fukase")),
    ("livetune adding Rin Oikawa (from Q;indivi)", ("livetune", "Rin Oikawa")),
    ("Tamiya Terashima (Rentrak Japan)", ("Tamiya Terashima",)),
    ("GENERATIONS from EXILE TRIBE", ("GENERATIONS from EXILE TRIBE",)),
    ("THE RAMPAGE from EXILE TRIBE", ("THE RAMPAGE",)),
    ("FANTASTICS from EXILE TRIBE", ("FANTASTICS",)),
    (
        "Sandaime J SOUL BROTHERS from EXILE TRIBE",
        ("Sandaime J SOUL BROTHERS from EXILE TRIBE",),
    ),
    ("Aya & chika from D&D", ("Aya Uehara", "Chikano Higa")),
    (
        "SawanoHiroyuki[nZk]:Junki Kono & Sho Yonashiro (JO1)",
        ("SawanoHiroyuki[nZk]", "Junki Kono", "Sho Yonashiro"),
    ),
    (
        "SawanoHiroyuki[nZk]:TOMORROW X TOGETHER",
        ("SawanoHiroyuki[nZk]", "TOMORROW X TOGETHER"),
    ),
    ("SawanoHiroyuki[nZk]:Rei", ("SawanoHiroyuki[nZk]", "Rei")),
    ("SawanoHiroyuki[nZk]:Motohiro Hata", ("SawanoHiroyuki[nZk]", "Motohiro Hata")),
    ("SawanoHiroyuki[nZk]:Akihito Okano", ("SawanoHiroyuki[nZk]", "Akihito Okano")),
    ("SawanoHiroyuki[nZk]:XAI", ("SawanoHiroyuki[nZk]", "XAI")),
    ("POLYSICS with Seiya Yamasaki (Kyuuso Nekokami)", ("POLYSICS", "Seiya Yamasaki")),
    ("JO\u2606STARS~TOMMY,Coda,JIN~", ("JO\u2606STARS~TOMMY,Coda,JIN~",)),
    ("Saori Hayami (from Eclipse)", ("Saori Hayami",)),
    ("Megumi Nakajima (from Eclipse)", ("Megumi Nakajima",)),
    ("Haruka Tomatsu (from Eclipse)", ("Haruka Tomatsu",)),
    ("AKINO&AIKI from bless4", ("AKINO", "AIKI")),
    ("AKINO from bless4", ("AKINO",)),
    ("AIKI from bless4", ("AIKI",)),
    ("AKINO arai×AKINO from bless4", ("AKINO arai", "AKINO")),
    ("AIKI & AKINO from bless4", ("AIKI", "AKINO")),
    ("Yuuki Ozaki(from Galileo Galilei)", ("Yuuki Ozaki",)),
    (
        "Kotaro Oshio with Yuuki Ozaki (from Galileo Galilei)",
        ("Kotaro Oshio", "Yuuki Ozaki"),
    ),
    ("Aya Hirano from Springs", ("Aya Hirano",)),
    (
        "Yuki Kaji, Kishou Taniyama, Yui Ishikawa from attackers",
        ("Yuki Kaji", "Kishou Taniyama", "Yui Ishikawa"),
    ),
    ("Hiroshi Kamiya from No Name", ("Hiroshi Kamiya",)),
    ("Jin ft. MARiA from GARNiDELiA", ("Jin", "MARiA")),
    ("Shinya & Tarantula (From Hi-Timez)", ("Shinya", "Tarantula")),
    ("Argonavis feat. Jin Ogasawara from GYROAXIA", ("Argonavis", "Jin Ogasawara")),
    ("Misaki Kurea from Girls²", ("Misaki Kurea",)),
    (
        "livetune adding Takuro Sugawara (from 9mm Parabellum Bullet)",
        ("livetune", "Takuro Sugawara (from 9mm Parabellum Bullet)"),
    ),
    ("Anna (BON-BON BLANCO)", ("Anna",)),
    ("Jin ft. Takumi Yoshida (phatmans after school)", ("Jin", "Takumi Yoshida")),
    ("Shifo from UNIVERS\u2605L D", ("Shifo",)),
    ("HARU & SAYAKA from UNIVERS★L D", ("HARU", "SAYAKA")),
    ("UL-SAYS [from T.P.D]", ("UL-SAYS",)),
    ("BACK-ON & Lil' Fang (from FAKY)", ("BACK-ON", "Lil' Fang")),
    ("Ai Orikasa to Jankenman Chorus-tai", ("Ai Orikasa", "Jankenman Chorus-tai")),
    ("Daiki Nakamura to The King Stars", ("Daiki Nakamura", "The King Stars")),
    (
        "Charisma.com to RYO-Z Onii-san (RIP SLYME)",
        ("Charisma.com", "RYO-Z Onii-san (RIP SLYME)"),
    ),
    (
        "Naoki Sagawa featuring JOE (Psychic Lover)",
        ("Naoki Sagawa", "JOE (Psychic Lover)"),
    ),
    (
        "Jin ft. Kouta Matsuyama (BYEE the ROUND)",
        ("Jin", "Kouta Matsuyama (BYEE the ROUND)"),
    ),
    (
        "Jin ft. Shouichi Taguchi (Kanshou Vector)",
        ("Jin", "Shouichi Taguchi (Kanshou Vector)"),
    ),
    ("Aztech from Hybrid Thoughts", ("Aztech",)),
    ("Aztech, Paranom & Kasper from Hybrid Thoughts", ("Aztech", "Paranom", "Kasper")),
    ("Demon Kakka×Arika Takarano (ALI PROJECT)", ("Demon Kakka", "Arika Takarano")),
    ("Takayuki Hattori Presents GUNDAM THE ORIGIN", ("Takayuki Hattori",)),
    ("Motohiro Hata meets Sakamichi no Apollon", ("Motohiro Hata",)),
    ("Tortoise Matsumoto (Ulfuls)", ("Tortoise Matsumoto",)),
    ("Yasutaka Nakata (CAPSULE)", ("Yasutaka Nakata",)),
    (
        "GHOST ORACLE DRIVE feat. Cento Chihiro Chittiii (BiSH)",
        ("GHOST ORACLE DRIVE", "Cento Chihiro Chittiii (BiSH)"),
    ),
    ("Risa Aizawa (Dempagumi.inc)", ("Risa Aizawa",)),
    ("KinKi Kids (Koichi Domoto)", ("KinKi Kids",)),
    ("KinKi Kids (Tsuyoshi Domoto)", ("KinKi Kids",)),
    ("Q-MHz feat. Mitsuhiro Hidaka a.k.a. SKY-HI", ("Q-MHz", "SKY-HI")),
    ("aki a.k.a Aki Deguchi", ("aki",)),
    ("ELISA connect EFP", ("ELISA",)),
    (
        "Kuricorder Quartet feat. Sou Matsumoto (GOING UNDER GROUND)",
        ("Kuricorder Quartet", "Sou Matsumoto"),
    ),
    ("Yumi Yoshimura (PUFFY)", ("Yumi Yoshimura",)),
    ("Ami Onuki (PUFFY)", ("Ami Onuki",)),
    ("ichigo from Kishida Kyoudan &THE Akeboshi Rockets", ("ichigo",)),
    ## Reformatting of the string (reformate the string by adding or removing some part to have better artists name)
    (
        "Kazuya Akiho・Kouji Akiho (from Carrot Club)",
        ("Kazuya Akiho (from Carrot Club)", "Kouji Akiho (from Carrot Club)"),
    ),
    ("HENTAI SHINSHI CLUB (feat. kojikoji)", ("HENTAI SHINSHI CLUB", "kojikoji")),
    ("yama (feat. Nakimushi)", ("yama", "Nakimushi")),
    (
        "Tenshou Gakuen Seito・Kyoushi Ichidou",
        ("Tenshou Gakuen Seito Ichidou", "Tenshou Gakuen Kyoushi Ichidou"),
    ),
    ("ReyMagtoto-NonoyTan", ("RAY MAGTOTO", "NONOY TAN")),
    ("Masayoshi Ooishi (feat.Riria.)", ("Masayoshi Ooishi", "Riria.")),
    ("Basement Jaxx (feat. Lisa Kekaula)", ("Basement Jaxx", "Lisa Kekaula")),
    ("Moe Shop (feat.TORIENA)", ("Moe Shop", "TORIENA")),
    (
        "Pokemon Kids & Unsho Ishizuka (+Ikue Ootani)",
        ("Pokemon Kids", "Unsho Ishizuka", "Ikue Ootani"),
    ),
    ("Pokemon Kids (+Ikue Ootani)", ("Pokemon Kids", "Ikue Ootani")),
    (
        "HoneyWorks meets Sayuringo Gundan + Manatsu-san Respect Gundan from Nogizaka46",
        ("Sayuringo Gundan", "Manatsu-san Respect Gundan"),
    ),
    ("G-Eazy (featuring Bente Violet McPherson)", ("G-Eazy", "Bente Violet McPherson")),
    ("Masayoshi Ooishi (feat. Yukari Tamura)", ("Masayoshi Ooishi", "Yukari Tamura")),
    (
        "Masayoshi Ooishi (feat. Hiroki Yasumoto)",
        ("Masayoshi Ooishi", "Hiroki Yasumoto"),
    ),
    (
        "M. Charlton-C. Cecchetto / M. Bonsanto-R. Rossi",
        ("Malcolm Charlton", "Claudio Cecchetto", "Matteo Bonsanto", "Roberto Rossi"),
    ),
    ("Kevin Penkin [feat. Emi Evans]", ("Kevin Penkin", "Emi Evans")),
    (
        "Shirahamazaka Koukou Gasshou-bu & Seigaku-bu",
        ("Shirahamazaka Koukou Gasshou-bu", "Shirahamazaka Koukou Seigaku-bu"),
    ),
    (
        "Ndaho & Peketan from Fischer's",
        ("Ndaho from Fischer's", "Peketan from Fischer's"),
    ),
    # Aikatsu
    (
        "Mirai\u30fbAine from BEST FRIENDS!",
        ("Mirai from BEST FRIENDS!", "Aine from BEST FRIENDS!"),
    ),
    (
        "Waka・Fuuri・Sunao・Risuko from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao from STAR☆ANIS",
        ("Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS", "Sunao from STAR☆ANIS"),
    ),
    (
        "Waka・Fuuri・Sunao・Remi・Moe・Eri・Yuna・Risuko from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    ("Waka・Remi from STAR☆ANIS", ("Waka from STAR☆ANIS", "Remi from STAR☆ANIS")),
    (
        "Waka・Fuuri・Sunao・Remi・Moe from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao・Remi・Moe・Eri・Risuko from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    ("Waka・Moe from STAR☆ANIS", ("Waka from STAR☆ANIS", "Moe from STAR☆ANIS")),
    ("Waka from STAR☆ANIS", ("Waka from STAR☆ANIS",)),
    ("Remi from STAR☆ANIS", ("Remi from STAR☆ANIS",)),
    ("Risuko from STAR☆ANIS", ("Risuko from STAR☆ANIS",)),
    ("Risuko・Waka from STAR☆ANIS", ("Risuko from STAR☆ANIS", "Waka from STAR☆ANIS")),
    ("Eri from STAR☆ANIS", ("Eri from STAR☆ANIS",)),
    ("Fuuri from STAR☆ANIS", ("Fuuri from STAR☆ANIS",)),
    (
        "Risuko・Moe・Yuna from STAR☆ANIS",
        ("Risuko from STAR☆ANIS", "Moe from STAR☆ANIS", "Yuna from STAR☆ANIS"),
    ),
    ("Sunao・Risuko from STAR☆ANIS", ("Sunao from STAR☆ANIS", "Risuko from STAR☆ANIS")),
    (
        "Sunao・Waka・Fuuri from STAR☆ANIS",
        ("Sunao from STAR☆ANIS", "Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS"),
    ),
    ("Waka・Fuuri from STAR☆ANIS", ("Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS")),
    ("Sunao from STAR☆ANIS", ("Sunao from STAR☆ANIS",)),
    ("Waka・Risuko from STAR☆ANIS", ("Waka from STAR☆ANIS", "Risuko from STAR☆ANIS")),
    ("Sunao・Yuniko from STAR☆ANIS", ("Sunao from STAR☆ANIS", "Yuniko from STAR☆ANIS")),
    (
        "Waka・Fuuri・Sunao・Remi・Moe・Eri from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Moe from STAR☆ANIS",
            "Eri from STAR☆ANIS",
        ),
    ),
    ("Moe from STAR☆ANIS", ("Moe from STAR☆ANIS",)),
    (
        "Waka・Fuuri・Sunao・Yuna from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
        ),
    ),
    (
        "Risuko・Sunao・Yuna from STAR☆ANIS",
        ("Risuko from STAR☆ANIS", "Sunao from STAR☆ANIS", "Yuna from STAR☆ANIS"),
    ),
    ("Waka・Sunao from STAR☆ANIS", ("Waka from STAR☆ANIS", "Sunao from STAR☆ANIS")),
    (
        "Waka・Fuuri・Yuna from STAR☆ANIS",
        ("Waka from STAR☆ANIS", "Fuuri from STAR☆ANIS", "Yuna from STAR☆ANIS"),
    ),
    (
        "Risuko・Waka・Fuuri・Mona from STAR☆ANIS",
        (
            "Risuko from STAR☆ANIS",
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Mona from STAR☆ANIS",
        ),
    ),
    ("Eri・Waka from STAR☆ANIS", ("Eri from STAR☆ANIS", "Waka from STAR☆ANIS")),
    ("Yuna from STAR☆ANIS", ("Yuna from STAR☆ANIS",)),
    ("Risuko・Mona from STAR☆ANIS", ("Risuko from STAR☆ANIS", "Mona from STAR☆ANIS")),
    (
        "Fuuri・Yuna・Sunao・Eri from STAR☆ANIS",
        (
            "Fuuri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Eri from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao・Remi from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Remi from STAR☆ANIS",
        ),
    ),
    ("Ruka from STAR☆ANIS", ("Ruka from STAR☆ANIS",)),
    ("Waka・Ruka from STAR☆ANIS", ("Waka from STAR☆ANIS", "Ruka from STAR☆ANIS")),
    ("Mona from STAR☆ANIS", ("Mona from STAR☆ANIS",)),
    (
        "Waka・Fuuri・Yuna・Ruka from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Ruka from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Remi・Risuko・Mona・Fuuri・Eri from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
            "Mona from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Eri from STAR☆ANIS",
        ),
    ),
    ("Fuuri・Waka from STAR☆ANIS", ("Fuuri from STAR☆ANIS", "Waka from STAR☆ANIS")),
    ("Yuna・Remi from STAR☆ANIS", ("Yuna from STAR☆ANIS", "Remi from STAR☆ANIS")),
    ("Remi・Eri from STAR☆ANIS", ("Remi from STAR☆ANIS", "Eri from STAR☆ANIS")),
    (
        "Waka・Risuko・Ruka from STAR☆ANIS",
        ("Waka from STAR☆ANIS", "Risuko from STAR☆ANIS", "Ruka from STAR☆ANIS"),
    ),
    (
        "Yuna・Remi・Eri from STAR☆ANIS",
        ("Yuna from STAR☆ANIS", "Remi from STAR☆ANIS", "Eri from STAR☆ANIS"),
    ),
    ("Eri・Remi from STAR☆ANIS", ("Eri from STAR☆ANIS", "Remi from STAR☆ANIS")),
    (
        "Ruka・Mona・Miki from AIKATSU☆STARS!",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
        ),
    ),
    ("Ruka from AIKATSU☆STARS!", ("Ruka from AIKATSU☆STARS!",)),
    (
        "Miho・Miki from AIKATSU☆STARS!",
        ("Miho from AIKATSU☆STARS!", "Miki from AIKATSU☆STARS!"),
    ),
    (
        "Miho・Nanase・Kana from AIKATSU☆STARS!",
        (
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    ("Mona from AIKATSU☆STARS!", ("Mona from AIKATSU☆STARS!",)),
    ("Kana from AIKATSU☆STARS!", ("Kana from AIKATSU☆STARS!",)),
    (
        "Kana・Ruka from AIKATSU☆STARS!",
        ("Kana from AIKATSU☆STARS!", "Ruka from AIKATSU☆STARS!"),
    ),
    (
        "Miki・Ruka・Mona from AIKATSU☆STARS!",
        (
            "Miki from AIKATSU☆STARS!",
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
        ),
    ),
    (
        "Ruka・Mona from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Mona from AIKATSU☆STARS!"),
    ),
    (
        "Ruka・Miki from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Miki from AIKATSU☆STARS!"),
    ),
    ("Miho from AIKATSU☆STARS!", ("Miho from AIKATSU☆STARS!",)),
    (
        "Mona・Ruka from AIKATSU☆STARS!",
        ("Mona from AIKATSU☆STARS!", "Ruka from AIKATSU☆STARS!"),
    ),
    ("Nanase from AIKATSU☆STARS!", ("Nanase from AIKATSU☆STARS!",)),
    (
        "Miki・Miho from AIKATSU☆STARS!",
        ("Miki from AIKATSU☆STARS!", "Miho from AIKATSU☆STARS!"),
    ),
    ("Miki from AIKATSU☆STARS!", ("Miki from AIKATSU☆STARS!",)),
    (
        "Mona・Nanase from AIKATSU☆STARS!",
        ("Mona from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!"),
    ),
    (
        "Ruka・Mona・Miki・Miho・Nanase・Kana from AIKATSU☆STARS!",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Nanase・Kana from AIKATSU☆STARS!",
        ("Nanase from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!"),
    ),
    (
        "Ruka・Nanase from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!"),
    ),
    (
        "Ruka・Kana from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!"),
    ),
    (
        "Miho・Nanase from AIKATSU☆STARS!",
        ("Miho from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!"),
    ),
    (
        "Sena・Rie from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Rie from AIKATSU☆STARS!"),
    ),
    (
        "Sena・Rie・Miki・Kana from AIKATSU☆STARS!",
        (
            "Sena from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    ("SUN&LUNAR", ("SUN&LUNAR",)),
    (
        "Ruka・Nanase・Kana・Miho from AIKATSU☆STARS!",
        (
            "Ruka from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
        ),
    ),
    (
        "Ruka・Sena from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Sena from AIKATSU☆STARS!"),
    ),
    ("Risa/Miho from AIKATSU☆STARS!", ("Risa Aizawa", "Miho from AIKATSU☆STARS!")),
    (
        "Sena・Ruka from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Ruka from AIKATSU☆STARS!"),
    ),
    ("Rie from AIKATSU☆STARS!", ("Rie from AIKATSU☆STARS!",)),
    ("Sena from AIKATSU☆STARS!", ("Sena from AIKATSU☆STARS!",)),
    (
        "Ruka・Miho from AIKATSU☆STARS!",
        ("Ruka from AIKATSU☆STARS!", "Miho from AIKATSU☆STARS!"),
    ),
    (
        "Sena・Miki・Kana from AIKATSU☆STARS!",
        (
            "Sena from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Risa/Miho・Rie・Ruka from AIKATSU☆STARS!",
        (
            "Risa Aizawa",
            "Miho from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Ruka from AIKATSU☆STARS!",
        ),
    ),
    (
        "Sena・Rie・Miki・Kana・Nanase from AIKATSU☆STARS!",
        (
            "Sena from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
        ),
    ),
    (
        "Rie・Kana from AIKATSU☆STARS!",
        ("Rie from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!"),
    ),
    (
        "Miho・Kana from AIKATSU☆STARS!",
        ("Miho from AIKATSU☆STARS!", "Kana from AIKATSU☆STARS!"),
    ),
    (
        "Nanase・Miho・Kana from AIKATSU☆STARS!",
        (
            "Nanase from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Kana・Sena・Miki from AIKATSU☆STARS!",
        (
            "Kana from AIKATSU☆STARS!",
            "Sena from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
        ),
    ),
    (
        "Kana・Nanase from AIKATSU☆STARS!",
        ("Kana from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!"),
    ),
    (
        "Nanase・Rie from AIKATSU☆STARS!",
        ("Nanase from AIKATSU☆STARS!", "Rie from AIKATSU☆STARS!"),
    ),
    (
        "Miki・Nanase from AIKATSU☆STARS!",
        ("Miki from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!"),
    ),
    (
        "Sena・Miki from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Miki from AIKATSU☆STARS!"),
    ),
    (
        "Sena・Nanase from AIKATSU☆STARS!",
        ("Sena from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!"),
    ),
    (
        "Rie・Nanase from AIKATSU☆STARS!",
        ("Rie from AIKATSU☆STARS!", "Nanase from AIKATSU☆STARS!"),
    ),
    (
        "Aine・Mio from BEST FRIENDS!",
        ("Aine from BEST FRIENDS!", "Mio from BEST FRIENDS!"),
    ),
    (
        "Karen・Mirai from BEST FRIENDS!",
        ("Karen from BEST FRIENDS!", "Mirai from BEST FRIENDS!"),
    ),
    ("Mio from BEST FRIENDS!", ("Mio from BEST FRIENDS!",)),
    ("Aine from BEST FRIENDS!", ("Aine from BEST FRIENDS!",)),
    ("Mirai from BEST FRIENDS!", ("Mirai from BEST FRIENDS!",)),
    ("Maika from BEST FRIENDS!", ("Maika from BEST FRIENDS!",)),
    ("Karen from BEST FRIENDS!", ("Karen from BEST FRIENDS!",)),
    (
        "Maika・Ema from BEST FRIENDS!",
        ("Maika from BEST FRIENDS!", "Ema from BEST FRIENDS!"),
    ),
    ("Sakuya from BEST FRIENDS!", ("Sakuya from BEST FRIENDS!",)),
    ("Ema from BEST FRIENDS!", ("Ema from BEST FRIENDS!",)),
    (
        "Sakuya・Kaguya from BEST FRIENDS!",
        ("Sakuya from BEST FRIENDS!", "Kaguya from BEST FRIENDS!"),
    ),
    ("Kaguya from BEST FRIENDS!", ("Kaguya from BEST FRIENDS!",)),
    (
        "Aine・Mio・Maika・Ema from BEST FRIENDS!",
        (
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Maika from BEST FRIENDS!",
            "Ema from BEST FRIENDS!",
        ),
    ),
    (
        "Aine・Mio・Ema・Maika from BEST FRIENDS!",
        (
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Ema from BEST FRIENDS!",
            "Maika from BEST FRIENDS!",
        ),
    ),
    ("Hibiki from BEST FRIENDS!", ("Hibiki from BEST FRIENDS!",)),
    (
        "Mio・Wakaba from BEST FRIENDS!",
        ("Mio from BEST FRIENDS!", "Wakaba from BEST FRIENDS!"),
    ),
    ("Wakaba from BEST FRIENDS!", ("Wakaba from BEST FRIENDS!",)),
    (
        "Hibiki・Alicia from BEST FRIENDS!",
        ("Hibiki from BEST FRIENDS!", "Alicia from BEST FRIENDS!"),
    ),
    (
        "Raki・Aine・Mio from BEST FRIENDS!",
        (
            "Raki from BEST FRIENDS!",
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
        ),
    ),
    (
        "Raki・Aine・Mio from BEST FRIENDS!/Waka・Ruka・Sena",
        (
            "Raki from BEST FRIENDS!",
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Waka from STAR☆ANIS",
            "Ruka from AIKATSU☆STARS!",
            "Sena from AIKATSU☆STARS!",
        ),
    ),
    ("Raki from BEST FRIENDS!", ("Raki from BEST FRIENDS!",)),
    (
        "Mio from BEST FRIENDS!/Sena",
        ("Mio from BEST FRIENDS!", "Sena from AIKATSU☆STARS!"),
    ),
    (
        "Mirai from BEST FRIENDS!/Ruka",
        ("Mirai from BEST FRIENDS!", "Ruka from AIKATSU☆STARS!"),
    ),
    (
        "Raki from BEST FRIENDS!/Waka",
        ("Raki from BEST FRIENDS!", "Waka from STAR☆ANIS"),
    ),
    (
        "Hibiki from BEST FRIENDS!/Risuko/Risa",
        ("Hibiki from BEST FRIENDS!", "Risuko from STAR☆ANIS", "Risa Aizawa"),
    ),
    (
        "Sunao/Sena・Rie・Miki・Kana・Nanase/Aine・Mio・Maika・Ema from BEST FRIENDS!",
        (
            "Sunao from STAR☆ANIS",
            "Sena from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Maika from BEST FRIENDS!",
            "Ema from BEST FRIENDS!",
        ),
    ),
    (
        "Aine・Mio from BEST FRIENDS!/Sena",
        (
            "Aine from BEST FRIENDS!",
            "Mio from BEST FRIENDS!",
            "Sena from AIKATSU☆STARS!",
        ),
    ),
    ("Alicia from BEST FRIENDS!", ("Alicia from BEST FRIENDS!",)),
    (
        "Aine・Mio from BEST FRIENDS!/Waka",
        ("Aine from BEST FRIENDS!", "Mio from BEST FRIENDS!", "Waka from STAR☆ANIS"),
    ),
    (
        "Ayane・Ruka・Rie/Karen from BEST FRIENDS!",
        (
            "Ayane Fujisaki",
            "Ruka from AIKATSU☆STARS!",
            "Rie from AIKATSU☆STARS!",
            "Karen from BEST FRIENDS!",
        ),
    ),
    (
        "Mao・Ruli from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Ruli from STARRY PLANET☆"),
    ),
    (
        "Ayumi・Ann from STARRY PLANET☆",
        ("Ayumi from STARRY PLANET☆", "Ann from STARRY PLANET☆"),
    ),
    (
        "Mao・Ayumi from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Ayumi from STARRY PLANET☆"),
    ),
    (
        "Mao・Kyouko from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Kyouko from STARRY PLANET☆"),
    ),
    (
        "Mao・Ruli・Kyouko・Shiori from STARRY PLANET☆",
        (
            "Mao from STARRY PLANET☆",
            "Ruli from STARRY PLANET☆",
            "Kyouko from STARRY PLANET☆",
            "Shiori from STARRY PLANET☆",
        ),
    ),
    ("Ayumi from STARRY PLANET☆", ("Ayumi from STARRY PLANET☆",)),
    (
        "Ayumi・Ruli from STARRY PLANET☆",
        ("Ayumi from STARRY PLANET☆", "Ruli from STARRY PLANET☆"),
    ),
    ("Meisa from STARRY PLANET☆", ("Meisa from STARRY PLANET☆",)),
    (
        "Shiori・Ruli from STARRY PLANET☆",
        ("Shiori from STARRY PLANET☆", "Ruli from STARRY PLANET☆"),
    ),
    (
        "Mao・Shiori from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Shiori from STARRY PLANET☆"),
    ),
    (
        "Shiori・Ann from STARRY PLANET☆",
        ("Shiori from STARRY PLANET☆", "Ann from STARRY PLANET☆"),
    ),
    (
        "Mao・Ann from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Ann from STARRY PLANET☆"),
    ),
    (
        "Kyouko・Ayumi from STARRY PLANET☆",
        ("Kyouko from STARRY PLANET☆", "Ayumi from STARRY PLANET☆"),
    ),
    (
        "Ruli・Meisa from STARRY PLANET☆",
        ("Ruli from STARRY PLANET☆", "Meisa from STARRY PLANET☆"),
    ),
    (
        "Mao・Meisa from STARRY PLANET☆",
        ("Mao from STARRY PLANET☆", "Meisa from STARRY PLANET☆"),
    ),
    (
        "Ann・Sala from STARRY PLANET☆",
        ("Ann from STARRY PLANET☆", "Sala from STARRY PLANET☆"),
    ),
    (
        "Shiori・Sala from STARRY PLANET☆",
        ("Shiori from STARRY PLANET☆", "Sala from STARRY PLANET☆"),
    ),
    (
        "Ruli・Kyouko from STARRY PLANET☆",
        ("Ruli from STARRY PLANET☆", "Kyouko from STARRY PLANET☆"),
    ),
    (
        "Ayumi・Meisa from STARRY PLANET☆",
        ("Ayumi from STARRY PLANET☆", "Meisa from STARRY PLANET☆"),
    ),
    (
        "Ruka・Mona・Miki from AIKATSU☆STARS! & Waka from STAR☆ANIS",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Waka from STAR☆ANIS",
        ),
    ),
    (
        "Eri from STAR☆ANIS & Miho from AIKATSU☆STARS!",
        ("Eri from STAR☆ANIS", "Miho from AIKATSU☆STARS!"),
    ),
    (
        "Ruka・Mona・Miki・Miho from AIKATSU☆STARS! & Waka・Risuko from STAR☆ANIS",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Waka from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Sunao from STAR☆ANIS & Ruka・Mona・Miki from AIKATSU☆STARS!",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Sunao from STAR☆ANIS",
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
        ),
    ),
    (
        "Ruka・Mona・Miki・Miho・Nanase・Kana from AIKATSU☆STARS! & Waka from STAR☆ANIS",
        (
            "Ruka from AIKATSU☆STARS!",
            "Mona from AIKATSU☆STARS!",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
            "Waka from STAR☆ANIS",
        ),
    ),
    (
        "Waka・Fuuri・Yuna・Remi・Eri・Risuko・Mona・Ruka from STAR☆ANIS & Mona・Miki・Miho・Nanase・Kana from AIKATSU☆STARS!",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Risuko from STAR☆ANIS",
            "Mona from STAR☆ANIS",
            "Ruka from STAR☆ANIS",
            "Miki from AIKATSU☆STARS!",
            "Miho from AIKATSU☆STARS!",
            "Nanase from AIKATSU☆STARS!",
            "Kana from AIKATSU☆STARS!",
        ),
    ),
    (
        "Waka・Fuuri・Yuna・Remi・Eri・Ruka from STAR☆ANIS",
        (
            "Waka from STAR☆ANIS",
            "Fuuri from STAR☆ANIS",
            "Yuna from STAR☆ANIS",
            "Remi from STAR☆ANIS",
            "Eri from STAR☆ANIS",
            "Ruka from STAR☆ANIS",
        ),
    ),
    ("Waka・Eimi", ("Waka Kirishima", "Eimi Naruse")),
    ("Risa・Eimi", ("Risa Aizawa", "Eimi Naruse")),
    ("Ayane・Eri", ("Ayane Fujisaki", "Eri Aino")),
]
# 0000

splitting_exception = {}
for split_exception in splitting_exception_list:
    splitting_exception[split_exception[0]] = split_exception[1]
# Splitting Config
