# Splitting Config

"""
exception collected over the time so that I can re-build it from scratch
"""

splitters = " VS | vs | & | , |, | featuring\. | Featuring\. | featuring | Featuring | feat\. | feat\.|feat\. |feat\.| ft\. | ft\.|ft\. |ft\.| x | × | with |＆| / |/| meets | adding | and "
secondary_splitters = "・|& | &|&| ,|,| ×|× |×| \+ |\+"

splitting_exception_list = [
    ## Force splitting (splitters that are not automatically recognized)
    # :
    ("SawanoHiroyuki[nZk]:Uru", ("Uru",)),
    ("SawanoHiroyuki[nZk]:Honoka Takahashi", ("Honoka Takahashi",)),
    ("SawanoHiroyuki[nZk]:Anly", ("Anly",)),
    ("SawanoHiroyuki[nZk]:LiSA", ("LiSA",)),
    ("SawanoHiroyuki[nZk]:Jean-Ken Johnny", ("Jean-Ken Johnny",)),
    ("SawanoHiroyuki[nZk]:Laco", ("Laco",)),
    ("SawanoHiroyuki[nZk]:ReoNa", ("ReoNa",)),
    ("SawanoHiroyuki[nZk]:mizuki", ("mizuki",)),
    ("SawanoHiroyuki[nZk]:Gemie", ("Gemie",)),
    ("SawanoHiroyuki[nZk]:Yosh", ("Yosh",)),
    ("SawanoHiroyuki[nZk]:Tielle", ("Tielle",)),
    ("SawanoHiroyuki[nZk]:naNami", ("naNami",)),
    ("SawanoHiroyuki[nZk]:Aimer", ("Aimer",)),
    ("(K)NoW_NAME:Ayaka Tachibana", ("Ayaka Tachibana",)),
    ("(K)NoW_NAME:Ayaka Tachibana & NIKIIE", ("Ayaka Tachibana", "NIKIIE")),
    ("(K)NoW_NAME:NIKIIE", ("NIKIIE",)),
    ("(K)NoW_NAME:AIJ", ("AIJ",)),
    ("(K)NoW_NAME:eNu", ("eNu",)),
    ## Force NOT splitting (exception on splitters)
    # ・
    ("G・GRIP", ("G・GRIP",)),
    ("PSY・S", ("PSY・S",)),
    ("A・ZU・NA", ("A・ZU・NA",)),
    ("Ham-chans • Himawari-gumi", ("Ham-chans • Himawari-gumi",)),
    ("Swing・Cats", ("Swing・Cats",)),
    ("F・MAP", ("F・MAP",)),
    ("a・chi-a・chi", ("a・chi-a・chi",)),
    ("hide with Spread Beaver", ("hide with Spread Beaver",)),
    ("A・Times", ("A・Times",)),
    ("SAY・S & Nintama Family", ("SAY・S", "Nintama Family")),
    ("SAY・S and Nintama Family", ("SAY・S", "Nintama Family")),
    ("R・O・N", ("R・O・N",)),
    ("Ja・Ja", ("Ja・Ja",)),
    ("B・B Girls", ("B・B Girls",)),
    ("G・P・S", ("G・P・S",)),
    ("M・A・O", ("M・A・O",)),
    ("Teikoku Kageki-dan・Hana-gumi", ("Teikoku Kageki-dan・Hana-gumi",)),
    # &
    ("Hironobu Kageyama & BROADWAY", ("Hironobu Kageyama & BROADWAY",)),
    (
        "Kishida Kyoudan &THE Akeboshi Rockets",
        ("Kishida Kyoudan &THE Akeboshi Rockets",),
    ),
    ("HIKAKIN & SEIKIN", ("HIKAKIN & SEIKIN",)),
    ("Athena & Robikerottsu", ("Athena & Robikerottsu",)),
    ("QUANGO & SPARKY", ("QUANGO & SPARKY",)),
    ("TAKAO & THE VIEW", ("TAKAO & THE VIEW",)),
    ("KING & QUEEN", ("KING & QUEEN",)),
    ("C&K", ("C&K",)),
    ("P&P", ("P&P",)),
    ("P4 with T", ("P4 with T",)),
    ("MAYA & Z", ("MAYA & Z",)),
    ("Icchi & Naru", ("Icchi & Naru",)),
    ("Licca & Noa", ("Licca", "Noa")),
    (
        'SOIL&"PIMP"SESSIONS feat. Maaya Sakamoto',
        ('SOIL&"PIMP"SESSIONS', "Maaya Sakamoto"),
    ),
    ('SOIL & "PIMP" SESSIONS', ('SOIL & "PIMP" SESSIONS',)),
    ("Kaako & Papa", ("Kaako & Papa",)),
    ("Adiamond -Amy & Bibian-", ("Adiamond -Amy & Bibian-",)),
    ("MAYUKO & Luminous", ("MAYUKO & Luminous",)),
    ("Bars & Melody", ("Bars & Melody",)),
    ("MON & STER", ("MON & STER",)),
    ("MYTH & ROID", ("MYTH & ROID",)),
    ("DEJO & BON", ("DEJO & BON",)),
    ("Kakki & Ash Potato", ("Kakki & Ash Potato",)),
    ("Anamu & Maki", ("Anamu & Maki",)),
    ("SUEMITSU & THE SUEMITH", ("SUEMITSU & THE SUEMITH",)),
    ("TAKAKO&THE CRAZY BOYS", ("TAKAKO&THE CRAZY BOYS",)),
    ("TAKAKO & THE CRAZY BOYS", ("TAKAKO & THE CRAZY BOYS",)),
    ("Oosugi & Hiiko", ("Oosugi & Hiiko",)),
    ("Christy&Clinton", ("Christy&Clinton",)),
    ("Irene & Erika", ("Irene & Erika",)),
    ("Dylan & Catherine", ("Dylan & Catherine",)),
    ("Junich & JJr", ("Junich & JJr",)),
    ("Bread & Butter", ("Bread & Butter",)),
    ("Betsy & Chris", ("Betsy & Chris",)),
    ("RUN&GUN", ("RUN&GUN",)),
    ("Macolin & Pythagoras", ("Macolin & Pythagoras",)),
    ("Rats & Star", ("Rats & Star",)),
    ("Aki & Isao", ("Aki & Isao",)),
    ("Let's Go BOYS & GIRLS", ("Let's Go BOYS & GIRLS",)),
    ("Shirai Takako &CRAZY BOYS", ("Shirai Takako &CRAZY BOYS",)),
    ("TOSS & TURN", ("TOSS & TURN",)),
    ("Chage & Aska", ("Chage & Aska",)),
    ("CHAGE&ASKA", ("CHAGE&ASKA",)),
    ("Earth, Wind & Fire", ("Earth, Wind & Fire",)),
    ("Oranges & Lemons", ("Oranges & Lemons",)),
    ("Rough & Ready", ("Rough & Ready",)),
    ("LOREN&MASH", ("LOREN&MASH",)),
    ("Jack & Betty", ("Jack & Betty",)),
    ("Tackey & Tsubasa", ("Tackey & Tsubasa",)),
    ("AKIMA & NEOS", ("AKIMA & NEOS",)),
    ("Duel Hero Yuu & Atsuto", ("Duel Hero Yuu & Atsuto",)),
    ("You & Explosion Band", ("You & Explosion Band",)),
    ("2&", ("2&",)),
    ("Yumachi & Aina", ("Yumachi & Aina",)),
    (
        "Japanese Geronimo & Love Guerilla Experience",
        ("Japanese Geronimo & Love Guerilla Experience",),
    ),
    # and
    ("Shou and the Moon Dogs", ("Shou and the Moon Dogs",)),
    ("Junko Hori and New Royal", ("Junko Hori and New Royal",)),
    ("Tetsu and Tomo", ("Tetsu and Tomo",)),
    ("HIGH and MIGHTY COLOR", ("HIGH and MIGHTY COLOR",)),
    ("Rokumonsen and Fool Sounds", ("Rokumonsen and Fool Sounds",)),
    ("Big Sofa and the Lazy Boys", ("Big Sofa and the Lazy Boys",)),
    ("devils and realist", ("devils and realist",)),
    ("Lillies and Remains", ("Lillies and Remains",)),
    ("Bird Bear Hare and Fish", ("Bird Bear Hare and Fish",)),
    (
        "Takanori Nishikawa × Fear, and Loathing in Las Vegas",
        (
            "Takanori Nishikawa",
            "Fear, and Loathing in Las Vegas",
        ),
    ),
    ("Tim Timebomb and the Interrupters", ("Tim Timebomb and the Interrupters",)),
    ("Yuusuke (ex. HIGH and MIGHTY COLOR)", ("Yuusuke (ex. HIGH and MIGHTY COLOR)",)),
    # x
    ("OxT", ("OxT",)),
    ("Clover×Clover", ("Clover×Clover",)),
    ("LIP×LIP", ("LIP×LIP",)),
    ("Gothic×Luck", ("Gothic×Luck",)),
    ("High×Joker", ("High×Joker",)),
    ("RhymeTube×Odori Foot Works", ("RhymeTube×Odori Foot Works",)),
    ("salyu × salyu", ("salyu × salyu",)),
    ("Daisy×Daisy", ("Daisy×Daisy",)),
    ("SKET×Sketch", ("SKET×Sketch",)),
    ("kanon×kanon", ("kanon×kanon",)),
    ("DIVA×DIVA", ("DIVA×DIVA",)),
    ("sister×sisters", ("sister×sisters",)),
    ("nana×nana", ("nana×nana",)),
    ("U×Mishi", ("U×Mishi",)),
    ("kanon x kanon", ("kanon x kanon",)),
    # with
    ("Petit Rabbit's with beans", ("Petit Rabbit's with beans",)),
    ("SERENON with K", ("SERENON with K",)),
    ("Cotori with Stitchbird", ("Cotori with Stitchbird",)),
    ("Akebonoyama Chuugaku Band with T", ("Akebonoyama Chuugaku Band with T",)),
    ("MATCHY with QUESTION?", ("MATCHY with QUESTION?",)),
    # ,
    ("Fear, and Loathing in Las Vegas", ("Fear, and Loathing in Las Vegas",)),
    ("Hello, Happy World!", ("Hello, Happy World!",)),
    ("Mix Speaker's,Inc.", ("Mix Speaker's,Inc.",)),
    ("Kamisama, Boku wa Kizuite Shimatta", ("Kamisama, Boku wa Kizuite Shimatta",)),
    ("New man Co.,Ltd.", ("New man Co.,Ltd.",)),
    ("Okino, Shuntaro", ("Okino, Shuntaro",)),
    ("Run Girls, Run!", ("Run Girls, Run!",)),
    ("Wake Up, Girls!", ("Wake Up, Girls!",)),
    ("Wake Up, May'n!", ("Wake Up, May'n!",)),
    ("Kagrra,", ("Kagrra,",)),
    # +
    ("Kaede+Cheek Fairy", ("Kaede+Cheek Fairy",)),
    ("Sister Princess +1", ("Sister Princess +1",)),
    ("nobodyknows+", ("nobodyknows+",)),
    ("Re+sa", ("Re+sa",)),
    ("+Plus", ("+Plus",)),
    ("T-Pistonz+KMC", ("T-Pistonz+KMC",)),
    ("T-Pistonz+KMZ", ("T-Pistonz+KMZ",)),
    ("Alchemy+", ("Alchemy+",)),
    ("stella quintet+", ("stella quintet+",)),
    ("YU+KI", ("YU+KI",)),
    ("Needless★Girls+", ("Needless★Girls+",)),
    ("Yonagahime 3+1", ("Yonagahime 3+1",)),
    ("ASAHINA Bros.+JULI", ("ASAHINA Bros.+JULI",)),
    ("Q;indivi+", ("Q;indivi+",)),
    ("+α/Alfakyun.", ("+α/Alfakyun.",)),
    ("+earth☆sky", ("+earth☆sky",)),
    ("SUMMONERS 2+", ("SUMMONERS 2+",)),
    ("DIALOGUE+", ("DIALOGUE+",)),
    ("MERI+Noriyuki", ("MERI+Noriyuki",)),
    ("sophie+", ("sophie+",)),
    ("Megami-ryousei+α", ("Megami-ryousei+α",)),
    # other
    ("NAMI with Shige×2＆S/N", ("NAMI", "Shige×2", "S/N")),
    ("r.o.r/s", ("r.o.r/s",)),
    ("can/goo", ("can/goo",)),
    ("DISH//", ("DISH//",)),
    ("ON/OFF", ("ON/OFF",)),
    ("S/mileage", ("S/mileage",)),
    ("Konnichiwa\(^o^)/Kirarinbo☆Harry!!!", ("Konnichiwa\(^o^)/Kirarinbo☆Harry!!!",)),
    ("Sol/Lull BOB", ("Sol/Lull BOB",)),
    ("Kisu Koide (PANDA 1/2)", ("Kisu Koide (PANDA 1/2)",)),
    ("H-el-ical//", ("H-el-ical//",)),
    ("22/7", ("22/7",)),
    ("YURiCa/Hanatan", ("YURiCa/Hanatan",)),
    ("Bach/Gounod", ("Johann Sebastian Bach/Charles Gounod",)),
    ("m-flo\u2665DOPING PANDA", ("m-flo", "DOPING PANDA")),
    ## removing longer strings (removing longer string to avoid having dumb artists names)
    ("livetune adding Fukase from SEKAI NO OWARI", ("livetune", "Fukase")),
    ("livetune adding Rin Oikawa (from Q;Indivi)", ("livetune", "Rin Oikawa")),
    ("Tamiya Terashima (Rentrak Japan)", ("Tamiya Terashima",)),
    ("Hamatora - Ryota Osaka & Wataru Hatano", ("Ryota Osaka", "Wataru Hatano")),
    ("GENERATIONS from EXILE TRIBE", ("GENERATIONS",)),
    ("THE RAMPAGE from EXILE TRIBE", ("THE RAMPAGE",)),
    ("FANTASTICS from EXILE TRIBE", ("FANTASTICS",)),
    ("Sandaime J SOUL BROTHERS from EXILE TRIBE", ("Sandaime J SOUL BROTHERS",)),
    ("Aya&chika from D&D", ("Aya Uehara", "Chikano Higa")),
    (
        "SawanoHiroyuki[nZk]:Junki Kono & Sho Yonashiro (JO1)",
        ("SawanoHiroyuki[nZk]", "Junki Kono", "Sho Yonashiro"),
    ),
    ("POLYSICS with Seiya Yamasaki (Kyuuso Nekokami)", ("POLYSICS", "Seiya Yamasaki")),
    ("JO☆STARS~TOMMY, Coda, JIN~", ("JO☆STARS",)),
    ("Saori Hayami (from Eclipse)", ("Saori Hayami",)),
    ("Megumi Nakajima (from Eclipse)", ("Megumi Nakajima",)),
    ("Haruka Tomatsu (from Eclipse)", ("Haruka Tomatsu",)),
    ("AKINO & AIKI from bless4", ("AKINO", "AIKI")),
    ("AKINO from bless4", ("AKINO",)),
    ("AIKI from bless4", ("AIKI",)),
    ("AKINO arai×AKINO from bless4", ("AKINO arai", "AKINO")),
    ("AIKI & AKINO from bless4", ("AIKI", "AKINO")),
    ("TK from Ling Tosite Sigure", ("TK",)),
    ("Yuuki Ozaki(from Galileo Galilei)", ("Yuuki Ozaki",)),
    (
        "Kotaro Oshio with Yuuki Ozaki (from Galileo Galilei)",
        ("Kotaro Oshio", "Yuuki Ozaki"),
    ),
    ("Aya Hirano from Springs", ("Aya Hirano",)),
    (
        "Yuki Kaji, Kishou Taniyama, Yui Ishikawa from attackers",
        ("Yuki Kaji", "Kishou Taniyama", "Yui Ishikawa"),
    ),
    ("Hiroshi Kamiya from No Name", ("Hiroshi Kamiya",)),
    ("Jin ft. MARIA from GARNiDELiA", ("Jin", "MARiA")),
    ("Shinya & Tarantula (From Hi-Timez)", ("Shinya", "Tarantula")),
    ("Argonavis feat. Jin Ogasawara from GYROAXIA", ("Argonavis", "Jin Ogasawara")),
    ("Misaki Kurea from Girls²", ("Misaki Kurea",)),
    (
        "livetune adding Takuro Sugawara from 9mm Parabellum Bullet",
        ("livetune", "Takuro Sugawara"),
    ),
    ("Anna (BON-BON BLANCO)", ("Anna",)),
    ("Jin ft. Takumi Yoshida from phatmans after school", ("Jin", "Takumi Yoshida")),
    ("Shifo from UNIVERS\u2605L D", ("Shifo",)),
    ("HARU＆SAYAKA from UNIVERS★LD", ("HARU", "SAYAKA")),
    ("UL-SAYS [from T.P.D]", ("UL-SAYS",)),
    ("BACK-ON & Lil' Fang (from FAKY)", ("BACK-ON", "Lil' Fang")),
    ("Charisma.com & RYO-Z Oni-san of RIP SLYME", ("Charisma.com", "RYO-Z")),
    ("Naoki Sagawa feat. JOE from PSYCHIC LOVER", ("Naoki Sagawa", "JOE")),
    ("Jin ft. Kouta Matsuyama from Byee the Round", ("Jin", "Kouta Matsuyama")),
    ("Jin ft. Shouichi Taguchi from Sentimental Vector", ("Jin", "Shouichi Taguchi")),
    ("Aztech from Hybrid Thoughts", ("Aztech",)),
    ("Aztech, Paranom & Kasper from Hybrid Thoughts", ("Aztech", "Paranom", "Kasper")),
    ("Tomoyo Mitani (LieN)", ("Tomoyo Mitani",)),
    ("Demon Kakka×Arika Takarano (ALI PROJECT)", ("Demon Kakka", "Arika Takarano")),
    ("I.C.I. a.k.a. Ai Ichikawa", ("I.C.I.",)),
    ("Takayuki Hattori Presents GUNDAM THE ORIGIN", ("Takayuki Hattori",)),
    ("Motohiro Hata meets Sakamichi no Apollon", ("Motohiro Hata",)),
    ("Tortoise Matsumoto (Ulfuls)", ("Tortoise Matsumoto",)),
    ("Yasutaka Nakata (CAPSULE)", ("Yasutaka Nakata",)),
    (
        "GHOST ORACLE DRIVE feat. Sen to Chihiro Chicchi (BiSH)",
        ("GHOST ORACLE DRIVE", "CENT CHiHiRO CHiTTiii"),
    ),
    ("TeddyLoid feat. Aina The End (BiSH)", ("TeddyLoid", "AiNA THE END")),
    ("SUGIZO feat. Aina The End (BiSH)", ("SUGIZO", "AiNA THE END")),
    ("Risa Aizawa (Dempagumi.inc)", ("Risa Aizawa",)),
    ("KinKi Kids (Koichi Domoto)", ("KinKi Kids",)),
    ("KinKi Kids (Tsuyoshi Domoto)", ("KinKi Kids",)),
    ("Suu (SILENT SIREN)", ("Sumire Yoshida",)),
    ("☆Taku Takahashi of m-flo", ("Taku Takahashi",)),
    ("Q-MHz feat. Mitsuhiro Hidaka a.k.a. SKY-HI", ("Q-MHz", "SKY-HI")),
    ("aki a.k.a Aki Deguchi", ("aki",)),
    ("ELISA connect EFP", ("ELISA",)),
    (
        "Kuricorder Quartet feat. Sou Matsumoto (GOING UNDER GROUND)",
        ("Kuricorder Quartet", "Sou Matsumoto"),
    ),
    ("ichigo from Kishida Kyoudan &THE Akeboshi Rockets", ("ichigo",)),
    ## Reformatting of the string (reformate the string by adding or removing some part to have better artists name)
    ("yama (feat. Nakimushi)", ("yama", "Nakimushi")),
    (
        "Tenshou Gakuen Seito・Kyoushi Ichidou",
        ("Tenshou Gakuen Seito Ichidou", "Tenshou Gakuen Kyoushi Ichidou"),
    ),
    ("ReyMagtoto-NonoyTan", ("RAY MAGTOTO", "NONOY TAN")),
    ("Becky (& PokePark KIDS Gasshou-dan)", ("Becky", "PokePark KIDS Gasshou-dan")),
    ("Masayoshi Ooishi (feat.Riria.)", ("Masayoshi Ooishi", "Riria.")),
    ("Basement Jaxx (feat. Lisa Kekaula)", ("Basement Jaxx", "Lisa Kekaula")),
    ("Moe Shop (feat.TORIENA)", ("Moe Shop", "TORIENA")),
    (
        "Pokemon Kids & Unshou Ishizuka (+Ikue Ootani)",
        ("Pokemon Kids", "Unshou Ishizuka", "Ikue Ootani"),
    ),
    ("Pokemon Kids (+Ikue Ootani)", ("Pokemon Kids", "Ikue Ootani")),
    (
        "HoneyWorks meets Sayuringo Gundan + Manatsu-san Respect Gundan from Nogizaka46",
        ("HoneyWorks", "Sayuringo Gundan", "Manatsu-san Respect Gundan", "Nogizaka46"),
    ),
    ("G-Eazy (featuring Bente Violet McPherson)", ("G-Eazy", "Bente Violet McPherson")),
    ("Masayoshi Ooishi (feat. Yukari Tamura)", ("Masayoshi Ooishi", "Yukari Tamura")),
    (
        "Masayoshi Ooishi (feat. Hiroki Yasumoto)",
        ("Masayoshi Ooishi", "Hiroki Yasumoto"),
    ),
    (
        "M. Charlton-C. Cecchetto / M. Bonsanto-R. Rossi",
        ("Malcolm Charlton", "Claudio Cecchetto", "Matteo Bonsanto", "Roberto Rossi"),
    ),
    ("Akiko & Naoko Kobayashi", ("Akiko Kobayashi", "Naoko Kobayashi")),
    ("Kevin Penkin [feat. Emi Evans]", ("Kevin Penkin", "Emi Evans")),
    (
        "Shirahamazaka Koukou Gasshou-bu & Seigaku-bu",
        ("Shirahamazaka Koukou Gasshou-bu", "Shirahamazaka Koukou Seigaku-bu"),
    ),
]
